$axure.loadCurrentPage({
  "url":"新增客户.html",
  "generationDate":new Date(1446432604950.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"82a03097362c4009afffc2112ac7131c",
    "type":"Axure:Page",
    "name":"新增客户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"96502494ff7c4c4087552dad747032df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":30},
            "size":{
              "width":786,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbb121a768854c47926663904055498c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":30},
                "size":{
                  "width":786,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u0.png"}},
{
          "id":"4f295406651242e4bdbf10ba5a493c96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":30},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fecc6d8c39c4a3ebb2700eb61c6b909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":30},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"b1921d23aebe46fa8e688ce54f537d71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":274,
              "y":38},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995679f45d3b43a8a150dda51a7ba55f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":274,
                  "y":38},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"888433e1734b4eafb73e607c782746b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":1024,
              "y":36},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456b3476c157447a85d41d24cf77bebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":1024,
                  "y":36},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ff6188cc6604267b436435ed878e363",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":540},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310d7054b88a45e6b143cccb3ee27126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":540},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"0bf5aa4650df47ddac4bfc0833b06d52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":865,
              "y":545},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef76dbded2a74c289d246b1169ebbe52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":865,
                  "y":545},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u71.png"}},
{
          "id":"4966efd7bee3463cbf623d25d6606c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":951,
              "y":545},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fecf575d2c74526af0eb0a9bb085cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":951,
                  "y":545},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u73.png"}},
{
          "id":"4332ee683fd349ddbbbd10c66a86867a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":300,
              "y":90},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94645dde7276412fb3e2c35576d1abae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25fa64d21c654d4cb22bcbb82ffd67a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":90},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096c47ff09dd481c8e2be0fb4c23dee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":90},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"5b4304a949e9408280ac5d64ce127d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":679,
              "y":90},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cf9700698e04566a5fcf2bb94f2acc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":679,
                  "y":90},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dac4f00eb25f4270bf1e489026c2ec56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":90},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dccc2699987d4fbb801b4bc2260fc34e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":90},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"e7a1fd48677a4a32b76ea3f2776bb764",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":300,
              "y":155},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb13fba29f714633900ee2919ec15437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":300,
                  "y":155},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7854a1ec16bf4ad0a935f25bcc966f8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":155},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce3de3aa950740b3a09a133cf99b9595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":155},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"ab77ffe01bbb488e9c7ba916e1fc1a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":684,
              "y":155},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc7eb695384041d3b114aad8400e4564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":684,
                  "y":155},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13eaa4028e7e49e684a70d741735d7ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "location":{
              "x":814,
              "y":155},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f1c07c5be64e10b2c724b7c866b790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "location":{
                  "x":814,
                  "y":155},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"904676ac0dac44ce833a35e28bf64d6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1011,
              "y":160},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691ff6f8d90b48a59a1de0e78c99e770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1011,
                  "y":160},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}},
{
          "id":"a40563c29be64189a0cb669e1360b80f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":300,
              "y":229},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1adff28b5f4f4662abe0e5b197b54ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":300,
                  "y":229},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d74d090543c04fba9ed8821e52de3db4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":229},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdbecc61728e4d228ea171d29c2a265b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":229},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"547a3fe263e9499183b9d00f9706a5b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":684,
              "y":229},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ce3026b63c43159abbcadccaaa161c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":684,
                  "y":229},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c05df8826e345479b5e762aae1abbd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":814,
              "y":229},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8751e24a7a7642a1b14339e0b546c52f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":814,
                  "y":229},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"815dfab2755c47bfafd9bebc97c5bc68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":280},
            "size":{
              "width":734,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93f6ab6b4544165b6d95d97655e7094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":280},
                "size":{
                  "width":734,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u40.png"}},
{
          "id":"82525f6e7c2141068a50b51c7464a486",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":300,
              "y":490},
            "size":{
              "width":734,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33d985c067784bf196c710bb00ee63eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":490},
                "size":{
                  "width":734,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u42.png"}},
{
          "id":"af400309b73242bbbe76b323d7cf98d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":280},
            "size":{
              "width":734,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04673d7ef38d404082fb203525d4a07e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":280},
                "size":{
                  "width":734,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u44.png"}},
{
          "id":"afe58ec66a164aac8026e50c74a9f265",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":320,
              "y":286},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7663272caa148f09cdf66174c776c86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":320,
                  "y":286},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04e27cc91a1c4a85955d189aeaf2ba0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":460,
              "y":286},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f46b06a8a014c568ca5c5b69308842c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":460,
                  "y":286},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bdd2a5a00cf42b7add6a940761bd5a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":578,
              "y":286},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e5b67f4fbaa4093af207077d13e500b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":578,
                  "y":286},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"451c13a1bdd94ac8b5b8b0bcef1bc982",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":734,
              "y":286},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"008db1b8b3714cd499b5520feba2e1e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":734,
                  "y":286},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cfd17146846409a9ec653ad1c8ac0d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":926,
              "y":286},
            "size":{
              "width":76,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"103633a3f8614395b2a6334a1cb89460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":926,
                  "y":286},
                "size":{
                  "width":76,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1cb2000631a44e882e8a384d90e9a3e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":280},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"4ebbcf19a9684eb6a517deb7fc607d4c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":280},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"d2f5ca5d169241eeaaa82c9502077733",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":654,
              "y":280},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"a7c8353d3d83406393ad587ea7da39da",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":905,
              "y":280},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"6211d9b2f01a495782b316a113f23021",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":330},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"f3969ffb7dce444c84f21d642fd4a059",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":362},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"56311cf16921414fb7278f8a4c4e31a0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":392},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"89b452bd80be4a3b9a4e34b5b5f8adc6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":423},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"977fc922d98446e9a03167698be9bc67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":167},
            "size":{
              "width":13,
              "height":9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"723bb592dcc0444d9e57b9f2fc6d7eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":629,
                  "y":167},
                "size":{
                  "width":13,
                  "height":9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "96502494ff7c4c4087552dad747032df":{
      "scriptId":"u0"},
    "fbb121a768854c47926663904055498c":{
      "scriptId":"u1"},
    "4f295406651242e4bdbf10ba5a493c96":{
      "scriptId":"u2"},
    "1fecc6d8c39c4a3ebb2700eb61c6b909":{
      "scriptId":"u3"},
    "b1921d23aebe46fa8e688ce54f537d71":{
      "scriptId":"u4"},
    "995679f45d3b43a8a150dda51a7ba55f":{
      "scriptId":"u5"},
    "888433e1734b4eafb73e607c782746b8":{
      "scriptId":"u6"},
    "456b3476c157447a85d41d24cf77bebd":{
      "scriptId":"u7"},
    "5ff6188cc6604267b436435ed878e363":{
      "scriptId":"u8"},
    "310d7054b88a45e6b143cccb3ee27126":{
      "scriptId":"u9"},
    "0bf5aa4650df47ddac4bfc0833b06d52":{
      "scriptId":"u10"},
    "ef76dbded2a74c289d246b1169ebbe52":{
      "scriptId":"u11"},
    "4966efd7bee3463cbf623d25d6606c94":{
      "scriptId":"u12"},
    "2fecf575d2c74526af0eb0a9bb085cf5":{
      "scriptId":"u13"},
    "4332ee683fd349ddbbbd10c66a86867a":{
      "scriptId":"u14"},
    "94645dde7276412fb3e2c35576d1abae":{
      "scriptId":"u15"},
    "25fa64d21c654d4cb22bcbb82ffd67a3":{
      "scriptId":"u16"},
    "096c47ff09dd481c8e2be0fb4c23dee1":{
      "scriptId":"u17"},
    "5b4304a949e9408280ac5d64ce127d56":{
      "scriptId":"u18"},
    "4cf9700698e04566a5fcf2bb94f2acc2":{
      "scriptId":"u19"},
    "dac4f00eb25f4270bf1e489026c2ec56":{
      "scriptId":"u20"},
    "dccc2699987d4fbb801b4bc2260fc34e":{
      "scriptId":"u21"},
    "e7a1fd48677a4a32b76ea3f2776bb764":{
      "scriptId":"u22"},
    "eb13fba29f714633900ee2919ec15437":{
      "scriptId":"u23"},
    "7854a1ec16bf4ad0a935f25bcc966f8c":{
      "scriptId":"u24"},
    "ce3de3aa950740b3a09a133cf99b9595":{
      "scriptId":"u25"},
    "ab77ffe01bbb488e9c7ba916e1fc1a22":{
      "scriptId":"u26"},
    "bc7eb695384041d3b114aad8400e4564":{
      "scriptId":"u27"},
    "13eaa4028e7e49e684a70d741735d7ca":{
      "scriptId":"u28"},
    "20f1c07c5be64e10b2c724b7c866b790":{
      "scriptId":"u29"},
    "904676ac0dac44ce833a35e28bf64d6b":{
      "scriptId":"u30"},
    "691ff6f8d90b48a59a1de0e78c99e770":{
      "scriptId":"u31"},
    "a40563c29be64189a0cb669e1360b80f":{
      "scriptId":"u32"},
    "1adff28b5f4f4662abe0e5b197b54ebc":{
      "scriptId":"u33"},
    "d74d090543c04fba9ed8821e52de3db4":{
      "scriptId":"u34"},
    "cdbecc61728e4d228ea171d29c2a265b":{
      "scriptId":"u35"},
    "547a3fe263e9499183b9d00f9706a5b4":{
      "scriptId":"u36"},
    "a0ce3026b63c43159abbcadccaaa161c":{
      "scriptId":"u37"},
    "1c05df8826e345479b5e762aae1abbd6":{
      "scriptId":"u38"},
    "8751e24a7a7642a1b14339e0b546c52f":{
      "scriptId":"u39"},
    "815dfab2755c47bfafd9bebc97c5bc68":{
      "scriptId":"u40"},
    "d93f6ab6b4544165b6d95d97655e7094":{
      "scriptId":"u41"},
    "82525f6e7c2141068a50b51c7464a486":{
      "scriptId":"u42"},
    "33d985c067784bf196c710bb00ee63eb":{
      "scriptId":"u43"},
    "af400309b73242bbbe76b323d7cf98d8":{
      "scriptId":"u44"},
    "04673d7ef38d404082fb203525d4a07e":{
      "scriptId":"u45"},
    "afe58ec66a164aac8026e50c74a9f265":{
      "scriptId":"u46"},
    "a7663272caa148f09cdf66174c776c86":{
      "scriptId":"u47"},
    "04e27cc91a1c4a85955d189aeaf2ba0c":{
      "scriptId":"u48"},
    "2f46b06a8a014c568ca5c5b69308842c":{
      "scriptId":"u49"},
    "5bdd2a5a00cf42b7add6a940761bd5a7":{
      "scriptId":"u50"},
    "8e5b67f4fbaa4093af207077d13e500b":{
      "scriptId":"u51"},
    "451c13a1bdd94ac8b5b8b0bcef1bc982":{
      "scriptId":"u52"},
    "008db1b8b3714cd499b5520feba2e1e4":{
      "scriptId":"u53"},
    "9cfd17146846409a9ec653ad1c8ac0d8":{
      "scriptId":"u54"},
    "103633a3f8614395b2a6334a1cb89460":{
      "scriptId":"u55"},
    "d1cb2000631a44e882e8a384d90e9a3e":{
      "scriptId":"u56"},
    "4ebbcf19a9684eb6a517deb7fc607d4c":{
      "scriptId":"u57"},
    "d2f5ca5d169241eeaaa82c9502077733":{
      "scriptId":"u58"},
    "a7c8353d3d83406393ad587ea7da39da":{
      "scriptId":"u59"},
    "6211d9b2f01a495782b316a113f23021":{
      "scriptId":"u60"},
    "f3969ffb7dce444c84f21d642fd4a059":{
      "scriptId":"u61"},
    "56311cf16921414fb7278f8a4c4e31a0":{
      "scriptId":"u62"},
    "89b452bd80be4a3b9a4e34b5b5f8adc6":{
      "scriptId":"u63"},
    "977fc922d98446e9a03167698be9bc67":{
      "scriptId":"u64"},
    "723bb592dcc0444d9e57b9f2fc6d7eb8":{
      "scriptId":"u65"}}});