$axure.loadCurrentPage({
  "url":"采购明细表.html",
  "generationDate":new Date(1446432609430.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cc9c0dfc4fe24889b541d88c5ba9effa",
    "type":"Axure:Page",
    "name":"采购明细表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1229d031e20b41ec85b3537a4f51ec67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe012863a38a4b9ea4087d927884ea3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"9a5367092e3449129d1bb22ca545d7fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672cf347dc62454889837345b3f3790c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"264b402dc16d40808d4812584d1410a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb973570b0254072a79f4c04c1801e5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"0727baeb810c4507b63eb43245ccd847",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"c1ed6355c297477fbffbcf1498d68724",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ecfae23f66b489fbb7c33d34c73d8b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"185908e777bd4feaa84c7ae8b1a3c6c4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"ab7281a629bd4861839a120a0f3ecd1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fa26997abd34d3bb825635dcd81b596",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94463d600987457f9056d0a0abe53ab4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"a0288a7a2a0a46b380b232e2299f8ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32bdbab848414f21956b05e9887e551d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50365db223f14d969571f661f6eb44b5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"2f5cabb9f2ec41f2a61edfa9e4980bbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad0051e2e5f4a148dcba984e905a420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2a2fc32ed234942930ea29a2a4e291f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"6baf2ecfa751400089bd9c453591db22",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c1426275d314b66acd178e70425102d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"73632057f4eb4a4db6cba041f2fb5f93",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd755cc9c1841e78f20379721bbf282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9377110d9fde4babbff02a644744bc7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6857d4b581e74a59bdda6b0b58bc785b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"dd27fcef3c74428bba4abc1ad7e78c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"893801f195d644e0b629f26bfc31fcdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5537efb6d704de28781083c6beec3c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2db22fd192a43dbad4645b70d138668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a4632726f6444e9a6ac03ab4cc1d844",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34bb413089d2410f89d4174b28a39503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"016635eaabd74c4da2def95f51049088",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11cdb23a5ad4756abb8a4a4a2d9c2a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a52c4640b9354f62b5f2b64387bd8cf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdad8fb2ada8415491858c37c9485bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"b8d60b38b1a6443d99c361a700579c65",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9bcd8acbc424fa6bef1f8d70d57ed7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"06f29c0135e341a8b247091cc88e60b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82d3652259224345bead04d01b016091",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"a7cabe6825b546db825deb5bab336e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0da1560721d14c9c87478aa01fb2e1d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67ec4991e5324dcbbaa1eb3f9eedd6b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8992b6424fba4dcf8b830c5c612cf092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"006c30fcf0d94956baca5439a5f0ddf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4a9d5992e744d3942bb7ec5d3e8449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"241266b8e3844424a1b0f73c12a3833d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"110033c6ae4f435d939f7e3de3501a6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb8cc1451f5d423aac62302413b489c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f8b389a1944b98851f7cb1fdda2409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd89330e70b2455cae3a939977fd947d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ca434c53dc44929ccf85ac0d86993a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62626a518cf948f5aabff181d77c5554",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89eec3ff8274dc181e290c501d76c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"592d6a2adb0647c3a4117f44b214c358",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e1f8818758e4984be824c2d13ed0b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e75f55a1ec04f2fb3b61bbb1b21e9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7303c85cf347c19783f4d1c83865db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c9288f1609e4ab1a1d3b155b820fc38",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1263cf3ab75d4a169e32d504919affe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44f86338a5034ef69dd1dcf60fabeb22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d160c7dbada240109016a7629718d18b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"58f2cd302d0c47ffacc6397083ce6dce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327489cf7c434be3a5cca4dc179a22ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"0058ece265554c48b0ac2232ef7c42f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af633db8e154e7fbe4559332e23b0e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"4cba9bf4f34349399f16931be53e6763",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d36b4decaee47e4abf588335e406d4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"0fcfcc0f95844f44ae4011151d87d68a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":345,
              "y":134},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c934de37956946478fb1166b36d2a131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":345,
                  "y":134},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98b5f01cb4c2472a926a98ad20ad80dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":258},
            "size":{
              "width":1766,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42fc1d87123c4c67a019aa61cffdba34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":258},
                "size":{
                  "width":1766,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u69.png"}},
{
          "id":"492155005d02423ba2014a81961613da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a187a0a260c241f7a5cd0ece26c1282e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdde8b04f705459cb237062275f6238d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":252,
              "y":195},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5526fbceb34bc08e03a4a8a91e80fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":252,
                  "y":195},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4c03e7c2425499fb44d24dab74eba94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":226},
            "size":{
              "width":326,
              "height":325}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9862132c7dc247529168ff960827fbdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":226},
                "size":{
                  "width":326,
                  "height":325}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u75.png"}},
{
          "id":"25718ef23d6f4b648c609ec1e95e414f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":195},
            "size":{
              "width":200,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff33a17ef8c47b3af77fbee0df8224e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":195},
                "size":{
                  "width":200,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u77.png"}},
{
          "id":"2837c1ccd770409995f0139aa4266d0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":209},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9122473db98a4f3bb32e3bcdbf8ff753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":209},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"1b20db4fe79640b2afeb9dc4078d685b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":194},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f7482695d4741b0bee3fe209fe62e81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":194},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u81.png"}},
{
          "id":"d67acd59e1ad4371bcfa1a6301599d16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":199},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cbe1e97c4284392bc42845efeb72f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":199},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u83.png"}},
{
          "id":"8565cdb9ac254379b6850cdbff7b7600",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "lineSpacing":"48px",
            "location":{
              "x":374,
              "y":237},
            "size":{
              "width":61,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a82da14a13364dab8e1c8d1e21dd79b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "lineSpacing":"48px",
                "location":{
                  "x":374,
                  "y":237},
                "size":{
                  "width":61,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ad36484130748119e158c0b7d54bb00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":250},
            "size":{
              "width":102,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"450b789705534d43b0e042e5eeda326c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":250},
                "size":{
                  "width":102,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u87.png"}},
{
          "id":"ff7b4d7e78c246819f7f82e4b10635ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":255},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"788c5a7f3c804203a5e07f09ab8f844c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":255},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}},
{
          "id":"a2dc24c8c65c4fae95f16334163a8207",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":574,
              "y":250},
            "size":{
              "width":102,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"280530c723194c2199d68b177c5d57d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":574,
                  "y":250},
                "size":{
                  "width":102,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u87.png"}},
{
          "id":"4660a10c78464359a965352b468f9982",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":255},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb6ee8fb9de40ca858d3eba0572a053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":255},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}},
{
          "id":"994e359488684c0682d5a4190ffbc2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":555,
              "y":254},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3e9f5cb4e4042b5ac1c03391488a557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":555,
                  "y":254},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd1ef9e44cd2475aa091687164379c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":298},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a06223b2456d422382d2cb949a1c040f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":298},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"a79fbe9f87b545fe99fe6c5270b955fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":348},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4a5fb8931f144bda99b87542fd0e295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":348},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"1f0426f914994af799ab688ec982f0ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":443},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a0b284fa2aa4c70ae8d9472e1e585c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":443},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"4ad2566974d740d69aaccd7c39e4e6bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":305},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b80268e05ead4648bf5af7df544da2a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":305},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"bb6d4f5733f24bc3b71e673d8bdab881",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":354},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92fe2242e23746e9a7fd627b86056f0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":354},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"7b03cc92b55c4c5d9bae1e33cc53cd57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":450},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5346182218ae4c5780e21d414308fb56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":450},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"b85e3373663f4b6685e9afe14a5fe43f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"400",
            "location":{
              "x":448,
              "y":378},
            "size":{
              "width":223,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713640e8d2ca4cdd8786a4cf8bf21c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"400",
                "location":{
                  "x":448,
                  "y":378},
                "size":{
                  "width":223,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9088f6d977444c10babf5be3e7aa8ce5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"400",
            "location":{
              "x":379,
              "y":514},
            "size":{
              "width":41,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e9cf2ebdbf4a56b157f647099a31f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"400",
                "location":{
                  "x":379,
                  "y":514},
                "size":{
                  "width":41,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c7c3e18dbdf46e68a69388000841474",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":514},
            "size":{
              "width":6,
              "height":12},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b59c5777dc747e79ca743ee3c885c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":514},
                "size":{
                  "width":6,
                  "height":12},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u113.png"}},
{
          "id":"1b11044954be410db7bbe111e5dbbf67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":506},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e620f70ef114b4d911a17cb4524dc10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":566,
                  "y":506},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u115.png"}},
{
          "id":"afe1cab3677a474e8b15fa7fcdd3996b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":626,
              "y":506},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d7761e8ae5b47edbe8dba98d27f63d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":626,
                  "y":506},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u117.png"}},
{
          "id":"cc45e18fe3404f4d8a65fbe822fed73b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1842,
              "y":200},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb777dcb53343d19b97153fc1213f1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1842,
                  "y":200},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u115.png"}},
{
          "id":"e2bd85db076f429eb3e4c28adecf7b34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":1902,
              "y":200},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a60f57faa7b4cd983687de779981fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":1902,
                  "y":200},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u117.png"}},
{
          "id":"8c1d209d48ba4de8bceab5194712faee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":305},
            "size":{
              "width":580,
              "height":583}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8851a69dc3e4421bd7d0d832a802aae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":305},
                "size":{
                  "width":580,
                  "height":583}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u123.png"}},
{
          "id":"a0de5ca89171496db986de35f64fea76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":506},
            "size":{
              "width":787,
              "height":585}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0f40ab57ec45a58fe1b7a6a0c37004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":506},
                "size":{
                  "width":787,
                  "height":585}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u125.png"}},
{
          "id":"9baf60470f184141b0b5aa05b626ad2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1032,
              "y":305},
            "size":{
              "width":517,
              "height":581}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e4ea520491a401f90586bb81c40ac02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1032,
                  "y":305},
                "size":{
                  "width":517,
                  "height":581}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u127.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1229d031e20b41ec85b3537a4f51ec67":{
      "scriptId":"u0"},
    "fe012863a38a4b9ea4087d927884ea3b":{
      "scriptId":"u1"},
    "9a5367092e3449129d1bb22ca545d7fd":{
      "scriptId":"u2"},
    "672cf347dc62454889837345b3f3790c":{
      "scriptId":"u3"},
    "264b402dc16d40808d4812584d1410a6":{
      "scriptId":"u4"},
    "fb973570b0254072a79f4c04c1801e5d":{
      "scriptId":"u5"},
    "0727baeb810c4507b63eb43245ccd847":{
      "scriptId":"u6"},
    "c1ed6355c297477fbffbcf1498d68724":{
      "scriptId":"u7"},
    "7ecfae23f66b489fbb7c33d34c73d8b8":{
      "scriptId":"u8"},
    "185908e777bd4feaa84c7ae8b1a3c6c4":{
      "scriptId":"u9"},
    "ab7281a629bd4861839a120a0f3ecd1d":{
      "scriptId":"u10"},
    "2fa26997abd34d3bb825635dcd81b596":{
      "scriptId":"u11"},
    "94463d600987457f9056d0a0abe53ab4":{
      "scriptId":"u12"},
    "a0288a7a2a0a46b380b232e2299f8ed0":{
      "scriptId":"u13"},
    "32bdbab848414f21956b05e9887e551d":{
      "scriptId":"u14"},
    "50365db223f14d969571f661f6eb44b5":{
      "scriptId":"u15"},
    "2f5cabb9f2ec41f2a61edfa9e4980bbf":{
      "scriptId":"u16"},
    "9ad0051e2e5f4a148dcba984e905a420":{
      "scriptId":"u17"},
    "e2a2fc32ed234942930ea29a2a4e291f":{
      "scriptId":"u18"},
    "6baf2ecfa751400089bd9c453591db22":{
      "scriptId":"u19"},
    "5c1426275d314b66acd178e70425102d":{
      "scriptId":"u20"},
    "73632057f4eb4a4db6cba041f2fb5f93":{
      "scriptId":"u21"},
    "8cd755cc9c1841e78f20379721bbf282":{
      "scriptId":"u22"},
    "9377110d9fde4babbff02a644744bc7d":{
      "scriptId":"u23"},
    "6857d4b581e74a59bdda6b0b58bc785b":{
      "scriptId":"u24"},
    "dd27fcef3c74428bba4abc1ad7e78c87":{
      "scriptId":"u25"},
    "893801f195d644e0b629f26bfc31fcdb":{
      "scriptId":"u26"},
    "e5537efb6d704de28781083c6beec3c7":{
      "scriptId":"u27"},
    "a2db22fd192a43dbad4645b70d138668":{
      "scriptId":"u28"},
    "4a4632726f6444e9a6ac03ab4cc1d844":{
      "scriptId":"u29"},
    "34bb413089d2410f89d4174b28a39503":{
      "scriptId":"u30"},
    "016635eaabd74c4da2def95f51049088":{
      "scriptId":"u31"},
    "c11cdb23a5ad4756abb8a4a4a2d9c2a3":{
      "scriptId":"u32"},
    "a52c4640b9354f62b5f2b64387bd8cf9":{
      "scriptId":"u33"},
    "fdad8fb2ada8415491858c37c9485bae":{
      "scriptId":"u34"},
    "b8d60b38b1a6443d99c361a700579c65":{
      "scriptId":"u35"},
    "c9bcd8acbc424fa6bef1f8d70d57ed7c":{
      "scriptId":"u36"},
    "06f29c0135e341a8b247091cc88e60b9":{
      "scriptId":"u37"},
    "82d3652259224345bead04d01b016091":{
      "scriptId":"u38"},
    "a7cabe6825b546db825deb5bab336e1a":{
      "scriptId":"u39"},
    "0da1560721d14c9c87478aa01fb2e1d2":{
      "scriptId":"u40"},
    "67ec4991e5324dcbbaa1eb3f9eedd6b1":{
      "scriptId":"u41"},
    "8992b6424fba4dcf8b830c5c612cf092":{
      "scriptId":"u42"},
    "006c30fcf0d94956baca5439a5f0ddf1":{
      "scriptId":"u43"},
    "9c4a9d5992e744d3942bb7ec5d3e8449":{
      "scriptId":"u44"},
    "241266b8e3844424a1b0f73c12a3833d":{
      "scriptId":"u45"},
    "110033c6ae4f435d939f7e3de3501a6d":{
      "scriptId":"u46"},
    "eb8cc1451f5d423aac62302413b489c5":{
      "scriptId":"u47"},
    "31f8b389a1944b98851f7cb1fdda2409":{
      "scriptId":"u48"},
    "bd89330e70b2455cae3a939977fd947d":{
      "scriptId":"u49"},
    "37ca434c53dc44929ccf85ac0d86993a":{
      "scriptId":"u50"},
    "62626a518cf948f5aabff181d77c5554":{
      "scriptId":"u51"},
    "d89eec3ff8274dc181e290c501d76c5c":{
      "scriptId":"u52"},
    "592d6a2adb0647c3a4117f44b214c358":{
      "scriptId":"u53"},
    "2e1f8818758e4984be824c2d13ed0b98":{
      "scriptId":"u54"},
    "2e75f55a1ec04f2fb3b61bbb1b21e9e3":{
      "scriptId":"u55"},
    "3a7303c85cf347c19783f4d1c83865db":{
      "scriptId":"u56"},
    "7c9288f1609e4ab1a1d3b155b820fc38":{
      "scriptId":"u57"},
    "1263cf3ab75d4a169e32d504919affe9":{
      "scriptId":"u58"},
    "44f86338a5034ef69dd1dcf60fabeb22":{
      "scriptId":"u59"},
    "d160c7dbada240109016a7629718d18b":{
      "scriptId":"u60"},
    "58f2cd302d0c47ffacc6397083ce6dce":{
      "scriptId":"u61"},
    "327489cf7c434be3a5cca4dc179a22ff":{
      "scriptId":"u62"},
    "0058ece265554c48b0ac2232ef7c42f2":{
      "scriptId":"u63"},
    "8af633db8e154e7fbe4559332e23b0e1":{
      "scriptId":"u64"},
    "4cba9bf4f34349399f16931be53e6763":{
      "scriptId":"u65"},
    "5d36b4decaee47e4abf588335e406d4a":{
      "scriptId":"u66"},
    "0fcfcc0f95844f44ae4011151d87d68a":{
      "scriptId":"u67"},
    "c934de37956946478fb1166b36d2a131":{
      "scriptId":"u68"},
    "98b5f01cb4c2472a926a98ad20ad80dc":{
      "scriptId":"u69"},
    "42fc1d87123c4c67a019aa61cffdba34":{
      "scriptId":"u70"},
    "492155005d02423ba2014a81961613da":{
      "scriptId":"u71"},
    "a187a0a260c241f7a5cd0ece26c1282e":{
      "scriptId":"u72"},
    "cdde8b04f705459cb237062275f6238d":{
      "scriptId":"u73"},
    "3f5526fbceb34bc08e03a4a8a91e80fa":{
      "scriptId":"u74"},
    "b4c03e7c2425499fb44d24dab74eba94":{
      "scriptId":"u75"},
    "9862132c7dc247529168ff960827fbdb":{
      "scriptId":"u76"},
    "25718ef23d6f4b648c609ec1e95e414f":{
      "scriptId":"u77"},
    "0ff33a17ef8c47b3af77fbee0df8224e":{
      "scriptId":"u78"},
    "2837c1ccd770409995f0139aa4266d0c":{
      "scriptId":"u79"},
    "9122473db98a4f3bb32e3bcdbf8ff753":{
      "scriptId":"u80"},
    "1b20db4fe79640b2afeb9dc4078d685b":{
      "scriptId":"u81"},
    "1f7482695d4741b0bee3fe209fe62e81":{
      "scriptId":"u82"},
    "d67acd59e1ad4371bcfa1a6301599d16":{
      "scriptId":"u83"},
    "5cbe1e97c4284392bc42845efeb72f18":{
      "scriptId":"u84"},
    "8565cdb9ac254379b6850cdbff7b7600":{
      "scriptId":"u85"},
    "a82da14a13364dab8e1c8d1e21dd79b0":{
      "scriptId":"u86"},
    "7ad36484130748119e158c0b7d54bb00":{
      "scriptId":"u87"},
    "450b789705534d43b0e042e5eeda326c":{
      "scriptId":"u88"},
    "ff7b4d7e78c246819f7f82e4b10635ba":{
      "scriptId":"u89"},
    "788c5a7f3c804203a5e07f09ab8f844c":{
      "scriptId":"u90"},
    "a2dc24c8c65c4fae95f16334163a8207":{
      "scriptId":"u91"},
    "280530c723194c2199d68b177c5d57d8":{
      "scriptId":"u92"},
    "4660a10c78464359a965352b468f9982":{
      "scriptId":"u93"},
    "ecb6ee8fb9de40ca858d3eba0572a053":{
      "scriptId":"u94"},
    "994e359488684c0682d5a4190ffbc2ab":{
      "scriptId":"u95"},
    "e3e9f5cb4e4042b5ac1c03391488a557":{
      "scriptId":"u96"},
    "cd1ef9e44cd2475aa091687164379c69":{
      "scriptId":"u97"},
    "a06223b2456d422382d2cb949a1c040f":{
      "scriptId":"u98"},
    "a79fbe9f87b545fe99fe6c5270b955fb":{
      "scriptId":"u99"},
    "b4a5fb8931f144bda99b87542fd0e295":{
      "scriptId":"u100"},
    "1f0426f914994af799ab688ec982f0ea":{
      "scriptId":"u101"},
    "3a0b284fa2aa4c70ae8d9472e1e585c6":{
      "scriptId":"u102"},
    "4ad2566974d740d69aaccd7c39e4e6bc":{
      "scriptId":"u103"},
    "b80268e05ead4648bf5af7df544da2a6":{
      "scriptId":"u104"},
    "bb6d4f5733f24bc3b71e673d8bdab881":{
      "scriptId":"u105"},
    "92fe2242e23746e9a7fd627b86056f0a":{
      "scriptId":"u106"},
    "7b03cc92b55c4c5d9bae1e33cc53cd57":{
      "scriptId":"u107"},
    "5346182218ae4c5780e21d414308fb56":{
      "scriptId":"u108"},
    "b85e3373663f4b6685e9afe14a5fe43f":{
      "scriptId":"u109"},
    "713640e8d2ca4cdd8786a4cf8bf21c51":{
      "scriptId":"u110"},
    "9088f6d977444c10babf5be3e7aa8ce5":{
      "scriptId":"u111"},
    "d5e9cf2ebdbf4a56b157f647099a31f8":{
      "scriptId":"u112"},
    "8c7c3e18dbdf46e68a69388000841474":{
      "scriptId":"u113"},
    "4b59c5777dc747e79ca743ee3c885c03":{
      "scriptId":"u114"},
    "1b11044954be410db7bbe111e5dbbf67":{
      "scriptId":"u115"},
    "5e620f70ef114b4d911a17cb4524dc10":{
      "scriptId":"u116"},
    "afe1cab3677a474e8b15fa7fcdd3996b":{
      "scriptId":"u117"},
    "6d7761e8ae5b47edbe8dba98d27f63d2":{
      "scriptId":"u118"},
    "cc45e18fe3404f4d8a65fbe822fed73b":{
      "scriptId":"u119"},
    "cbb777dcb53343d19b97153fc1213f1d":{
      "scriptId":"u120"},
    "e2bd85db076f429eb3e4c28adecf7b34":{
      "scriptId":"u121"},
    "9a60f57faa7b4cd983687de779981fb7":{
      "scriptId":"u122"},
    "8c1d209d48ba4de8bceab5194712faee":{
      "scriptId":"u123"},
    "c8851a69dc3e4421bd7d0d832a802aae":{
      "scriptId":"u124"},
    "a0de5ca89171496db986de35f64fea76":{
      "scriptId":"u125"},
    "bf0f40ab57ec45a58fe1b7a6a0c37004":{
      "scriptId":"u126"},
    "9baf60470f184141b0b5aa05b626ad2c":{
      "scriptId":"u127"},
    "1e4ea520491a401f90586bb81c40ac02":{
      "scriptId":"u128"}}});