$axure.loadCurrentPage({
  "url":"新增职员.html",
  "generationDate":new Date(1446432605585.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04e3114be6ac45b4af21fdc03ce69e07",
    "type":"Axure:Page",
    "name":"新增职员",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0c17e90e18a6480c8453da09302707b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":252}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"758f14d467624930b5dbf31150abdd9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":252}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u0.png"}},
{
          "id":"cf6912cfd8834057b1a5e713206901d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7565bd5fd12434dbdbf75a7d14feff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u2.png"}},
{
          "id":"32dc233fa53b40c189877d45718fef16",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":385,
              "y":56},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5200d309997f4815824912c864b4af46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":385,
                  "y":56},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"968584fe47084243a0c55e59ddc4da19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":728,
              "y":53},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67b6623c28314f9e826908185e580365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":728,
                  "y":53},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc074daba4924baf9c5f7afe30592fb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":270},
            "size":{
              "width":360,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46106d1bd1b441f1828888b5163d276b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":270},
                "size":{
                  "width":360,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u8.png"}},
{
          "id":"77cd69524cc5450e8d9024c033c3c78e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":630,
              "y":274},
            "size":{
              "width":52,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7e46f33fc574f1fb911a697449299d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":630,
                  "y":274},
                "size":{
                  "width":52,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u10.png"}},
{
          "id":"b623d9b2ae294ce9929960ba7cf4ce07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":692,
              "y":274},
            "size":{
              "width":38,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"280040d110d7446995dbf8ce1c33403b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":692,
                  "y":274},
                "size":{
                  "width":38,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u12.png"}},
{
          "id":"12445a6f45ae44cfb6da077d062b9532",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":112},
            "size":{
              "width":76,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b59cd93789744ed8a17a370f87a5ab30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":112},
                "size":{
                  "width":76,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d24525d37bf476eb6a126da64d965f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":107},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598d1a5ab92f47f6a0c82c726568f524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":107},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"1038cc031c854c33b27cd3628633c1ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":170},
            "size":{
              "width":76,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe1c5332ff7d4500ab02e7d3ee4d3111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":170},
                "size":{
                  "width":76,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2e2f6ad8711473d82f620c006cbbcad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":165},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947bf6aafa4345efb73e81fdbd795855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":165},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0c17e90e18a6480c8453da09302707b4":{
      "scriptId":"u0"},
    "758f14d467624930b5dbf31150abdd9b":{
      "scriptId":"u1"},
    "cf6912cfd8834057b1a5e713206901d0":{
      "scriptId":"u2"},
    "d7565bd5fd12434dbdbf75a7d14feff7":{
      "scriptId":"u3"},
    "32dc233fa53b40c189877d45718fef16":{
      "scriptId":"u4"},
    "5200d309997f4815824912c864b4af46":{
      "scriptId":"u5"},
    "968584fe47084243a0c55e59ddc4da19":{
      "scriptId":"u6"},
    "67b6623c28314f9e826908185e580365":{
      "scriptId":"u7"},
    "cc074daba4924baf9c5f7afe30592fb6":{
      "scriptId":"u8"},
    "46106d1bd1b441f1828888b5163d276b":{
      "scriptId":"u9"},
    "77cd69524cc5450e8d9024c033c3c78e":{
      "scriptId":"u10"},
    "a7e46f33fc574f1fb911a697449299d9":{
      "scriptId":"u11"},
    "b623d9b2ae294ce9929960ba7cf4ce07":{
      "scriptId":"u12"},
    "280040d110d7446995dbf8ce1c33403b":{
      "scriptId":"u13"},
    "12445a6f45ae44cfb6da077d062b9532":{
      "scriptId":"u14"},
    "b59cd93789744ed8a17a370f87a5ab30":{
      "scriptId":"u15"},
    "0d24525d37bf476eb6a126da64d965f6":{
      "scriptId":"u16"},
    "598d1a5ab92f47f6a0c82c726568f524":{
      "scriptId":"u17"},
    "1038cc031c854c33b27cd3628633c1ab":{
      "scriptId":"u18"},
    "fe1c5332ff7d4500ab02e7d3ee4d3111":{
      "scriptId":"u19"},
    "d2e2f6ad8711473d82f620c006cbbcad":{
      "scriptId":"u20"},
    "947bf6aafa4345efb73e81fdbd795855":{
      "scriptId":"u21"}}});