$axure.loadCurrentPage({
  "url":"商品管理.html",
  "generationDate":new Date(1446432603966.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"60585f4ab64c48418bc4a380bf37545e",
    "type":"Axure:Page",
    "name":"商品管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f10c7e7f6d74f4d93d1cb3630e496da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c95be44048d4856a742e0e19553acb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"dd1ec68bdab344ce8becce4da8670f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"652ab54b16b94c9fafc7fb651403dacb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b24471cd9532448f8a2c71194a10f954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb76dfc49fc747d79ea35b364ec1a5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"4af3a88e7f5c4634aa9cdb0399214ea2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"d658ae6d71bb4b4684ef94e1c559ae8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"788f8867efe748d38f2c8bbf7a21bae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1402039507f94959beed69e755637988",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"3b9064f86aa14cfcab370000e9f216f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3882c144edd0417e859558988055627d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1a015674c84e00a75ec94a3de2a9ec",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"e94b1a23f2e340f1a46a3ca9f04a1171",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"663512e12f5c41158133c291dbc99db7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31263ae62b9a443a84257f7301aa7bc1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"ee3a38de195a48369dcd4b7c635f647d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2625c1793d754b1f9f263c3d61136159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0771c9259ad349be91313b51b4c90b09",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"2fdc4662460942a880e0b11b3491811c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26496fa002244d6993568e3c37b5f98c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"ed25fb9d7bc54bc5be7384943249ca2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54ff0eb0a93491fabd7af444fac6c08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22f955fb8cfc45b690643c6ce4bb5551",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198088769c6f4ea4ac745120dbb3a2f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"1068a167b3d94e37ad504f82bd8aa8c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3abd3d35f0cd467f803f72d9dc500743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5c451659a5c4b538955fa9c59dbd123",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b03fa5fb26e84085bc5ca3aebd3f4d2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fa6b57bc1f8466b85d32b2ca557508b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"883b254d824c44b293262551682b5d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"22c2db603bf24f2b96ebbe0a1ee35d7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"effc1ba224b94a0f80e80f906419b3f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae34cbc6856e417e97e573d20c4dd830",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b7f112d8424c5fb8d023884e47f8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"6edfeb8cad884bd2ace1bc603ce90f2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276c4e822a0641068ad5af910616c6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"c5ac2e0004764b4c9d60b0244ca2c81d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8cba36be9f41faac2d2e583ab9f57b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"1991fcfdd14c40358fdcb4180f095e2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"082e1720c4a74b35a441b81cd0d959f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"645063b920b24955b379c9090b636429",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a88182790afe4663be565eefce07ea5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"623f46599b6140739b956f54d547007e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d07df3be7db04ee9ae846dd80e8c5051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"b87c21b267c649ce8cba55b04d065f5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"340d87684ddf4e9dbad968d7a020144a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39e14f43beb0400096acd187eb679356",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32f056ec7abc4a869b357d3ef8b14a4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30b6597b0eb648ce88bb3d605fa75bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6615330d0a42f7adbdae01a9c81414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85d3d6c79b364d2eb9017e9aeddf197e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ed80dad4457414cb2ed0b64194fd6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f575d11420a641de82923a7e899a268e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a4686f426b4852952384d1c98f369c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f445b987e7c414d9d882d59445fbfec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b28bfea9fab243ccb28562fd06969900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e09bf9b60713428ca2e561e2f1f98e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"560140e34dae404ea48b71a6755f51cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b60c677b8150420a853f72b527f0d639",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f21f323baa54a29a30c8e15cdbb7b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"24b186c089664ec7bde9bebe03f0bf5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b023467dfb9e4d91aeada446f3631327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"0ca3255160d140adbe1ea20dde9d2b71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b015c66178984d518800ba041d95ce61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"c1ae1f119a25495c843bf0eb6b35304e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a4eb6cab73473d9e5ae1285ec13c69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"5b6ffbd4cc8f42e3a522cb4d38000d59",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":352,
              "y":133},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"027a949d22ff4810b3678aa41b2bf13c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":352,
                  "y":133},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeef18308c9e48c8a7fe83fac20cdde5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":263},
            "size":{
              "width":1766,
              "height":688}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc784578af1a48aba68a1d4b32bba6ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":263},
                "size":{
                  "width":1766,
                  "height":688}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u69.png"}},
{
          "id":"4e2e6e2d50e44dafaf19366dbcd458ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36a146c16ad4066bd58df3fa397d8ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eedf6c1cec294e588b27d0a750e3c50c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":240,
              "y":225},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72ec10ea88f24a05b00538594100ff3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":240,
                  "y":225},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u75.png"}},
{
          "id":"cf74d548620d4a6f89b43ea2dddae605",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":247,
              "y":232},
            "size":{
              "width":88,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c297322754e413d93b2863256b56f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":247,
                  "y":232},
                "size":{
                  "width":88,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea8ac67a286f47a098af3d05565e4841",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":240,
              "y":263},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69e7898ab1a8470f903703f02d2c83ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":240,
                  "y":263},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品管理/u77.png"}},
{
          "id":"ae522df099104296920a2e1c36c08704",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"475e6a72904c4dd8bac9af7af66c013d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":536,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"def17dbc691648078742b1a53b1d0a5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":284,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b305277325cc4fecb27243eac849ab9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":284,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9354469c67e4504916b4e170cd58a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1323,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b0998499ad43efaaf259c5410122d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1323,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"8b16ba4575b24218a102ae5285d44a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1439,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97955b9ef5e54c129637463fab5579f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1439,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"703719cd59ce48c395103eb2b8a67f48",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":265},
            "size":{
              "width":10,
              "height":685}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u87_line.png"}},
{
          "id":"50dd451b46b944cbb9b95724e3e5efb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":427,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef3da15ec0af41689cc7e519fd9a7aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":427,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"772b93102ea342b58a9b8e58db9eb047",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"79dacad862a54fef9e75c9ebe9409bcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":604,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4ae61f264054b98827ac09ef24f9532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":604,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"247f692e6f2a4c49a5b85de4a93bd6a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":783,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a113d500374899b342f27a396e57a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":783,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a48b3ca87b6e437086c50367b717a5c7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"0a783985116b4caea6a5320acc9bc639",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"36c90a5be980408cbbb716e848a8ceb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":906,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfcc599df8ec48ea95db3072b1e13592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":906,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c82148ec6b4741c99b4a48be4d742451",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":980,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"769e880fcb0c4e37b72631b014dc8d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":980,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8169c9eb4fa64d8a9930a2288c357712",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1088,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb219d4f6c2a486798b4292104cd0f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1088,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34466d7da2cb4093acb85e359b88792a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1203,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c021fad581f4f38b24125e153dd9428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1203,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f695c0a69644190ade4d2cea4ba98be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1310,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423c41d2422c4a488c6edf95703e42e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1310,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04db83da774347cd8f87618467cec59a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1433,
              "y":270},
            "size":{
              "width":111,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a93c242114e457f8ad9350e314611fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1433,
                  "y":270},
                "size":{
                  "width":111,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af8b3bbed80749689e5c3569b141ef9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1567,
              "y":270},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aa1be4f59744eaaaeef2bbe6065fcc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1567,
                  "y":270},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22c8c0c4f0e1481989d70fa5ad7ae281",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1684,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63766c439a044d47bbb6df3b0389dfd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1684,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b61aedcfc7d464eb8c0eb94410b0c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1803,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5fbb803e08f42da8c166b3881b485d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1803,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afac69a066774fd99fc81f510662565d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1918,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e33b713c11484e5498b9e0b7707bcf2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1918,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e92b5375a64548d19f2159ffb63e3757",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1072,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"3e5774b3a76b420fa1ec02d8c048045e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1181,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"6591e05621364486b4f9fb738ee1de1c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1292,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"6b821e5f637540449a048830fa13b150",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1410,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"3158da91795743918bbf1f22199f7a03",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1541,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"c1ba68f0f5fb42759d502df1782a600c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1643,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"7bba0469aaa843deb91473acf113f104",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1773,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"0beade9919b3439a9a213dcc19972b6a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"41d54faf679a4af4982a9f9a1cc0fe1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":330},
            "size":{
              "width":1760,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u125_line.png"}},
{
          "id":"200d8ce206e549bd9a5d8ea5d554aab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":1792,
              "y":306},
            "size":{
              "width":72,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"525ebe1c66284957889a7f433dd5f675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":1792,
                  "y":306},
                "size":{
                  "width":72,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u98.png"}},
{
          "id":"f4f394e2ec3c447bb55b66fa0bc72029",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1953.5,
              "y":306},
            "size":{
              "width":19,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2915291b63aa4652a10162d1e0ff2759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1953.5,
                  "y":306},
                "size":{
                  "width":19,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"12bb2cc6b1b94e7a9c3f1d9eeb7dbb54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1908.5,
              "y":310},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27056b6f8a90414bb98c4fa722249f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1908.5,
                  "y":310},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u96.png"}},
{
          "id":"98fb9266268f44ebbbdc347ec21e8966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1556,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5490328b2c444c328289a7f5634f6b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1556,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"eee5706c1a8b4c2994128364ec05eba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1670,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da236c9cf684f5c816afcce29f5dee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1670,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"32aaef4694e2498292220af62b02c5c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1788,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aba66566223e46a6919b236e2bf44f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1788,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"79170a987b564c26a9e9062fb7539e64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1910,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c21460988c4d89af134040f09c1b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1910,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"666085d02c6143fbb8ef228a0fb1cfdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":310},
            "size":{
              "width":13,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba0f5d6a2b7b4521bb27a903341e54f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":310},
                "size":{
                  "width":13,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品管理/u140.png"}},
{
          "id":"198a8d33ecb84abb82678cdd160e7cbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":278},
            "size":{
              "width":13,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a211f0b6e4d94dbd969c5c80c897bb66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":278},
                "size":{
                  "width":13,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品管理/u140.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f10c7e7f6d74f4d93d1cb3630e496da":{
      "scriptId":"u0"},
    "1c95be44048d4856a742e0e19553acb5":{
      "scriptId":"u1"},
    "dd1ec68bdab344ce8becce4da8670f48":{
      "scriptId":"u2"},
    "652ab54b16b94c9fafc7fb651403dacb":{
      "scriptId":"u3"},
    "b24471cd9532448f8a2c71194a10f954":{
      "scriptId":"u4"},
    "fb76dfc49fc747d79ea35b364ec1a5c0":{
      "scriptId":"u5"},
    "4af3a88e7f5c4634aa9cdb0399214ea2":{
      "scriptId":"u6"},
    "d658ae6d71bb4b4684ef94e1c559ae8e":{
      "scriptId":"u7"},
    "788f8867efe748d38f2c8bbf7a21bae0":{
      "scriptId":"u8"},
    "1402039507f94959beed69e755637988":{
      "scriptId":"u9"},
    "3b9064f86aa14cfcab370000e9f216f7":{
      "scriptId":"u10"},
    "3882c144edd0417e859558988055627d":{
      "scriptId":"u11"},
    "3e1a015674c84e00a75ec94a3de2a9ec":{
      "scriptId":"u12"},
    "e94b1a23f2e340f1a46a3ca9f04a1171":{
      "scriptId":"u13"},
    "663512e12f5c41158133c291dbc99db7":{
      "scriptId":"u14"},
    "31263ae62b9a443a84257f7301aa7bc1":{
      "scriptId":"u15"},
    "ee3a38de195a48369dcd4b7c635f647d":{
      "scriptId":"u16"},
    "2625c1793d754b1f9f263c3d61136159":{
      "scriptId":"u17"},
    "0771c9259ad349be91313b51b4c90b09":{
      "scriptId":"u18"},
    "2fdc4662460942a880e0b11b3491811c":{
      "scriptId":"u19"},
    "26496fa002244d6993568e3c37b5f98c":{
      "scriptId":"u20"},
    "ed25fb9d7bc54bc5be7384943249ca2e":{
      "scriptId":"u21"},
    "c54ff0eb0a93491fabd7af444fac6c08":{
      "scriptId":"u22"},
    "22f955fb8cfc45b690643c6ce4bb5551":{
      "scriptId":"u23"},
    "198088769c6f4ea4ac745120dbb3a2f5":{
      "scriptId":"u24"},
    "1068a167b3d94e37ad504f82bd8aa8c1":{
      "scriptId":"u25"},
    "3abd3d35f0cd467f803f72d9dc500743":{
      "scriptId":"u26"},
    "f5c451659a5c4b538955fa9c59dbd123":{
      "scriptId":"u27"},
    "b03fa5fb26e84085bc5ca3aebd3f4d2b":{
      "scriptId":"u28"},
    "0fa6b57bc1f8466b85d32b2ca557508b":{
      "scriptId":"u29"},
    "883b254d824c44b293262551682b5d98":{
      "scriptId":"u30"},
    "22c2db603bf24f2b96ebbe0a1ee35d7d":{
      "scriptId":"u31"},
    "effc1ba224b94a0f80e80f906419b3f3":{
      "scriptId":"u32"},
    "ae34cbc6856e417e97e573d20c4dd830":{
      "scriptId":"u33"},
    "48b7f112d8424c5fb8d023884e47f8c4":{
      "scriptId":"u34"},
    "6edfeb8cad884bd2ace1bc603ce90f2a":{
      "scriptId":"u35"},
    "276c4e822a0641068ad5af910616c6b3":{
      "scriptId":"u36"},
    "c5ac2e0004764b4c9d60b0244ca2c81d":{
      "scriptId":"u37"},
    "ba8cba36be9f41faac2d2e583ab9f57b":{
      "scriptId":"u38"},
    "1991fcfdd14c40358fdcb4180f095e2a":{
      "scriptId":"u39"},
    "082e1720c4a74b35a441b81cd0d959f2":{
      "scriptId":"u40"},
    "645063b920b24955b379c9090b636429":{
      "scriptId":"u41"},
    "a88182790afe4663be565eefce07ea5e":{
      "scriptId":"u42"},
    "623f46599b6140739b956f54d547007e":{
      "scriptId":"u43"},
    "d07df3be7db04ee9ae846dd80e8c5051":{
      "scriptId":"u44"},
    "b87c21b267c649ce8cba55b04d065f5c":{
      "scriptId":"u45"},
    "340d87684ddf4e9dbad968d7a020144a":{
      "scriptId":"u46"},
    "39e14f43beb0400096acd187eb679356":{
      "scriptId":"u47"},
    "32f056ec7abc4a869b357d3ef8b14a4e":{
      "scriptId":"u48"},
    "30b6597b0eb648ce88bb3d605fa75bb4":{
      "scriptId":"u49"},
    "cf6615330d0a42f7adbdae01a9c81414":{
      "scriptId":"u50"},
    "85d3d6c79b364d2eb9017e9aeddf197e":{
      "scriptId":"u51"},
    "0ed80dad4457414cb2ed0b64194fd6ae":{
      "scriptId":"u52"},
    "f575d11420a641de82923a7e899a268e":{
      "scriptId":"u53"},
    "60a4686f426b4852952384d1c98f369c":{
      "scriptId":"u54"},
    "4f445b987e7c414d9d882d59445fbfec":{
      "scriptId":"u55"},
    "b28bfea9fab243ccb28562fd06969900":{
      "scriptId":"u56"},
    "e09bf9b60713428ca2e561e2f1f98e82":{
      "scriptId":"u57"},
    "560140e34dae404ea48b71a6755f51cf":{
      "scriptId":"u58"},
    "b60c677b8150420a853f72b527f0d639":{
      "scriptId":"u59"},
    "9f21f323baa54a29a30c8e15cdbb7b04":{
      "scriptId":"u60"},
    "24b186c089664ec7bde9bebe03f0bf5c":{
      "scriptId":"u61"},
    "b023467dfb9e4d91aeada446f3631327":{
      "scriptId":"u62"},
    "0ca3255160d140adbe1ea20dde9d2b71":{
      "scriptId":"u63"},
    "b015c66178984d518800ba041d95ce61":{
      "scriptId":"u64"},
    "c1ae1f119a25495c843bf0eb6b35304e":{
      "scriptId":"u65"},
    "17a4eb6cab73473d9e5ae1285ec13c69":{
      "scriptId":"u66"},
    "5b6ffbd4cc8f42e3a522cb4d38000d59":{
      "scriptId":"u67"},
    "027a949d22ff4810b3678aa41b2bf13c":{
      "scriptId":"u68"},
    "aeef18308c9e48c8a7fe83fac20cdde5":{
      "scriptId":"u69"},
    "bc784578af1a48aba68a1d4b32bba6ed":{
      "scriptId":"u70"},
    "4e2e6e2d50e44dafaf19366dbcd458ec":{
      "scriptId":"u71"},
    "d36a146c16ad4066bd58df3fa397d8ca":{
      "scriptId":"u72"},
    "eedf6c1cec294e588b27d0a750e3c50c":{
      "scriptId":"u73"},
    "72ec10ea88f24a05b00538594100ff3b":{
      "scriptId":"u74"},
    "cf74d548620d4a6f89b43ea2dddae605":{
      "scriptId":"u75"},
    "4c297322754e413d93b2863256b56f7d":{
      "scriptId":"u76"},
    "ea8ac67a286f47a098af3d05565e4841":{
      "scriptId":"u77"},
    "69e7898ab1a8470f903703f02d2c83ab":{
      "scriptId":"u78"},
    "ae522df099104296920a2e1c36c08704":{
      "scriptId":"u79"},
    "475e6a72904c4dd8bac9af7af66c013d":{
      "scriptId":"u80"},
    "def17dbc691648078742b1a53b1d0a5d":{
      "scriptId":"u81"},
    "b305277325cc4fecb27243eac849ab9f":{
      "scriptId":"u82"},
    "a9354469c67e4504916b4e170cd58a13":{
      "scriptId":"u83"},
    "d5b0998499ad43efaaf259c5410122d4":{
      "scriptId":"u84"},
    "8b16ba4575b24218a102ae5285d44a57":{
      "scriptId":"u85"},
    "97955b9ef5e54c129637463fab5579f0":{
      "scriptId":"u86"},
    "703719cd59ce48c395103eb2b8a67f48":{
      "scriptId":"u87"},
    "50dd451b46b944cbb9b95724e3e5efb8":{
      "scriptId":"u88"},
    "ef3da15ec0af41689cc7e519fd9a7aa6":{
      "scriptId":"u89"},
    "772b93102ea342b58a9b8e58db9eb047":{
      "scriptId":"u90"},
    "79dacad862a54fef9e75c9ebe9409bcf":{
      "scriptId":"u91"},
    "f4ae61f264054b98827ac09ef24f9532":{
      "scriptId":"u92"},
    "247f692e6f2a4c49a5b85de4a93bd6a7":{
      "scriptId":"u93"},
    "a6a113d500374899b342f27a396e57a5":{
      "scriptId":"u94"},
    "a48b3ca87b6e437086c50367b717a5c7":{
      "scriptId":"u95"},
    "0a783985116b4caea6a5320acc9bc639":{
      "scriptId":"u96"},
    "36c90a5be980408cbbb716e848a8ceb9":{
      "scriptId":"u97"},
    "cfcc599df8ec48ea95db3072b1e13592":{
      "scriptId":"u98"},
    "c82148ec6b4741c99b4a48be4d742451":{
      "scriptId":"u99"},
    "769e880fcb0c4e37b72631b014dc8d10":{
      "scriptId":"u100"},
    "8169c9eb4fa64d8a9930a2288c357712":{
      "scriptId":"u101"},
    "bb219d4f6c2a486798b4292104cd0f11":{
      "scriptId":"u102"},
    "34466d7da2cb4093acb85e359b88792a":{
      "scriptId":"u103"},
    "1c021fad581f4f38b24125e153dd9428":{
      "scriptId":"u104"},
    "0f695c0a69644190ade4d2cea4ba98be":{
      "scriptId":"u105"},
    "423c41d2422c4a488c6edf95703e42e3":{
      "scriptId":"u106"},
    "04db83da774347cd8f87618467cec59a":{
      "scriptId":"u107"},
    "1a93c242114e457f8ad9350e314611fd":{
      "scriptId":"u108"},
    "af8b3bbed80749689e5c3569b141ef9e":{
      "scriptId":"u109"},
    "6aa1be4f59744eaaaeef2bbe6065fcc0":{
      "scriptId":"u110"},
    "22c8c0c4f0e1481989d70fa5ad7ae281":{
      "scriptId":"u111"},
    "63766c439a044d47bbb6df3b0389dfd9":{
      "scriptId":"u112"},
    "7b61aedcfc7d464eb8c0eb94410b0c52":{
      "scriptId":"u113"},
    "e5fbb803e08f42da8c166b3881b485d1":{
      "scriptId":"u114"},
    "afac69a066774fd99fc81f510662565d":{
      "scriptId":"u115"},
    "e33b713c11484e5498b9e0b7707bcf2a":{
      "scriptId":"u116"},
    "e92b5375a64548d19f2159ffb63e3757":{
      "scriptId":"u117"},
    "3e5774b3a76b420fa1ec02d8c048045e":{
      "scriptId":"u118"},
    "6591e05621364486b4f9fb738ee1de1c":{
      "scriptId":"u119"},
    "6b821e5f637540449a048830fa13b150":{
      "scriptId":"u120"},
    "3158da91795743918bbf1f22199f7a03":{
      "scriptId":"u121"},
    "c1ba68f0f5fb42759d502df1782a600c":{
      "scriptId":"u122"},
    "7bba0469aaa843deb91473acf113f104":{
      "scriptId":"u123"},
    "0beade9919b3439a9a213dcc19972b6a":{
      "scriptId":"u124"},
    "41d54faf679a4af4982a9f9a1cc0fe1c":{
      "scriptId":"u125"},
    "200d8ce206e549bd9a5d8ea5d554aab9":{
      "scriptId":"u126"},
    "525ebe1c66284957889a7f433dd5f675":{
      "scriptId":"u127"},
    "f4f394e2ec3c447bb55b66fa0bc72029":{
      "scriptId":"u128"},
    "2915291b63aa4652a10162d1e0ff2759":{
      "scriptId":"u129"},
    "12bb2cc6b1b94e7a9c3f1d9eeb7dbb54":{
      "scriptId":"u130"},
    "27056b6f8a90414bb98c4fa722249f81":{
      "scriptId":"u131"},
    "98fb9266268f44ebbbdc347ec21e8966":{
      "scriptId":"u132"},
    "5490328b2c444c328289a7f5634f6b17":{
      "scriptId":"u133"},
    "eee5706c1a8b4c2994128364ec05eba8":{
      "scriptId":"u134"},
    "8da236c9cf684f5c816afcce29f5dee3":{
      "scriptId":"u135"},
    "32aaef4694e2498292220af62b02c5c3":{
      "scriptId":"u136"},
    "aba66566223e46a6919b236e2bf44f1e":{
      "scriptId":"u137"},
    "79170a987b564c26a9e9062fb7539e64":{
      "scriptId":"u138"},
    "54c21460988c4d89af134040f09c1b78":{
      "scriptId":"u139"},
    "666085d02c6143fbb8ef228a0fb1cfdd":{
      "scriptId":"u140"},
    "ba0f5d6a2b7b4521bb27a903341e54f3":{
      "scriptId":"u141"},
    "198a8d33ecb84abb82678cdd160e7cbf":{
      "scriptId":"u142"},
    "a211f0b6e4d94dbd969c5c80c897bb66":{
      "scriptId":"u143"}}});