$axure.loadCurrentPage({
  "url":"初期设置.html",
  "generationDate":new Date(1446432604230.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"df1eec2574784a41bab5338f9ee64c23",
    "type":"Axure:Page",
    "name":"初期设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5b6440e8da843eda4e2efe87228d026",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":786,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0729e2a316fa4ddfb0a95a1b52cd510a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":786,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u0.png"}},
{
          "id":"261204f5910c466b83eb6e0e02912c70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0863457183254eadb45f3680e1c91d49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"4e0d9babff4b4704a6552806a4698c3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":404,
              "y":78},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5834f5174b2e4e61b21c2a1a90489aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":404,
                  "y":78},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fe83b11b81942e3b9d507d7425bcada",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":1154,
              "y":76},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80bf46eeb1454510a341ab2f941ff914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":1154,
                  "y":76},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3761e7481a94d64872bb3bd64932f11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":109},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84c72a2e3e44d7fa5c2622b84294ebe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":109},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u12.png"}},
{
          "id":"9cadbf22621c40cd8cb35dcf716053d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":409,
              "y":112},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"079cb3ba21e64dcaafe09d08419afc19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":409,
                  "y":112},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63155f64c7a84c9abd92f218c30a2c36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":109},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b49b49ec9fa4c879d2c0d5e3c70523c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":109},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u12.png"}},
{
          "id":"1ee970a619fc43a3a2d262e342e87c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":623,
              "y":109},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d50ce565d14d898b0ecd6e54a98e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":623,
                  "y":109},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u12.png"}},
{
          "id":"0476ca80dab7404bb9194fcd47a0d2d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":529,
              "y":112},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0254cfe2ae144125973e037c66d78db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":529,
                  "y":112},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ba6ff7b67d74e9fa612a8e223b48723",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":643,
              "y":112},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beed0f1170984a15b2ce9e676092576c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":643,
                  "y":112},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8648fde6ade4ea2bf9de192134da005",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":580},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"811db67c03bc46bf95916294c6e4db5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":580},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"0f8c50b2662f42c88a4f46fcd1b7af36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":995,
              "y":585},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2648befb4ffb4be1aca1bdb4af825276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":995,
                  "y":585},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u71.png"}},
{
          "id":"a5d304678d2441b88b75d8d90723de24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1081,
              "y":585},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b22ab17bc3324e6497589309db4ec38b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1081,
                  "y":585},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u73.png"}},
{
          "id":"d13e31e2ff194d569153b02eaa5a0be1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":736,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e842a66133c9437bb642c35569a03216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":736,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/初期设置/u26.png"}},
{
          "id":"7919bd1442244bc38cb2a0ceb3625669",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":420,
              "y":150},
            "size":{
              "width":30,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd21d849f4b4876bc50c4a78bf402ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":420,
                  "y":150},
                "size":{
                  "width":30,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/初期设置/u28.png"}},
{
          "id":"c2771f3f8b014fe5993583eab964a5f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":174},
            "size":{
              "width":29,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u30_line.png"}},
{
          "id":"f8ca5f781c7e49bf992efc04ae5f9e50",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":150},
            "size":{
              "width":10,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u31_line.png"}},
{
          "id":"3e2d63cb1bff4cf1816ecc2bcebfbba8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":481,
              "y":155},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12ac4a812ded4661a632c0e66266be15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":481,
                  "y":155},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3854197f3c0b4ff2a662e7024a7df4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":578,
              "y":155},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc596e8de032466ea436e0c97b2a26c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":578,
                  "y":155},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59c0fe18708244d592d1aee1a0010bbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":680,
              "y":155},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04d2f2dad483446089f6351c1b91feaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":680,
                  "y":155},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f5ea97db9154019be27c886e22d4925",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":788,
              "y":155},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243d677c559d48f9b4c4142aae72d16b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":788,
                  "y":155},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fca8c6112e345a9af2d201ec240fbb2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":150},
            "size":{
              "width":10,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u31_line.png"}},
{
          "id":"47aa539e137b4e52a0e7318afad690ce",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":755,
              "y":150},
            "size":{
              "width":10,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u31_line.png"}},
{
          "id":"4a674d3290574802a6a2f03fdee061f5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":150},
            "size":{
              "width":10,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u31_line.png"}},
{
          "id":"3f20f755332642a6848b1aa69f7c042e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":150},
            "size":{
              "width":10,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u31_line.png"}},
{
          "id":"bff0a40153e24adf87c6e5dfb7ee6d09",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":202},
            "size":{
              "width":505,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u44_line.png"}},
{
          "id":"fc234d5bbde642978a86d338aa8fd967",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":233},
            "size":{
              "width":735,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u45_line.png"}},
{
          "id":"497bb57304534cb092fc470e9f8f30ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":901,
              "y":186},
            "size":{
              "width":11,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195ce37cfb3f489aa404eb61fb416f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":901,
                  "y":186},
                "size":{
                  "width":11,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"a608aa7a861c41ce80610020aa4ebb8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":901,
              "y":216},
            "size":{
              "width":11,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a00647887b140309a8f49e7adcef4ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":901,
                  "y":216},
                "size":{
                  "width":11,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"ffefc624d82441a2937bc79dbb2b5701",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":882,
              "y":181},
            "size":{
              "width":13,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36208823c3f14179a2c90889d2595f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":882,
                  "y":181},
                "size":{
                  "width":13,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4e6c0b29ccc4f3a80c62fc47a66eec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":882,
              "y":212},
            "size":{
              "width":13,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7562c8317df4c4dad1cd96029a40803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":882,
                  "y":212},
                "size":{
                  "width":13,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d1c41c0c50c4f01a1fb1c20d022befb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":181},
            "size":{
              "width":12,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27fbbf4780c045de82617f7770918558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":181},
                "size":{
                  "width":12,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eded0950a9b426f808a47ebdd300ca3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":212},
            "size":{
              "width":12,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aab3bc0be514678867f804ccacd1fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":212},
                "size":{
                  "width":12,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06f25f54b055471bb49f313f78e72c2b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1149.75,
              "y":150},
            "size":{
              "width":10,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/初期设置/u31_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b5b6440e8da843eda4e2efe87228d026":{
      "scriptId":"u0"},
    "0729e2a316fa4ddfb0a95a1b52cd510a":{
      "scriptId":"u1"},
    "261204f5910c466b83eb6e0e02912c70":{
      "scriptId":"u2"},
    "0863457183254eadb45f3680e1c91d49":{
      "scriptId":"u3"},
    "4e0d9babff4b4704a6552806a4698c3d":{
      "scriptId":"u4"},
    "5834f5174b2e4e61b21c2a1a90489aeb":{
      "scriptId":"u5"},
    "7fe83b11b81942e3b9d507d7425bcada":{
      "scriptId":"u6"},
    "80bf46eeb1454510a341ab2f941ff914":{
      "scriptId":"u7"},
    "a3761e7481a94d64872bb3bd64932f11":{
      "scriptId":"u8"},
    "c84c72a2e3e44d7fa5c2622b84294ebe":{
      "scriptId":"u9"},
    "9cadbf22621c40cd8cb35dcf716053d8":{
      "scriptId":"u10"},
    "079cb3ba21e64dcaafe09d08419afc19":{
      "scriptId":"u11"},
    "63155f64c7a84c9abd92f218c30a2c36":{
      "scriptId":"u12"},
    "5b49b49ec9fa4c879d2c0d5e3c70523c":{
      "scriptId":"u13"},
    "1ee970a619fc43a3a2d262e342e87c24":{
      "scriptId":"u14"},
    "50d50ce565d14d898b0ecd6e54a98e2a":{
      "scriptId":"u15"},
    "0476ca80dab7404bb9194fcd47a0d2d1":{
      "scriptId":"u16"},
    "0254cfe2ae144125973e037c66d78db8":{
      "scriptId":"u17"},
    "6ba6ff7b67d74e9fa612a8e223b48723":{
      "scriptId":"u18"},
    "beed0f1170984a15b2ce9e676092576c":{
      "scriptId":"u19"},
    "d8648fde6ade4ea2bf9de192134da005":{
      "scriptId":"u20"},
    "811db67c03bc46bf95916294c6e4db5e":{
      "scriptId":"u21"},
    "0f8c50b2662f42c88a4f46fcd1b7af36":{
      "scriptId":"u22"},
    "2648befb4ffb4be1aca1bdb4af825276":{
      "scriptId":"u23"},
    "a5d304678d2441b88b75d8d90723de24":{
      "scriptId":"u24"},
    "b22ab17bc3324e6497589309db4ec38b":{
      "scriptId":"u25"},
    "d13e31e2ff194d569153b02eaa5a0be1":{
      "scriptId":"u26"},
    "e842a66133c9437bb642c35569a03216":{
      "scriptId":"u27"},
    "7919bd1442244bc38cb2a0ceb3625669":{
      "scriptId":"u28"},
    "5bd21d849f4b4876bc50c4a78bf402ce":{
      "scriptId":"u29"},
    "c2771f3f8b014fe5993583eab964a5f1":{
      "scriptId":"u30"},
    "f8ca5f781c7e49bf992efc04ae5f9e50":{
      "scriptId":"u31"},
    "3e2d63cb1bff4cf1816ecc2bcebfbba8":{
      "scriptId":"u32"},
    "12ac4a812ded4661a632c0e66266be15":{
      "scriptId":"u33"},
    "3854197f3c0b4ff2a662e7024a7df4dc":{
      "scriptId":"u34"},
    "cc596e8de032466ea436e0c97b2a26c2":{
      "scriptId":"u35"},
    "59c0fe18708244d592d1aee1a0010bbd":{
      "scriptId":"u36"},
    "04d2f2dad483446089f6351c1b91feaf":{
      "scriptId":"u37"},
    "9f5ea97db9154019be27c886e22d4925":{
      "scriptId":"u38"},
    "243d677c559d48f9b4c4142aae72d16b":{
      "scriptId":"u39"},
    "5fca8c6112e345a9af2d201ec240fbb2":{
      "scriptId":"u40"},
    "47aa539e137b4e52a0e7318afad690ce":{
      "scriptId":"u41"},
    "4a674d3290574802a6a2f03fdee061f5":{
      "scriptId":"u42"},
    "3f20f755332642a6848b1aa69f7c042e":{
      "scriptId":"u43"},
    "bff0a40153e24adf87c6e5dfb7ee6d09":{
      "scriptId":"u44"},
    "fc234d5bbde642978a86d338aa8fd967":{
      "scriptId":"u45"},
    "497bb57304534cb092fc470e9f8f30ab":{
      "scriptId":"u46"},
    "195ce37cfb3f489aa404eb61fb416f45":{
      "scriptId":"u47"},
    "a608aa7a861c41ce80610020aa4ebb8d":{
      "scriptId":"u48"},
    "6a00647887b140309a8f49e7adcef4ac":{
      "scriptId":"u49"},
    "ffefc624d82441a2937bc79dbb2b5701":{
      "scriptId":"u50"},
    "36208823c3f14179a2c90889d2595f78":{
      "scriptId":"u51"},
    "a4e6c0b29ccc4f3a80c62fc47a66eec4":{
      "scriptId":"u52"},
    "b7562c8317df4c4dad1cd96029a40803":{
      "scriptId":"u53"},
    "0d1c41c0c50c4f01a1fb1c20d022befb":{
      "scriptId":"u54"},
    "27fbbf4780c045de82617f7770918558":{
      "scriptId":"u55"},
    "1eded0950a9b426f808a47ebdd300ca3":{
      "scriptId":"u56"},
    "2aab3bc0be514678867f804ccacd1fef":{
      "scriptId":"u57"},
    "06f25f54b055471bb49f313f78e72c2b":{
      "scriptId":"u58"}}});