$axure.loadCurrentPage({
  "url":"客户对账单.html",
  "generationDate":new Date(1446432611475.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c620ad4bd84948c1a1c4f4f05cd0056e",
    "type":"Axure:Page",
    "name":"客户对账单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c3d279ecbec1469b86222b956a6c2fa7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-214,
              "y":52},
            "size":{
              "width":1806,
              "height":775}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5fe1df73d64ca58fbea509d493caaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-214,
                  "y":52},
                "size":{
                  "width":1806,
                  "height":775}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户对账单/u0.png"}},
{
          "id":"e4e8edfafe89426c8b0072ae4af75bd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":249},
            "size":{
              "width":88,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51d0d64b2cd9414da9203330d26a6da9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":249},
                "size":{
                  "width":88,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户对账单/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c3d279ecbec1469b86222b956a6c2fa7":{
      "scriptId":"u0"},
    "8c5fe1df73d64ca58fbea509d493caaa":{
      "scriptId":"u1"},
    "e4e8edfafe89426c8b0072ae4af75bd9":{
      "scriptId":"u2"},
    "51d0d64b2cd9414da9203330d26a6da9":{
      "scriptId":"u3"}}});