$axure.loadCurrentPage({
  "url":"库存预警.html",
  "generationDate":new Date(1446432604150.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"34ab7e099dd44c69b1751f017f773f22",
    "type":"Axure:Page",
    "name":"库存预警",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"300439fa211047ffbc6f25f82aabd094",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":786,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e60f8c0573a481eb87dcd3528d8b894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":786,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u0.png"}},
{
          "id":"dfa8f9a8c7b84a8aa48b418749417201",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99c5114bae6944fda4eca15bf7401b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"b3e8b10d228f4401a721fda68f281e41",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":404,
              "y":78},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5977e2bc3b4a10b10e1df279f13ce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":404,
                  "y":78},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"525017154b3a4177a8c8e4cbe2f09480",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":1154,
              "y":76},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9b3ab0a059459ca042a5e135a9492c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":1154,
                  "y":76},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5710e23292074592b1ec03d82b3a2a8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":109},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f574df7ea54c460abd15683a291c3f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":109},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u12.png"}},
{
          "id":"6f2503ddb2a542c6964f437d53f29523",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":409,
              "y":112},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45630c11c0244b2c8d7b9226b33eef76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":409,
                  "y":112},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cd3f774bafe471ea70693c2e0fa9935",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":508,
              "y":109},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a48018134f4a34ac933c2af4e2235c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":508,
                  "y":109},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u12.png"}},
{
          "id":"d4bf5ea5035d4ea3b5a1389201e65828",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":109},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53aef42df24b4a6e924bd3aad275ab43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":623,
                  "y":109},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u12.png"}},
{
          "id":"d24c70a318214f549eab2912006f3a8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":529,
              "y":112},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a0fc14cf90e4ec4a5e9001b244f2226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":529,
                  "y":112},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b1fcce473ef4d94bb271056b4a066dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":643,
              "y":112},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a37641f3cf4632b3456afde0cdab70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":643,
                  "y":112},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"711111383bdc4283b3481b95fcda1ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":580},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9682ecaeb5aa4ccbb6d7b9e69f1c5f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":580},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"5621016278ed478eb45fd098378bac41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":995,
              "y":585},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a0d4e1a63c04deb90c0b6af94194551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":995,
                  "y":585},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u71.png"}},
{
          "id":"69067fcb755f477b835b8a62d534435d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1081,
              "y":585},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"597f287ba84b4910ac1f328a69241a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1081,
                  "y":585},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u73.png"}},
{
          "id":"59244732d83b4a23a41c1741a837c060",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":164},
            "size":{
              "width":13,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e242bbfbb13473fabce12dbcaf87c7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":164},
                "size":{
                  "width":13,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u26.png"}},
{
          "id":"00f63b48ba8b49a48e5332d0e015ec33",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":440,
              "y":160},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8594466ce63442da0a3c66078da20de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":160},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10160f1db75d43ffb368802c13861f6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":417,
              "y":200},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea21ad6be0d47c99eb5d3bfb0402318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":417,
                  "y":200},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec879925e7c14ad58459896dd2337e9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":194},
            "size":{
              "width":172,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d044c17324047598f129f8d5fa7bedf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":194},
                "size":{
                  "width":172,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u32.png"}},
{
          "id":"8a94290781aa4a59bef9cbe5c7846764",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":761,
              "y":200},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f30510cc034400be3ba1a576fdaebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":761,
                  "y":200},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"855cf1bb17614fd88a4a3a479f0ba19e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":866,
              "y":194},
            "size":{
              "width":172,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cf12ab5a75b4f8b8041a68aae477e43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":866,
                  "y":194},
                "size":{
                  "width":172,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/库存预警/u32.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "300439fa211047ffbc6f25f82aabd094":{
      "scriptId":"u0"},
    "7e60f8c0573a481eb87dcd3528d8b894":{
      "scriptId":"u1"},
    "dfa8f9a8c7b84a8aa48b418749417201":{
      "scriptId":"u2"},
    "99c5114bae6944fda4eca15bf7401b64":{
      "scriptId":"u3"},
    "b3e8b10d228f4401a721fda68f281e41":{
      "scriptId":"u4"},
    "8a5977e2bc3b4a10b10e1df279f13ce1":{
      "scriptId":"u5"},
    "525017154b3a4177a8c8e4cbe2f09480":{
      "scriptId":"u6"},
    "8c9b3ab0a059459ca042a5e135a9492c":{
      "scriptId":"u7"},
    "5710e23292074592b1ec03d82b3a2a8f":{
      "scriptId":"u8"},
    "f574df7ea54c460abd15683a291c3f53":{
      "scriptId":"u9"},
    "6f2503ddb2a542c6964f437d53f29523":{
      "scriptId":"u10"},
    "45630c11c0244b2c8d7b9226b33eef76":{
      "scriptId":"u11"},
    "6cd3f774bafe471ea70693c2e0fa9935":{
      "scriptId":"u12"},
    "e1a48018134f4a34ac933c2af4e2235c":{
      "scriptId":"u13"},
    "d4bf5ea5035d4ea3b5a1389201e65828":{
      "scriptId":"u14"},
    "53aef42df24b4a6e924bd3aad275ab43":{
      "scriptId":"u15"},
    "d24c70a318214f549eab2912006f3a8d":{
      "scriptId":"u16"},
    "5a0fc14cf90e4ec4a5e9001b244f2226":{
      "scriptId":"u17"},
    "7b1fcce473ef4d94bb271056b4a066dd":{
      "scriptId":"u18"},
    "42a37641f3cf4632b3456afde0cdab70":{
      "scriptId":"u19"},
    "711111383bdc4283b3481b95fcda1ed0":{
      "scriptId":"u20"},
    "9682ecaeb5aa4ccbb6d7b9e69f1c5f09":{
      "scriptId":"u21"},
    "5621016278ed478eb45fd098378bac41":{
      "scriptId":"u22"},
    "5a0d4e1a63c04deb90c0b6af94194551":{
      "scriptId":"u23"},
    "69067fcb755f477b835b8a62d534435d":{
      "scriptId":"u24"},
    "597f287ba84b4910ac1f328a69241a75":{
      "scriptId":"u25"},
    "59244732d83b4a23a41c1741a837c060":{
      "scriptId":"u26"},
    "2e242bbfbb13473fabce12dbcaf87c7e":{
      "scriptId":"u27"},
    "00f63b48ba8b49a48e5332d0e015ec33":{
      "scriptId":"u28"},
    "c8594466ce63442da0a3c66078da20de":{
      "scriptId":"u29"},
    "10160f1db75d43ffb368802c13861f6a":{
      "scriptId":"u30"},
    "9ea21ad6be0d47c99eb5d3bfb0402318":{
      "scriptId":"u31"},
    "ec879925e7c14ad58459896dd2337e9d":{
      "scriptId":"u32"},
    "0d044c17324047598f129f8d5fa7bedf":{
      "scriptId":"u33"},
    "8a94290781aa4a59bef9cbe5c7846764":{
      "scriptId":"u34"},
    "e2f30510cc034400be3ba1a576fdaebb":{
      "scriptId":"u35"},
    "855cf1bb17614fd88a4a3a479f0ba19e":{
      "scriptId":"u36"},
    "4cf12ab5a75b4f8b8041a68aae477e43":{
      "scriptId":"u37"}}});