$axure.loadCurrentPage({
  "url":"商品收发明细表.html",
  "generationDate":new Date(1446432611354.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7fd010ed02ae41c5b0f0f72c62399bdd",
    "type":"Axure:Page",
    "name":"商品收发明细表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f91819da81f43a5a66dbe2c9d8ff4c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-216,
              "y":28},
            "size":{
              "width":1811,
              "height":823}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17b6a2face6e42339bd5afc14cfc0bc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-216,
                  "y":28},
                "size":{
                  "width":1811,
                  "height":823}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品收发明细表/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2f91819da81f43a5a66dbe2c9d8ff4c4":{
      "scriptId":"u0"},
    "17b6a2face6e42339bd5afc14cfc0bc5":{
      "scriptId":"u1"}}});