$axure.loadCurrentPage({
  "url":"商品类别.html",
  "generationDate":new Date(1446432606712.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9fc1627196c4cf38ab74bf06aec2202",
    "type":"Axure:Page",
    "name":"商品类别",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9273241a7964a679f880e3f32d8f89d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8628ad6d9294f4e986821552cecfd83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"74aa608ff1c44b90817c2474cca370b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e8167a12da489fada01a9f7827a7b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda6e027724044faa92215c4bc744c56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c7f0538b8b94003b20d8e44c10e2d6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"c517361406a74a23bd37fd78bb52d1d3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"94a73beb3386441b99630c0673e8a1dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675a516d2ed44400be64f92b74d8fb0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a46f3dfda65a4102af4bf59af17bd2c8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"972a95ac357d4879afa271c2ebf1e784",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3cc1ded97249e3807eb2ded67fa6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d9c869949b84f8ebd06035f854483f7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"ba90df821c924066a2dafa0c77a59416",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a9b80578ddb41c39f201cf1dd312b34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bd77991d66348ec9fe4b08185b919f4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"0881c51749a549f28f3d699e02f7a020",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703de9bbd394472d8226fb42155a2e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0be2d9219a3142c1873dd8d4c8aa7c5e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"032a8c1309234cd28a47b8de6d2f0696",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"543823c2a44e4b6882f3aca04d7e0544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"6b3bcafd6dda4f6db765beb4c0e83db7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b92490ff46e542b381b9d64185253a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7ac81ea88e24551b67340c694b85976",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bcf75e8dfcb4bb48e60252518e8b4f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"ab3c95a23aa44ceb9e66e69510d6642a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"612722124fa9473284c20e2b4520eee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be828d7e2fa24435957c0982b6641970",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c46bc4cef5a417c97569c476d4bcc57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7939e365c7e64b4d8884bd8181394a1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358c55cb4f4a46b2b0a301b94278108c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"b977a812a93d42f882d9fe0d06697f06",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1758b857a2e4ebaae04333145a0fd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f00c98fb77f40ae8b272409f8037dd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8878bbd60614688a218c84d7b8df0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"ab0517a1ffa640129908cc6d83980dc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398a8495957444ce8cf82f776e589107",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"8f53926250d241a884931631d1998f8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506362196ec34af695f7599ea2e23e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"be50e09b426a40a196061c725c7c0633",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f07ba90448145c3aa5130acd8d81a68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8e9266348064781ad23188eaba14d1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18d2f42aefb4abb97a6a72859abdd6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"80f97b87fcd84ca3b7558d431108c768",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6850a4652854017b51916dc69dfc72c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"66181b2ad958403690aa10ef6df01ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96cdcf6a4e534848b3261e7a115c880c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba28654e1b7441fcb4a5821c1b5902ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0ff4e61233496c813945c9903989ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84264496c80f4c8ca360a5bea4a2095d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7eeeae4a0c34837a2bd453bc36f0608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"232fe35b37c545b0b7a8148fcab61e0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"459d77d51f9540a98ea87d0644575bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e82bb4ed846d47259efb3a10bbd46a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df6c79164d3d4046904634aeef55df89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae7b9497240e464baabd5d885de739cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60db63bcd78e44758ac378c03e156295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b42db3ab7444bbabbe29ecb446976a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5fd0483e2894846ba295a3133643c76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6afbfb26a61a417c9c8dfa5b5c4d1f6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f433e96a31f84cdd98f1c74927a53163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"8c91aa51b5bf45c8baea667ec31c63b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b600f1c7b14e8cb10c71c2fa3e3d18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"574baefa66604fa686b2d9163769c875",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e39318bdb5cb4502bbecd8ff094014b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"a15b8d58cde34b69bf6ca7c6c75a700a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd60a98dda054f9192f57b81256d2823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"a0f5bf6d1505436a87afca83a6135f03",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":347,
              "y":133},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f9689dfedd34951a370af61b87c15b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":347,
                  "y":133},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a27e6fb4feec449b95ffd165badb8ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":230},
            "size":{
              "width":1766,
              "height":688}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7a8289fb1d94609962904cd64a57662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":230},
                "size":{
                  "width":1766,
                  "height":688}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u69.png"}},
{
          "id":"2378f33cbd59496ba61eee021d4b541d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1493e6ec188445b59a6f5c1215e3a013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32480ccf709b41e78a71d9119c3a4061",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":186},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"320f2c2ecbdc472d9aad4f7c2ace1b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":186},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1403c5558424ec4a4c3c172d3278885",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":240,
              "y":230},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a34b68b76f44395b67b8eab79d78e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":240,
                  "y":230},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u75.png"}},
{
          "id":"5b81f140bcec40868cd96cfa71c24bb9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":230},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"a9ae0378a60148d9b408d8ea0c82f3ef",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":230},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"bdb65ea50014424190bf690c80abbdaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":416,
              "y":237},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"938e873072164533b68b9fd7009408f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":416,
                  "y":237},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c6e61a0d2c84280a35f5ad578dbf8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":630,
              "y":237},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da285058142d4b4fbae8b917a70c1f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":630,
                  "y":237},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfc36b76866c43f68a3646824e55442c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":269},
            "size":{
              "width":470,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a89260bf644df581393fc795e66d44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":269},
                "size":{
                  "width":470,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u83.png"}},
{
          "id":"2cbb09960e9b453d9a11fa54d1b1c6e2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":269},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"848cc89b384f4d5b85f50dee0f2e01e1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":269},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"29e8ec6c2bcf4e1185f739092ca8704a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":276},
            "size":{
              "width":19,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81b7e07f1ead46f68b425844a95d635d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":276},
                "size":{
                  "width":19,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"f571dfe92d504f8f96b1d31f8e3eca1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":280},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f132cc8229dc46fbbdb99b932a5ed355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":623,
                  "y":280},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u96.png"}},
{
          "id":"b4ac327916804c78b486a10265bbec67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":416,
              "y":277},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307597e04a46440db55b7b8abd90d6af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":416,
                  "y":277},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef24b3e0681d42be8fadd7840ac2e178",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1785,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7146383a804d7db8befb19370ad2f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1785,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"16ac48b1f6c74c80a5314f4cf8fa4b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1910,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f490caee4c84a689686552e1af42f27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1910,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"b886f1a7e93b4454b8acaccd940cb25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":319,
              "y":185},
            "size":{
              "width":81,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0b625464fe1429d806bc39fee52b399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":319,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户类别/u97.png"}},
{
          "id":"d8dbc979312c4c768f0bd96b0022035b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":398,
              "y":185},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0582809b22344695ba0bef6dc7518633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":398,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u99.png"}},
{
          "id":"fd31b3d2d4f543379fe8dcedf06c1455",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":473,
              "y":185},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e49b59132e9d4f448a1c47830b524698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":473,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户类别/u99.png"}},
{
          "id":"a81debfa37b04a13a2b0a1548c134fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":553,
              "y":185},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a499c296a5f248f4b35abf2e399cda58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":553,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u99.png"}},
{
          "id":"3ed8f041921e4295941398fcc554572e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":814,
              "y":185},
            "size":{
              "width":286,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8073370f05e54fac8f21dcae34bb5d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":814,
                  "y":185},
                "size":{
                  "width":286,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u105.png"}},
{
          "id":"1a31b94c33ae42a1b2704abecb787eff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1112,
              "y":185},
            "size":{
              "width":67,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba7931a0210a4fe186ca53a968989ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1112,
                  "y":185},
                "size":{
                  "width":67,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u107.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d9273241a7964a679f880e3f32d8f89d":{
      "scriptId":"u0"},
    "b8628ad6d9294f4e986821552cecfd83":{
      "scriptId":"u1"},
    "74aa608ff1c44b90817c2474cca370b3":{
      "scriptId":"u2"},
    "91e8167a12da489fada01a9f7827a7b6":{
      "scriptId":"u3"},
    "dda6e027724044faa92215c4bc744c56":{
      "scriptId":"u4"},
    "4c7f0538b8b94003b20d8e44c10e2d6e":{
      "scriptId":"u5"},
    "c517361406a74a23bd37fd78bb52d1d3":{
      "scriptId":"u6"},
    "94a73beb3386441b99630c0673e8a1dd":{
      "scriptId":"u7"},
    "675a516d2ed44400be64f92b74d8fb0e":{
      "scriptId":"u8"},
    "a46f3dfda65a4102af4bf59af17bd2c8":{
      "scriptId":"u9"},
    "972a95ac357d4879afa271c2ebf1e784":{
      "scriptId":"u10"},
    "2d3cc1ded97249e3807eb2ded67fa6cf":{
      "scriptId":"u11"},
    "8d9c869949b84f8ebd06035f854483f7":{
      "scriptId":"u12"},
    "ba90df821c924066a2dafa0c77a59416":{
      "scriptId":"u13"},
    "6a9b80578ddb41c39f201cf1dd312b34":{
      "scriptId":"u14"},
    "9bd77991d66348ec9fe4b08185b919f4":{
      "scriptId":"u15"},
    "0881c51749a549f28f3d699e02f7a020":{
      "scriptId":"u16"},
    "703de9bbd394472d8226fb42155a2e91":{
      "scriptId":"u17"},
    "0be2d9219a3142c1873dd8d4c8aa7c5e":{
      "scriptId":"u18"},
    "032a8c1309234cd28a47b8de6d2f0696":{
      "scriptId":"u19"},
    "543823c2a44e4b6882f3aca04d7e0544":{
      "scriptId":"u20"},
    "6b3bcafd6dda4f6db765beb4c0e83db7":{
      "scriptId":"u21"},
    "b92490ff46e542b381b9d64185253a90":{
      "scriptId":"u22"},
    "f7ac81ea88e24551b67340c694b85976":{
      "scriptId":"u23"},
    "5bcf75e8dfcb4bb48e60252518e8b4f8":{
      "scriptId":"u24"},
    "ab3c95a23aa44ceb9e66e69510d6642a":{
      "scriptId":"u25"},
    "612722124fa9473284c20e2b4520eee0":{
      "scriptId":"u26"},
    "be828d7e2fa24435957c0982b6641970":{
      "scriptId":"u27"},
    "0c46bc4cef5a417c97569c476d4bcc57":{
      "scriptId":"u28"},
    "7939e365c7e64b4d8884bd8181394a1f":{
      "scriptId":"u29"},
    "358c55cb4f4a46b2b0a301b94278108c":{
      "scriptId":"u30"},
    "b977a812a93d42f882d9fe0d06697f06":{
      "scriptId":"u31"},
    "d1758b857a2e4ebaae04333145a0fd49":{
      "scriptId":"u32"},
    "1f00c98fb77f40ae8b272409f8037dd9":{
      "scriptId":"u33"},
    "f8878bbd60614688a218c84d7b8df0f3":{
      "scriptId":"u34"},
    "ab0517a1ffa640129908cc6d83980dc8":{
      "scriptId":"u35"},
    "398a8495957444ce8cf82f776e589107":{
      "scriptId":"u36"},
    "8f53926250d241a884931631d1998f8e":{
      "scriptId":"u37"},
    "506362196ec34af695f7599ea2e23e9f":{
      "scriptId":"u38"},
    "be50e09b426a40a196061c725c7c0633":{
      "scriptId":"u39"},
    "5f07ba90448145c3aa5130acd8d81a68":{
      "scriptId":"u40"},
    "f8e9266348064781ad23188eaba14d1d":{
      "scriptId":"u41"},
    "f18d2f42aefb4abb97a6a72859abdd6b":{
      "scriptId":"u42"},
    "80f97b87fcd84ca3b7558d431108c768":{
      "scriptId":"u43"},
    "a6850a4652854017b51916dc69dfc72c":{
      "scriptId":"u44"},
    "66181b2ad958403690aa10ef6df01ced":{
      "scriptId":"u45"},
    "96cdcf6a4e534848b3261e7a115c880c":{
      "scriptId":"u46"},
    "ba28654e1b7441fcb4a5821c1b5902ae":{
      "scriptId":"u47"},
    "2c0ff4e61233496c813945c9903989ce":{
      "scriptId":"u48"},
    "84264496c80f4c8ca360a5bea4a2095d":{
      "scriptId":"u49"},
    "c7eeeae4a0c34837a2bd453bc36f0608":{
      "scriptId":"u50"},
    "232fe35b37c545b0b7a8148fcab61e0c":{
      "scriptId":"u51"},
    "459d77d51f9540a98ea87d0644575bd2":{
      "scriptId":"u52"},
    "e82bb4ed846d47259efb3a10bbd46a9a":{
      "scriptId":"u53"},
    "df6c79164d3d4046904634aeef55df89":{
      "scriptId":"u54"},
    "ae7b9497240e464baabd5d885de739cd":{
      "scriptId":"u55"},
    "60db63bcd78e44758ac378c03e156295":{
      "scriptId":"u56"},
    "7b42db3ab7444bbabbe29ecb446976a5":{
      "scriptId":"u57"},
    "f5fd0483e2894846ba295a3133643c76":{
      "scriptId":"u58"},
    "6afbfb26a61a417c9c8dfa5b5c4d1f6e":{
      "scriptId":"u59"},
    "f433e96a31f84cdd98f1c74927a53163":{
      "scriptId":"u60"},
    "8c91aa51b5bf45c8baea667ec31c63b8":{
      "scriptId":"u61"},
    "e1b600f1c7b14e8cb10c71c2fa3e3d18":{
      "scriptId":"u62"},
    "574baefa66604fa686b2d9163769c875":{
      "scriptId":"u63"},
    "e39318bdb5cb4502bbecd8ff094014b3":{
      "scriptId":"u64"},
    "a15b8d58cde34b69bf6ca7c6c75a700a":{
      "scriptId":"u65"},
    "fd60a98dda054f9192f57b81256d2823":{
      "scriptId":"u66"},
    "a0f5bf6d1505436a87afca83a6135f03":{
      "scriptId":"u67"},
    "7f9689dfedd34951a370af61b87c15b3":{
      "scriptId":"u68"},
    "a27e6fb4feec449b95ffd165badb8ffe":{
      "scriptId":"u69"},
    "e7a8289fb1d94609962904cd64a57662":{
      "scriptId":"u70"},
    "2378f33cbd59496ba61eee021d4b541d":{
      "scriptId":"u71"},
    "1493e6ec188445b59a6f5c1215e3a013":{
      "scriptId":"u72"},
    "32480ccf709b41e78a71d9119c3a4061":{
      "scriptId":"u73"},
    "320f2c2ecbdc472d9aad4f7c2ace1b22":{
      "scriptId":"u74"},
    "c1403c5558424ec4a4c3c172d3278885":{
      "scriptId":"u75"},
    "8a34b68b76f44395b67b8eab79d78e77":{
      "scriptId":"u76"},
    "5b81f140bcec40868cd96cfa71c24bb9":{
      "scriptId":"u77"},
    "a9ae0378a60148d9b408d8ea0c82f3ef":{
      "scriptId":"u78"},
    "bdb65ea50014424190bf690c80abbdaf":{
      "scriptId":"u79"},
    "938e873072164533b68b9fd7009408f0":{
      "scriptId":"u80"},
    "3c6e61a0d2c84280a35f5ad578dbf8e9":{
      "scriptId":"u81"},
    "da285058142d4b4fbae8b917a70c1f00":{
      "scriptId":"u82"},
    "cfc36b76866c43f68a3646824e55442c":{
      "scriptId":"u83"},
    "b1a89260bf644df581393fc795e66d44":{
      "scriptId":"u84"},
    "2cbb09960e9b453d9a11fa54d1b1c6e2":{
      "scriptId":"u85"},
    "848cc89b384f4d5b85f50dee0f2e01e1":{
      "scriptId":"u86"},
    "29e8ec6c2bcf4e1185f739092ca8704a":{
      "scriptId":"u87"},
    "81b7e07f1ead46f68b425844a95d635d":{
      "scriptId":"u88"},
    "f571dfe92d504f8f96b1d31f8e3eca1d":{
      "scriptId":"u89"},
    "f132cc8229dc46fbbdb99b932a5ed355":{
      "scriptId":"u90"},
    "b4ac327916804c78b486a10265bbec67":{
      "scriptId":"u91"},
    "307597e04a46440db55b7b8abd90d6af":{
      "scriptId":"u92"},
    "ef24b3e0681d42be8fadd7840ac2e178":{
      "scriptId":"u93"},
    "6c7146383a804d7db8befb19370ad2f9":{
      "scriptId":"u94"},
    "16ac48b1f6c74c80a5314f4cf8fa4b39":{
      "scriptId":"u95"},
    "4f490caee4c84a689686552e1af42f27":{
      "scriptId":"u96"},
    "b886f1a7e93b4454b8acaccd940cb25e":{
      "scriptId":"u97"},
    "f0b625464fe1429d806bc39fee52b399":{
      "scriptId":"u98"},
    "d8dbc979312c4c768f0bd96b0022035b":{
      "scriptId":"u99"},
    "0582809b22344695ba0bef6dc7518633":{
      "scriptId":"u100"},
    "fd31b3d2d4f543379fe8dcedf06c1455":{
      "scriptId":"u101"},
    "e49b59132e9d4f448a1c47830b524698":{
      "scriptId":"u102"},
    "a81debfa37b04a13a2b0a1548c134fbe":{
      "scriptId":"u103"},
    "a499c296a5f248f4b35abf2e399cda58":{
      "scriptId":"u104"},
    "3ed8f041921e4295941398fcc554572e":{
      "scriptId":"u105"},
    "8073370f05e54fac8f21dcae34bb5d88":{
      "scriptId":"u106"},
    "1a31b94c33ae42a1b2704abecb787eff":{
      "scriptId":"u107"},
    "ba7931a0210a4fe186ca53a968989ca6":{
      "scriptId":"u108"}}});