$axure.loadCurrentPage({
  "url":"新增供应商.html",
  "generationDate":new Date(1446432604603.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2be629b1c69545ef9310ffdba467e177",
    "type":"Axure:Page",
    "name":"新增供应商",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ce0193d159954171b64b815bbff7c0d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":786,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c2a1b85510a43ac85f323bae5233080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":786,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u0.png"}},
{
          "id":"29e92c1da0e5430f999909db533a0b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":70},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b74d532c604f658f22ea920586f147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":70},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"21d2e622c02145a0a11ff5b6ef7ad5f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":404,
              "y":78},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28617de24a38490ea043c62dc2f156cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":404,
                  "y":78},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d5b29599ce48a98a5cafc7765eb1dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":1154,
              "y":76},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6d521f358d64f3691c4735c49bae785",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":1154,
                  "y":76},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20ed66500e2947ec88c9216c8f09bc85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":580},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d175c1fcce68454580c5de0afae6c61b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":580},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"9ceffb0df9a74190bd5fe3c914eb0bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":995,
              "y":585},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1437d4acd0164c908206745c64472064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":995,
                  "y":585},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u71.png"}},
{
          "id":"3704e253ae63418bb9621ace112fac59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1081,
              "y":585},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dfdb01554f74af1af397a82c913d6e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1081,
                  "y":585},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u73.png"}},
{
          "id":"25aed2a12fce4973b93f3143741f2401",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":130},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764074cf2ea84cd48848dadcf29a399d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":130},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e483b0d7984a4306a43b282372b9c1ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":130},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5293f0cabb874a47b42304b4b82a036a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":130},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"aff6b1a4b0af4addb0ed2ef03b077c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":809,
              "y":130},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdf68048800a403cbc1395f3d191ff08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":809,
                  "y":130},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54cfd9374f0540fdb403c19a613848fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":130},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731c1370bbad4098ba0398c073e3d5e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":939,
                  "y":130},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"04dd05b5bfa74262a83a7d55660402fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":195},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf7e7c8a35fa4ee094329eac41003fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":195},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc10481cb48848b983889f17961cc555",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":195},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2625c060fc741edb84a1c4ea97d9007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":195},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"f61839ee23064e66b6cf467287295987",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":814,
              "y":195},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52848543f2764c6ea5762aa618b2eb70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":814,
                  "y":195},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcbe8fbdc42543728da6cc19f340ce28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "location":{
              "x":944,
              "y":195},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2bb330a55fd459ca637c2b0cb826e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "location":{
                  "x":944,
                  "y":195},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"82fbdda916dc449483daa0c6f1aa66d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1141,
              "y":199.5},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c968067d64f4483ab7f40ca3e1f51aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1141,
                  "y":199.5},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}},
{
          "id":"5d18fd1563cf42ebace9813c95efc740",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":269},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c92209d102c4bd4aad1e3f69d338b63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":269},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efcd349c8680401f99068fa46d06b3dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":269},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02c037f43e5400b872feb17c3297ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":269},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"faefdf04b97c48809940fa3d20f75b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":814,
              "y":269},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e810ce32d6447db8fc1622f00916072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":814,
                  "y":269},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c396a75c06a14067baf209bc8d7f5cf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":269},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23505419ef4e48ab808b2e9c66330bf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":269},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u16.png"}},
{
          "id":"3c1447aeb3924804afb14036b8536246",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":320},
            "size":{
              "width":734,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3984ba6a330a44dc83970da84644f4f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":320},
                "size":{
                  "width":734,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u40.png"}},
{
          "id":"7dd86d9d1a35414c84a07ff023f46f37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":430,
              "y":530},
            "size":{
              "width":734,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"516981c4e1f94f5fb55d1dbec5ecd021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":530},
                "size":{
                  "width":734,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u42.png"}},
{
          "id":"8eef42df75b749339e2b2ca930afcea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":320},
            "size":{
              "width":734,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14451965a2a94915a129da692af8fbf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":320},
                "size":{
                  "width":734,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增供应商/u44.png"}},
{
          "id":"cb3a263b933c4fb7b39e4daa3037c7e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":450,
              "y":326},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"860f9d37a47044f4ac262fcb57526364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":450,
                  "y":326},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26d1318aa29445ef94ce500daee87133",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":590,
              "y":326},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a676f133c1740ab9846baa315755b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":590,
                  "y":326},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87c0a7445a1b410a84e01eedd0a09715",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":708,
              "y":326},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca6449efa234838bd9ace63fc0e4931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":708,
                  "y":326},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6e000f47fb149faaf8b49942c643877",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":864,
              "y":326},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a02376e0f924b78b2de4f1b4c104697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":864,
                  "y":326},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5477f7d24f2a40b1aced313481dc820e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":1056,
              "y":326},
            "size":{
              "width":76,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b04d11f1004f3eb34cf48b5a45b225",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":1056,
                  "y":326},
                "size":{
                  "width":76,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d969cc3c33554480b856513c4c06cb0f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":320},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"c76cafbc5ace42a7a7b6dbe0be6ce8f6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":320},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"e8e1fa3244664f1aaf27d5636fb8d379",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":784,
              "y":320},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"4f15b5b7804b43aa9cffca2ddf1f3723",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1035,
              "y":320},
            "size":{
              "width":10,
              "height":180}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u56_line.png"}},
{
          "id":"9b77341c1bb74cf9a739f20bd81b767b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":370},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"e4413aba02ab4bb09324be0094fc73d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":402.5},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"3940d508f39a4454bc362405ddab3775",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":432},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}},
{
          "id":"d99a8a68d9a84e31bb6968712f398f29",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":463.25},
            "size":{
              "width":734,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增供应商/u60_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ce0193d159954171b64b815bbff7c0d7":{
      "scriptId":"u0"},
    "1c2a1b85510a43ac85f323bae5233080":{
      "scriptId":"u1"},
    "29e92c1da0e5430f999909db533a0b7c":{
      "scriptId":"u2"},
    "a6b74d532c604f658f22ea920586f147":{
      "scriptId":"u3"},
    "21d2e622c02145a0a11ff5b6ef7ad5f9":{
      "scriptId":"u4"},
    "28617de24a38490ea043c62dc2f156cd":{
      "scriptId":"u5"},
    "b4d5b29599ce48a98a5cafc7765eb1dc":{
      "scriptId":"u6"},
    "b6d521f358d64f3691c4735c49bae785":{
      "scriptId":"u7"},
    "20ed66500e2947ec88c9216c8f09bc85":{
      "scriptId":"u8"},
    "d175c1fcce68454580c5de0afae6c61b":{
      "scriptId":"u9"},
    "9ceffb0df9a74190bd5fe3c914eb0bb8":{
      "scriptId":"u10"},
    "1437d4acd0164c908206745c64472064":{
      "scriptId":"u11"},
    "3704e253ae63418bb9621ace112fac59":{
      "scriptId":"u12"},
    "9dfdb01554f74af1af397a82c913d6e3":{
      "scriptId":"u13"},
    "25aed2a12fce4973b93f3143741f2401":{
      "scriptId":"u14"},
    "764074cf2ea84cd48848dadcf29a399d":{
      "scriptId":"u15"},
    "e483b0d7984a4306a43b282372b9c1ba":{
      "scriptId":"u16"},
    "5293f0cabb874a47b42304b4b82a036a":{
      "scriptId":"u17"},
    "aff6b1a4b0af4addb0ed2ef03b077c64":{
      "scriptId":"u18"},
    "cdf68048800a403cbc1395f3d191ff08":{
      "scriptId":"u19"},
    "54cfd9374f0540fdb403c19a613848fc":{
      "scriptId":"u20"},
    "731c1370bbad4098ba0398c073e3d5e4":{
      "scriptId":"u21"},
    "04dd05b5bfa74262a83a7d55660402fe":{
      "scriptId":"u22"},
    "cf7e7c8a35fa4ee094329eac41003fb2":{
      "scriptId":"u23"},
    "fc10481cb48848b983889f17961cc555":{
      "scriptId":"u24"},
    "e2625c060fc741edb84a1c4ea97d9007":{
      "scriptId":"u25"},
    "f61839ee23064e66b6cf467287295987":{
      "scriptId":"u26"},
    "52848543f2764c6ea5762aa618b2eb70":{
      "scriptId":"u27"},
    "fcbe8fbdc42543728da6cc19f340ce28":{
      "scriptId":"u28"},
    "d2bb330a55fd459ca637c2b0cb826e8c":{
      "scriptId":"u29"},
    "82fbdda916dc449483daa0c6f1aa66d5":{
      "scriptId":"u30"},
    "3c968067d64f4483ab7f40ca3e1f51aa":{
      "scriptId":"u31"},
    "5d18fd1563cf42ebace9813c95efc740":{
      "scriptId":"u32"},
    "2c92209d102c4bd4aad1e3f69d338b63":{
      "scriptId":"u33"},
    "efcd349c8680401f99068fa46d06b3dc":{
      "scriptId":"u34"},
    "f02c037f43e5400b872feb17c3297ceb":{
      "scriptId":"u35"},
    "faefdf04b97c48809940fa3d20f75b25":{
      "scriptId":"u36"},
    "3e810ce32d6447db8fc1622f00916072":{
      "scriptId":"u37"},
    "c396a75c06a14067baf209bc8d7f5cf4":{
      "scriptId":"u38"},
    "23505419ef4e48ab808b2e9c66330bf2":{
      "scriptId":"u39"},
    "3c1447aeb3924804afb14036b8536246":{
      "scriptId":"u40"},
    "3984ba6a330a44dc83970da84644f4f4":{
      "scriptId":"u41"},
    "7dd86d9d1a35414c84a07ff023f46f37":{
      "scriptId":"u42"},
    "516981c4e1f94f5fb55d1dbec5ecd021":{
      "scriptId":"u43"},
    "8eef42df75b749339e2b2ca930afcea9":{
      "scriptId":"u44"},
    "14451965a2a94915a129da692af8fbf8":{
      "scriptId":"u45"},
    "cb3a263b933c4fb7b39e4daa3037c7e3":{
      "scriptId":"u46"},
    "860f9d37a47044f4ac262fcb57526364":{
      "scriptId":"u47"},
    "26d1318aa29445ef94ce500daee87133":{
      "scriptId":"u48"},
    "5a676f133c1740ab9846baa315755b26":{
      "scriptId":"u49"},
    "87c0a7445a1b410a84e01eedd0a09715":{
      "scriptId":"u50"},
    "fca6449efa234838bd9ace63fc0e4931":{
      "scriptId":"u51"},
    "e6e000f47fb149faaf8b49942c643877":{
      "scriptId":"u52"},
    "3a02376e0f924b78b2de4f1b4c104697":{
      "scriptId":"u53"},
    "5477f7d24f2a40b1aced313481dc820e":{
      "scriptId":"u54"},
    "70b04d11f1004f3eb34cf48b5a45b225":{
      "scriptId":"u55"},
    "d969cc3c33554480b856513c4c06cb0f":{
      "scriptId":"u56"},
    "c76cafbc5ace42a7a7b6dbe0be6ce8f6":{
      "scriptId":"u57"},
    "e8e1fa3244664f1aaf27d5636fb8d379":{
      "scriptId":"u58"},
    "4f15b5b7804b43aa9cffca2ddf1f3723":{
      "scriptId":"u59"},
    "9b77341c1bb74cf9a739f20bd81b767b":{
      "scriptId":"u60"},
    "e4413aba02ab4bb09324be0094fc73d7":{
      "scriptId":"u61"},
    "3940d508f39a4454bc362405ddab3775":{
      "scriptId":"u62"},
    "d99a8a68d9a84e31bb6968712f398f29":{
      "scriptId":"u63"}}});