$axure.loadCurrentPage({
  "url":"新增设备类别.html",
  "generationDate":new Date(1446432607039.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"71f3a49e630343c2856252baf04b5eb7",
    "type":"Axure:Page",
    "name":"新增设备类别",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ea4127cffe574fc281a44341f1bb471f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":252}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd8f538e0744b99a03bd41629e3d9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":252}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u0.png"}},
{
          "id":"60fc03cf9d4c4acabeaa3982d41e86ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f4d4c8a4894a81902e0013f139296e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u2.png"}},
{
          "id":"92a0bb70bbc2490580f7886e5218e702",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":385,
              "y":56},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c0ec597c434e47b97d0a30a34b601e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":385,
                  "y":56},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6b93d65f1094b67822541dafb23315a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":728,
              "y":53},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83b8efceaa0e487db8b7b8e60ccb8b76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":728,
                  "y":53},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3149807eecc349428e75b3381edfe9e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":270},
            "size":{
              "width":360,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d58be5b70f34444a959b01c509701bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":270},
                "size":{
                  "width":360,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u8.png"}},
{
          "id":"7af2999a60034fa8a839a4a4518beb72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":630,
              "y":274},
            "size":{
              "width":52,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc3f3b50a5b3482086fb3ec8ce1da82a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":630,
                  "y":274},
                "size":{
                  "width":52,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u10.png"}},
{
          "id":"7b3b1364af214d22adc40fe6362d46b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":692,
              "y":274},
            "size":{
              "width":38,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d0b1c0c4194df1af3a590570e59823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":692,
                  "y":274},
                "size":{
                  "width":38,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u12.png"}},
{
          "id":"ec58bffa859f420bbcb0a7e3255a3010",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":170},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dfd0dd12c2e44fb82301a4a2a76b5a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":170},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2877ffdf60b940e88c0499743e49ac73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":165},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d78519d9d14398b7d8aa3dd39a7238",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":165},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ea4127cffe574fc281a44341f1bb471f":{
      "scriptId":"u0"},
    "4cd8f538e0744b99a03bd41629e3d9be":{
      "scriptId":"u1"},
    "60fc03cf9d4c4acabeaa3982d41e86ae":{
      "scriptId":"u2"},
    "69f4d4c8a4894a81902e0013f139296e":{
      "scriptId":"u3"},
    "92a0bb70bbc2490580f7886e5218e702":{
      "scriptId":"u4"},
    "62c0ec597c434e47b97d0a30a34b601e":{
      "scriptId":"u5"},
    "b6b93d65f1094b67822541dafb23315a":{
      "scriptId":"u6"},
    "83b8efceaa0e487db8b7b8e60ccb8b76":{
      "scriptId":"u7"},
    "3149807eecc349428e75b3381edfe9e7":{
      "scriptId":"u8"},
    "3d58be5b70f34444a959b01c509701bb":{
      "scriptId":"u9"},
    "7af2999a60034fa8a839a4a4518beb72":{
      "scriptId":"u10"},
    "fc3f3b50a5b3482086fb3ec8ce1da82a":{
      "scriptId":"u11"},
    "7b3b1364af214d22adc40fe6362d46b4":{
      "scriptId":"u12"},
    "42d0b1c0c4194df1af3a590570e59823":{
      "scriptId":"u13"},
    "ec58bffa859f420bbcb0a7e3255a3010":{
      "scriptId":"u14"},
    "6dfd0dd12c2e44fb82301a4a2a76b5a3":{
      "scriptId":"u15"},
    "2877ffdf60b940e88c0499743e49ac73":{
      "scriptId":"u16"},
    "96d78519d9d14398b7d8aa3dd39a7238":{
      "scriptId":"u17"}}});