$axure.loadCurrentPage({
  "url":"采购汇总表（按供应商）.html",
  "generationDate":new Date(1446432610203.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b2d280df91f847f687db7a4e049a3215",
    "type":"Axure:Page",
    "name":"采购汇总表（按供应商）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3dc0c9356eac470384e28be21c0de88b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f8346bd0bd4b30bacbafbf30ac57c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"2bf657f7263244d0b86e075d36e68400",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db91d4d4e21499b8153b4644bc991c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbe3562cba0a42db8ac73929046ce511",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f086dd40184e63893c4fa787f3b87e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"1bfb81021f7a4c37b4f114ae55f42d89",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"f59af0fc2bd44eb6bdb0d92e9a59370d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"decefad7d38f40d79ec46b385c2703fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a08cfb5e55144968b0068542087e7b36",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"22a118317b0c4b9fbfe692d4a888fa12",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7dc073c7e44909b34a0f7077cebdb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e888549d7574145978d49f049a0450d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"82376ffcedd54def9e858d2fb753cd35",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c2516d7c6db4c2aa0e2a919b0504899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a9c9c321c5f4a8c93ff45a827b684ca",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"f29a48aeaa584e859eb80109a983d42a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed0314dfc49f40579e01693bf33a176d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54890da95874b5dba8e68b471babe7a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"0bf03b68a1b1467ca1fe15c597edf948",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8033abc071c44f0899ede8d272cf430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"7bfab15f03064fd19fbccd186008fd3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c123657317e0453ea3f9996d89fed314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"597ca850427049859c556a4579aa6f0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40a067fb852d4d0c8827009462e274c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"191d487219a041faa65676af6ca17e0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aacbfbba87ba4752b9eedf0faeba6033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"468f9bea1ff647ff93065c760d8a9721",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56aaf0a8dd2847ddb9e8d3dd13d722ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57449ae6f9f3427c8c5a35e696348bb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f96c166095ef44aab4add35ddda6cd0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"28114dfd1706491b908fcfdee11481cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2c02f74c424f47a91227901472de75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac6f837bf04449b3ae091ca8143774f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4373b359681946eaae70ce8efb26ff87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"06f7398e16e245b4a4191fe9d8bd8522",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c08aefc2919740099d1d6ee2fa86636f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"8cb9339c363443829055efdde91caf05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f603a47d8c8c422a8f797c933702c65b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"1bfe3305166b43c492a8fb4404440d55",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b754a93929324a518329976ddf4446f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"247e0b19c68849adb03963dc74f11dc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbcaf51d0cd64ac2ab7da6302a8cd6e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"9e014e6ea1f8494a800215b38e159a37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"114bf620b18a4c66a15f5b994f68aa7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"0a94d846bdbf45a6b51f26bbce815aa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a69e9a7257784fa7b0bde6cba9fa7d32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9b338d6280143e8bac666854bee74a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c40387b985e74838a07db4de2732a6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9738de9b5b6e4dcb942f401716eaee91",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c6d61709e064762b544dcc3f8e87cbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12de4eea331a45628af6cdf6a7732a32",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e822f5281b49c0b540d32e8c6a75f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a8cf8f49244bec8f7e2525a1b00d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82070bc3e4c4cd2a26c25ee22b22740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d63ab4ca148a444a94cc04a11e73db8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f5b7a1ca02452588031c7a2d579fee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fafaaeef0f9f4c64bc978e6635aa90c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a789e56e62a41f49a755f157631c951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4b0414d6ded4624a60c10a3b1f56990",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686de0ee778b494599a05860fbddc55c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"90ed880b7ad546de91c43c84bfdf567a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b0ed905868c460387e6c99201a2fd3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"6da3d120d8014167b4f4e3792bd8044a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f36f1cd2ff194f94b2248e7c05d0fde0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"182fde58952940acbe081d47215cc4f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d17339a1e9c400d9fe4e08285d4ef1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"b7f58963e6064945be2a0eb539376380",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":345,
              "y":134},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdedf065db88477c89f946cf4755ba18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":345,
                  "y":134},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02e5b0917ee04999950c09460210c197",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":258},
            "size":{
              "width":1766,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d12130423624b2a805d0b3e28c1a5c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":258},
                "size":{
                  "width":1766,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u69.png"}},
{
          "id":"3ec93ce70d4d48b5a6fbb715b9aaf595",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b68e1bce726e456f880b98742e084093",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b00b1dca438414eb824ac2e53dd9796",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":252,
              "y":195},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ecbc8311a9419c8f44a4cdf8d83001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":252,
                  "y":195},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c211ae514a14807a8c83b0ce67d61af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":195},
            "size":{
              "width":200,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9cbe3afd2ba4fba82c44244ccdf7cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":195},
                "size":{
                  "width":200,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u77.png"}},
{
          "id":"0e3e9c15c60a40de8547ef05ab254f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":194},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"477b29e1287844c1a5efef25f35df54b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":194},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u81.png"}},
{
          "id":"e6a5ef740cc14450a9cb39a61314c263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":199},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03c83457cdca4c458b29a74d48341e0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":199},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u83.png"}},
{
          "id":"9c5726cf3a9847b19fd0e3e80d74ca03",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1082,
              "y":273},
            "size":{
              "width":243,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41af2211188b49869ff3413b3245b736",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1082,
                  "y":273},
                "size":{
                  "width":243,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a737623b571149dd85e6c07a04fdf8e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":354},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f11614cb56484f8f5cc01ed8e42d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":354},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"fae724c4027c49bcb5a54e3ee9bfe34b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":399},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5402d7918b491f9ed9b7043ae6cbb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":399},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"7032d83151cc4257b3fe66ef4984ac46",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"00bfcce6a2324c1e93579fc1bfddcb59",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":309,
              "y":365},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e6d77fdff348eda478e90d350b1558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":309,
                  "y":365},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf48cb43b0244a2fb3cae1452c6fc9b6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"95e67019a30d4fd88dafcbf86f2455ee",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":905,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"66d6199720f949f580d48dc316b7605d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":985,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"c847f43064d14f13b66e5a016adebc0f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"28584abfc4ad4e2281bc7337d2d536f9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"0b42ad8d64484f4baf0e7e0e748aa07f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"446951118edd49bfb2efd5c64e3b567f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":605,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55425c8d94fa41d6abbcfd1e37ea6409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":605,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3d3e2c5a6754db68a99dc52588db77b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":806,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9364f931da7544718c0cedf494da14cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":806,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f4197eadb194e2da4c0281d501e5eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":928,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e05ac2651209445ca09206d4c05124ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":928,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9043e9cdc10341f48d7ad386ac2460d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2432e0ec8c3e41118917ab2b0c84c446",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c19c044e67c6432a848c973e8e1df5d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1116,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a798dae534a4037972e367c592d43ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1116,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78ae930407704396aff73a7bfecb6035",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1225,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe13f64ca6c4da187942954213c01da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1225,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67bdb7f9b1b04cd5b8c65f088c72f6e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd4ea9ae6db3406a8f9898b448428ff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be3b74607e514c9ebc528e0a0f2bdd27",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"e21b55e09d50478793e1b6c83ebcc514",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"e3378e7137924a82a1a348e92763ba76",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"baeaec437afb47e7850c4834a0ef84bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1003,
              "y":410},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2ea31fbcaf2416389968b6cbffd512f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1003,
                  "y":410},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da5abd2873d546a681d490566a961687",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":289,
              "y":325},
            "size":{
              "width":209,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"816160aafd44470d815f20ac55750086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":289,
                  "y":325},
                "size":{
                  "width":209,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0837a976664c43858e977caaa20a7759",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520.30773925781,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"38f5b2a7d18c46cc861ef81cc687c660",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"139e4a14f7204549bcc5860f86221fac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":427,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec6ba873f3114c4b8a1e8e9f45ff8aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":427,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23057bbb93fa49ae82768d526aa5ef77",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"693ae532129c4ad7bc6bb5cd56281d2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF449513},
            "location":{
              "x":1806,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdcb6a5fe5b44836921115bba3ae9b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF449513},
                "location":{
                  "x":1806,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u129.png"}},
{
          "id":"522aa20be2244999b8edfc8aa5ae718f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1920,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db074fe91ac49b2ae5567109c7a87a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1920,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u131.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3dc0c9356eac470384e28be21c0de88b":{
      "scriptId":"u0"},
    "b6f8346bd0bd4b30bacbafbf30ac57c8":{
      "scriptId":"u1"},
    "2bf657f7263244d0b86e075d36e68400":{
      "scriptId":"u2"},
    "4db91d4d4e21499b8153b4644bc991c7":{
      "scriptId":"u3"},
    "dbe3562cba0a42db8ac73929046ce511":{
      "scriptId":"u4"},
    "a3f086dd40184e63893c4fa787f3b87e":{
      "scriptId":"u5"},
    "1bfb81021f7a4c37b4f114ae55f42d89":{
      "scriptId":"u6"},
    "f59af0fc2bd44eb6bdb0d92e9a59370d":{
      "scriptId":"u7"},
    "decefad7d38f40d79ec46b385c2703fd":{
      "scriptId":"u8"},
    "a08cfb5e55144968b0068542087e7b36":{
      "scriptId":"u9"},
    "22a118317b0c4b9fbfe692d4a888fa12":{
      "scriptId":"u10"},
    "dc7dc073c7e44909b34a0f7077cebdb0":{
      "scriptId":"u11"},
    "6e888549d7574145978d49f049a0450d":{
      "scriptId":"u12"},
    "82376ffcedd54def9e858d2fb753cd35":{
      "scriptId":"u13"},
    "6c2516d7c6db4c2aa0e2a919b0504899":{
      "scriptId":"u14"},
    "6a9c9c321c5f4a8c93ff45a827b684ca":{
      "scriptId":"u15"},
    "f29a48aeaa584e859eb80109a983d42a":{
      "scriptId":"u16"},
    "ed0314dfc49f40579e01693bf33a176d":{
      "scriptId":"u17"},
    "e54890da95874b5dba8e68b471babe7a":{
      "scriptId":"u18"},
    "0bf03b68a1b1467ca1fe15c597edf948":{
      "scriptId":"u19"},
    "c8033abc071c44f0899ede8d272cf430":{
      "scriptId":"u20"},
    "7bfab15f03064fd19fbccd186008fd3b":{
      "scriptId":"u21"},
    "c123657317e0453ea3f9996d89fed314":{
      "scriptId":"u22"},
    "597ca850427049859c556a4579aa6f0b":{
      "scriptId":"u23"},
    "40a067fb852d4d0c8827009462e274c7":{
      "scriptId":"u24"},
    "191d487219a041faa65676af6ca17e0c":{
      "scriptId":"u25"},
    "aacbfbba87ba4752b9eedf0faeba6033":{
      "scriptId":"u26"},
    "468f9bea1ff647ff93065c760d8a9721":{
      "scriptId":"u27"},
    "56aaf0a8dd2847ddb9e8d3dd13d722ea":{
      "scriptId":"u28"},
    "57449ae6f9f3427c8c5a35e696348bb6":{
      "scriptId":"u29"},
    "f96c166095ef44aab4add35ddda6cd0b":{
      "scriptId":"u30"},
    "28114dfd1706491b908fcfdee11481cf":{
      "scriptId":"u31"},
    "8a2c02f74c424f47a91227901472de75":{
      "scriptId":"u32"},
    "ac6f837bf04449b3ae091ca8143774f2":{
      "scriptId":"u33"},
    "4373b359681946eaae70ce8efb26ff87":{
      "scriptId":"u34"},
    "06f7398e16e245b4a4191fe9d8bd8522":{
      "scriptId":"u35"},
    "c08aefc2919740099d1d6ee2fa86636f":{
      "scriptId":"u36"},
    "8cb9339c363443829055efdde91caf05":{
      "scriptId":"u37"},
    "f603a47d8c8c422a8f797c933702c65b":{
      "scriptId":"u38"},
    "1bfe3305166b43c492a8fb4404440d55":{
      "scriptId":"u39"},
    "b754a93929324a518329976ddf4446f6":{
      "scriptId":"u40"},
    "247e0b19c68849adb03963dc74f11dc1":{
      "scriptId":"u41"},
    "bbcaf51d0cd64ac2ab7da6302a8cd6e8":{
      "scriptId":"u42"},
    "9e014e6ea1f8494a800215b38e159a37":{
      "scriptId":"u43"},
    "114bf620b18a4c66a15f5b994f68aa7b":{
      "scriptId":"u44"},
    "0a94d846bdbf45a6b51f26bbce815aa4":{
      "scriptId":"u45"},
    "a69e9a7257784fa7b0bde6cba9fa7d32":{
      "scriptId":"u46"},
    "b9b338d6280143e8bac666854bee74a9":{
      "scriptId":"u47"},
    "c40387b985e74838a07db4de2732a6ae":{
      "scriptId":"u48"},
    "9738de9b5b6e4dcb942f401716eaee91":{
      "scriptId":"u49"},
    "8c6d61709e064762b544dcc3f8e87cbe":{
      "scriptId":"u50"},
    "12de4eea331a45628af6cdf6a7732a32":{
      "scriptId":"u51"},
    "c0e822f5281b49c0b540d32e8c6a75f4":{
      "scriptId":"u52"},
    "26a8cf8f49244bec8f7e2525a1b00d84":{
      "scriptId":"u53"},
    "f82070bc3e4c4cd2a26c25ee22b22740":{
      "scriptId":"u54"},
    "d63ab4ca148a444a94cc04a11e73db8b":{
      "scriptId":"u55"},
    "07f5b7a1ca02452588031c7a2d579fee":{
      "scriptId":"u56"},
    "fafaaeef0f9f4c64bc978e6635aa90c2":{
      "scriptId":"u57"},
    "2a789e56e62a41f49a755f157631c951":{
      "scriptId":"u58"},
    "a4b0414d6ded4624a60c10a3b1f56990":{
      "scriptId":"u59"},
    "686de0ee778b494599a05860fbddc55c":{
      "scriptId":"u60"},
    "90ed880b7ad546de91c43c84bfdf567a":{
      "scriptId":"u61"},
    "2b0ed905868c460387e6c99201a2fd3d":{
      "scriptId":"u62"},
    "6da3d120d8014167b4f4e3792bd8044a":{
      "scriptId":"u63"},
    "f36f1cd2ff194f94b2248e7c05d0fde0":{
      "scriptId":"u64"},
    "182fde58952940acbe081d47215cc4f8":{
      "scriptId":"u65"},
    "7d17339a1e9c400d9fe4e08285d4ef1f":{
      "scriptId":"u66"},
    "b7f58963e6064945be2a0eb539376380":{
      "scriptId":"u67"},
    "fdedf065db88477c89f946cf4755ba18":{
      "scriptId":"u68"},
    "02e5b0917ee04999950c09460210c197":{
      "scriptId":"u69"},
    "2d12130423624b2a805d0b3e28c1a5c3":{
      "scriptId":"u70"},
    "3ec93ce70d4d48b5a6fbb715b9aaf595":{
      "scriptId":"u71"},
    "b68e1bce726e456f880b98742e084093":{
      "scriptId":"u72"},
    "8b00b1dca438414eb824ac2e53dd9796":{
      "scriptId":"u73"},
    "73ecbc8311a9419c8f44a4cdf8d83001":{
      "scriptId":"u74"},
    "4c211ae514a14807a8c83b0ce67d61af":{
      "scriptId":"u75"},
    "b9cbe3afd2ba4fba82c44244ccdf7cf8":{
      "scriptId":"u76"},
    "0e3e9c15c60a40de8547ef05ab254f48":{
      "scriptId":"u77"},
    "477b29e1287844c1a5efef25f35df54b":{
      "scriptId":"u78"},
    "e6a5ef740cc14450a9cb39a61314c263":{
      "scriptId":"u79"},
    "03c83457cdca4c458b29a74d48341e0b":{
      "scriptId":"u80"},
    "9c5726cf3a9847b19fd0e3e80d74ca03":{
      "scriptId":"u81"},
    "41af2211188b49869ff3413b3245b736":{
      "scriptId":"u82"},
    "a737623b571149dd85e6c07a04fdf8e6":{
      "scriptId":"u83"},
    "43f11614cb56484f8f5cc01ed8e42d7e":{
      "scriptId":"u84"},
    "fae724c4027c49bcb5a54e3ee9bfe34b":{
      "scriptId":"u85"},
    "6f5402d7918b491f9ed9b7043ae6cbb6":{
      "scriptId":"u86"},
    "7032d83151cc4257b3fe66ef4984ac46":{
      "scriptId":"u87"},
    "00bfcce6a2324c1e93579fc1bfddcb59":{
      "scriptId":"u88"},
    "d5e6d77fdff348eda478e90d350b1558":{
      "scriptId":"u89"},
    "cf48cb43b0244a2fb3cae1452c6fc9b6":{
      "scriptId":"u90"},
    "95e67019a30d4fd88dafcbf86f2455ee":{
      "scriptId":"u91"},
    "66d6199720f949f580d48dc316b7605d":{
      "scriptId":"u92"},
    "c847f43064d14f13b66e5a016adebc0f":{
      "scriptId":"u93"},
    "28584abfc4ad4e2281bc7337d2d536f9":{
      "scriptId":"u94"},
    "0b42ad8d64484f4baf0e7e0e748aa07f":{
      "scriptId":"u95"},
    "446951118edd49bfb2efd5c64e3b567f":{
      "scriptId":"u96"},
    "55425c8d94fa41d6abbcfd1e37ea6409":{
      "scriptId":"u97"},
    "a3d3e2c5a6754db68a99dc52588db77b":{
      "scriptId":"u98"},
    "9364f931da7544718c0cedf494da14cd":{
      "scriptId":"u99"},
    "7f4197eadb194e2da4c0281d501e5eec":{
      "scriptId":"u100"},
    "e05ac2651209445ca09206d4c05124ad":{
      "scriptId":"u101"},
    "9043e9cdc10341f48d7ad386ac2460d3":{
      "scriptId":"u102"},
    "2432e0ec8c3e41118917ab2b0c84c446":{
      "scriptId":"u103"},
    "c19c044e67c6432a848c973e8e1df5d2":{
      "scriptId":"u104"},
    "6a798dae534a4037972e367c592d43ea":{
      "scriptId":"u105"},
    "78ae930407704396aff73a7bfecb6035":{
      "scriptId":"u106"},
    "afe13f64ca6c4da187942954213c01da":{
      "scriptId":"u107"},
    "67bdb7f9b1b04cd5b8c65f088c72f6e7":{
      "scriptId":"u108"},
    "dd4ea9ae6db3406a8f9898b448428ff7":{
      "scriptId":"u109"},
    "be3b74607e514c9ebc528e0a0f2bdd27":{
      "scriptId":"u110"},
    "e21b55e09d50478793e1b6c83ebcc514":{
      "scriptId":"u111"},
    "e3378e7137924a82a1a348e92763ba76":{
      "scriptId":"u112"},
    "baeaec437afb47e7850c4834a0ef84bb":{
      "scriptId":"u113"},
    "b2ea31fbcaf2416389968b6cbffd512f":{
      "scriptId":"u114"},
    "da5abd2873d546a681d490566a961687":{
      "scriptId":"u115"},
    "816160aafd44470d815f20ac55750086":{
      "scriptId":"u116"},
    "0837a976664c43858e977caaa20a7759":{
      "scriptId":"u117"},
    "38f5b2a7d18c46cc861ef81cc687c660":{
      "scriptId":"u118"},
    "139e4a14f7204549bcc5860f86221fac":{
      "scriptId":"u119"},
    "ec6ba873f3114c4b8a1e8e9f45ff8aa3":{
      "scriptId":"u120"},
    "23057bbb93fa49ae82768d526aa5ef77":{
      "scriptId":"u121"},
    "693ae532129c4ad7bc6bb5cd56281d2e":{
      "scriptId":"u122"},
    "cdcb6a5fe5b44836921115bba3ae9b1c":{
      "scriptId":"u123"},
    "522aa20be2244999b8edfc8aa5ae718f":{
      "scriptId":"u124"},
    "2db074fe91ac49b2ae5567109c7a87a3":{
      "scriptId":"u125"}}});