$axure.loadCurrentPage({
  "url":"新增商品.html",
  "generationDate":new Date(1446432604084.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5cebf8866bed48f4a546304f273b2bc0",
    "type":"Axure:Page",
    "name":"新增商品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"690293ff9c4042b99b2b4491a09d2e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":160},
            "size":{
              "width":786,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a19411ccc39e4b84a588f1c55c2c43c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":160},
                "size":{
                  "width":786,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u0.png"}},
{
          "id":"f896e1713a194e038e70c1d2a26a9cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":160},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2034ddecad1f4a9ca9ab5b5f72b52a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":160},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"23cde13c2fa74fd4ad7da2bde90e1bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":764,
              "y":168},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2ecc72568eb48deb98333a6e3f124b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":764,
                  "y":168},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760631147ca34e8db11faa624854e363",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":1514,
              "y":166},
            "size":{
              "width":14,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d88fc989ebc143a197d50e83b11cf3d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":1514,
                  "y":166},
                "size":{
                  "width":14,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"193f77f737204c3483e1e8b01d595048",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":754,
              "y":199},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48aa1fa83d2d4301a0a8b0f017a6666d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":754,
                  "y":199},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u8.png"}},
{
          "id":"6902b4ba8561481093a7b7b830a55b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":769,
              "y":202},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"468c40408120491bac6b501ecee38be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":769,
                  "y":202},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6881a30d0d3043ca88a106818459f21b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":199},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8686e2bf89d446df8cd7fbc36bc62a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":199},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u12.png"}},
{
          "id":"850de06ca94b424e9992fb8000e16707",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":983,
              "y":199},
            "size":{
              "width":116,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c1b135b09d49eaad2fbe5dac537cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":983,
                  "y":199},
                "size":{
                  "width":116,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u12.png"}},
{
          "id":"c0d7b405042f440c9119d6b5591549c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":889,
              "y":202},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"133ddfc470194c04b3e2fb209e710c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":889,
                  "y":202},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"687aed61fb3742cba7af40f3e2563992",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":1003,
              "y":202},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"735cdbd00f164a929c538b83d037af83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":1003,
                  "y":202},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04b6db491ded4cc9ab447c1e5cdccf73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":777,
              "y":247},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3426f31efa944f481eb4a47beeac4b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":777,
                  "y":247},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e791aef805094bed900e53006e617634",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":247},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3af64782d464f7a8afe7f4cc199a129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":247},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"987211f8606542da88972e056d9fcbd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1063,
              "y":247},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a107b0577997419199aa455523e1f5c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1063,
                  "y":247},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dbf5800c8b14904bfa3d3b10b7639eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1154,
              "y":247},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd3a7efe5e84cad9a774b0da64d5eaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1154,
                  "y":247},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"ad937f4b89b348659a1b16bc5e81a559",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1063,
              "y":289},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21d3541b7584018b57503b41ed25c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1063,
                  "y":289},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e35436c2caba4264819c4f75b6d9cd57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1154,
              "y":289},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea23bc02d76847899db3e814ef442618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1154,
                  "y":289},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"0a07f4483d2b40fa935b5aeed3bc9cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":779,
              "y":289},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fada14fde0294cb884344f0bec4f56b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":779,
                  "y":289},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50ac395817f64454875432a3759b4704",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":289},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1806452039dc4d87be1d4b7dcea3c8bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":289},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"fb60a09cb7d44a159c30d7ec4d09c6a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1291,
              "y":297},
            "size":{
              "width":9,
              "height":7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0070d1fca4804edea57aaa035a013ed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1291,
                  "y":297},
                "size":{
                  "width":9,
                  "height":7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"007ea7b5b94f427186877749bc92a064",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":779,
              "y":330},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fbbb7445d2a448c94e5f4e1d3718232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":779,
                  "y":330},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98f417ed379f4aa78dbcb1f2529572c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":330},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b08f0a241fe4267876f39919b41c76a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":330},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"ddd7b3c8232e4fc69228e217bc3b4e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1065,
              "y":330},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"425f66506b2745a6a29ea62abe122f7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1065,
                  "y":330},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8ce63ec01e847faafa8ffd0073d86ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1156,
              "y":330},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c851cf5e935e401d8f551403e4407082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1156,
                  "y":330},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"6453f672b0db4d3fa590c350c6a13cb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1291,
              "y":340},
            "size":{
              "width":9,
              "height":7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fbbfe45ebb7432abb4ff128ffd6b7dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1291,
                  "y":340},
                "size":{
                  "width":9,
                  "height":7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"371d311577ee4552b58c435466800067",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1008,
              "y":340},
            "size":{
              "width":9,
              "height":7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7756c5a286cf4506b9a5f82e8ef0fb5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1008,
                  "y":340},
                "size":{
                  "width":9,
                  "height":7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"b0f04fe2014f4dabbbe287946a0d8d7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":779,
              "y":393},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07506ac846d84ca89b006c622fb4463c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":779,
                  "y":393},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d19cf8882624493aa80359850511212",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":779,
              "y":415},
            "size":{
              "width":551,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增商品/u52_line.png"}},
{
          "id":"3f50e78616f8418e8debedc1cfc0d81c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":779,
              "y":444},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a96812b1e3d458ca05b429db7d10745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":779,
                  "y":444},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20fc240fe16e488da22571b84a5e22ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":444},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"630c122427564900881020d85b3ebaca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":444},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"98a9bd187e6c4adfb33248573f39f22c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1070,
              "y":444},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce6d799aa7f43fab848a1b237e7d596",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1070,
                  "y":444},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a5afd1cc64840adb79e7cffb5405616",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1161,
              "y":444},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f68e2fc78e2446882a7ee8b59a93aff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1161,
                  "y":444},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"3e1a779a8c764c779364b1268cd1ee3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":779,
              "y":497},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16280bec5fe84a2881dc1da3713dfb90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":779,
                  "y":497},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e909503d373e40148170b9df9ce9c9c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":497},
            "size":{
              "width":152,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4d0ea42c4a46b4974a0c1f26e27281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":497},
                "size":{
                  "width":152,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u22.png"}},
{
          "id":"b6247fa23b8f48b1b09d20669c682447",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":779,
              "y":540},
            "size":{
              "width":731,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c26ecb4e81462caacea479be24f1c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":779,
                  "y":540},
                "size":{
                  "width":731,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u65.png"}},
{
          "id":"85c469b37fd545d2bfd14eb1575a8f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":788,
              "y":550},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc95475114f14f948beb0a2087b74d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":788,
                  "y":550},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19c4f54c4b824cdc991956fd5d75b991",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":670},
            "size":{
              "width":786,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddf69d400b914514be012fd4c2e93bbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":670},
                "size":{
                  "width":786,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u2.png"}},
{
          "id":"a8f4a34473604ca59be35582b1274fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":1355,
              "y":675},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5578e0f7277430a94cd9dfcb5d60823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":1355,
                  "y":675},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u71.png"}},
{
          "id":"d29761cebd704c3fb4763f69fafcc782",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1441,
              "y":675},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7429cbe89c304ffe8452bf557c0e8da8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1441,
                  "y":675},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增商品/u73.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "690293ff9c4042b99b2b4491a09d2e21":{
      "scriptId":"u0"},
    "a19411ccc39e4b84a588f1c55c2c43c4":{
      "scriptId":"u1"},
    "f896e1713a194e038e70c1d2a26a9cc1":{
      "scriptId":"u2"},
    "2034ddecad1f4a9ca9ab5b5f72b52a89":{
      "scriptId":"u3"},
    "23cde13c2fa74fd4ad7da2bde90e1bd5":{
      "scriptId":"u4"},
    "f2ecc72568eb48deb98333a6e3f124b6":{
      "scriptId":"u5"},
    "760631147ca34e8db11faa624854e363":{
      "scriptId":"u6"},
    "d88fc989ebc143a197d50e83b11cf3d8":{
      "scriptId":"u7"},
    "193f77f737204c3483e1e8b01d595048":{
      "scriptId":"u8"},
    "48aa1fa83d2d4301a0a8b0f017a6666d":{
      "scriptId":"u9"},
    "6902b4ba8561481093a7b7b830a55b92":{
      "scriptId":"u10"},
    "468c40408120491bac6b501ecee38be9":{
      "scriptId":"u11"},
    "6881a30d0d3043ca88a106818459f21b":{
      "scriptId":"u12"},
    "8686e2bf89d446df8cd7fbc36bc62a4a":{
      "scriptId":"u13"},
    "850de06ca94b424e9992fb8000e16707":{
      "scriptId":"u14"},
    "87c1b135b09d49eaad2fbe5dac537cdb":{
      "scriptId":"u15"},
    "c0d7b405042f440c9119d6b5591549c3":{
      "scriptId":"u16"},
    "133ddfc470194c04b3e2fb209e710c79":{
      "scriptId":"u17"},
    "687aed61fb3742cba7af40f3e2563992":{
      "scriptId":"u18"},
    "735cdbd00f164a929c538b83d037af83":{
      "scriptId":"u19"},
    "04b6db491ded4cc9ab447c1e5cdccf73":{
      "scriptId":"u20"},
    "f3426f31efa944f481eb4a47beeac4b5":{
      "scriptId":"u21"},
    "e791aef805094bed900e53006e617634":{
      "scriptId":"u22"},
    "f3af64782d464f7a8afe7f4cc199a129":{
      "scriptId":"u23"},
    "987211f8606542da88972e056d9fcbd6":{
      "scriptId":"u24"},
    "a107b0577997419199aa455523e1f5c5":{
      "scriptId":"u25"},
    "3dbf5800c8b14904bfa3d3b10b7639eb":{
      "scriptId":"u26"},
    "acd3a7efe5e84cad9a774b0da64d5eaa":{
      "scriptId":"u27"},
    "ad937f4b89b348659a1b16bc5e81a559":{
      "scriptId":"u28"},
    "d21d3541b7584018b57503b41ed25c03":{
      "scriptId":"u29"},
    "e35436c2caba4264819c4f75b6d9cd57":{
      "scriptId":"u30"},
    "ea23bc02d76847899db3e814ef442618":{
      "scriptId":"u31"},
    "0a07f4483d2b40fa935b5aeed3bc9cea":{
      "scriptId":"u32"},
    "fada14fde0294cb884344f0bec4f56b2":{
      "scriptId":"u33"},
    "50ac395817f64454875432a3759b4704":{
      "scriptId":"u34"},
    "1806452039dc4d87be1d4b7dcea3c8bc":{
      "scriptId":"u35"},
    "fb60a09cb7d44a159c30d7ec4d09c6a7":{
      "scriptId":"u36"},
    "0070d1fca4804edea57aaa035a013ed1":{
      "scriptId":"u37"},
    "007ea7b5b94f427186877749bc92a064":{
      "scriptId":"u38"},
    "1fbbb7445d2a448c94e5f4e1d3718232":{
      "scriptId":"u39"},
    "98f417ed379f4aa78dbcb1f2529572c7":{
      "scriptId":"u40"},
    "6b08f0a241fe4267876f39919b41c76a":{
      "scriptId":"u41"},
    "ddd7b3c8232e4fc69228e217bc3b4e97":{
      "scriptId":"u42"},
    "425f66506b2745a6a29ea62abe122f7a":{
      "scriptId":"u43"},
    "b8ce63ec01e847faafa8ffd0073d86ad":{
      "scriptId":"u44"},
    "c851cf5e935e401d8f551403e4407082":{
      "scriptId":"u45"},
    "6453f672b0db4d3fa590c350c6a13cb7":{
      "scriptId":"u46"},
    "0fbbfe45ebb7432abb4ff128ffd6b7dc":{
      "scriptId":"u47"},
    "371d311577ee4552b58c435466800067":{
      "scriptId":"u48"},
    "7756c5a286cf4506b9a5f82e8ef0fb5e":{
      "scriptId":"u49"},
    "b0f04fe2014f4dabbbe287946a0d8d7d":{
      "scriptId":"u50"},
    "07506ac846d84ca89b006c622fb4463c":{
      "scriptId":"u51"},
    "4d19cf8882624493aa80359850511212":{
      "scriptId":"u52"},
    "3f50e78616f8418e8debedc1cfc0d81c":{
      "scriptId":"u53"},
    "3a96812b1e3d458ca05b429db7d10745":{
      "scriptId":"u54"},
    "20fc240fe16e488da22571b84a5e22ab":{
      "scriptId":"u55"},
    "630c122427564900881020d85b3ebaca":{
      "scriptId":"u56"},
    "98a9bd187e6c4adfb33248573f39f22c":{
      "scriptId":"u57"},
    "5ce6d799aa7f43fab848a1b237e7d596":{
      "scriptId":"u58"},
    "6a5afd1cc64840adb79e7cffb5405616":{
      "scriptId":"u59"},
    "9f68e2fc78e2446882a7ee8b59a93aff":{
      "scriptId":"u60"},
    "3e1a779a8c764c779364b1268cd1ee3f":{
      "scriptId":"u61"},
    "16280bec5fe84a2881dc1da3713dfb90":{
      "scriptId":"u62"},
    "e909503d373e40148170b9df9ce9c9c2":{
      "scriptId":"u63"},
    "ec4d0ea42c4a46b4974a0c1f26e27281":{
      "scriptId":"u64"},
    "b6247fa23b8f48b1b09d20669c682447":{
      "scriptId":"u65"},
    "35c26ecb4e81462caacea479be24f1c4":{
      "scriptId":"u66"},
    "85c469b37fd545d2bfd14eb1575a8f70":{
      "scriptId":"u67"},
    "bc95475114f14f948beb0a2087b74d27":{
      "scriptId":"u68"},
    "19c4f54c4b824cdc991956fd5d75b991":{
      "scriptId":"u69"},
    "ddf69d400b914514be012fd4c2e93bbb":{
      "scriptId":"u70"},
    "a8f4a34473604ca59be35582b1274fa8":{
      "scriptId":"u71"},
    "a5578e0f7277430a94cd9dfcb5d60823":{
      "scriptId":"u72"},
    "d29761cebd704c3fb4763f69fafcc782":{
      "scriptId":"u73"},
    "7429cbe89c304ffe8452bf557c0e8da8":{
      "scriptId":"u74"}}});