$axure.loadCurrentPage({
  "url":"其他收支明细表.html",
  "generationDate":new Date(1446432611522.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7721f1e4ee7f4f8f90a6a1590330f10f",
    "type":"Axure:Page",
    "name":"其他收支明细表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f978562015494830b9f9ee6f2579c16d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-220,
              "y":40},
            "size":{
              "width":1817,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce2346ca6b64922879630e5b9245c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-220,
                  "y":40},
                "size":{
                  "width":1817,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/其他收支明细表/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f978562015494830b9f9ee6f2579c16d":{
      "scriptId":"u0"},
    "5ce2346ca6b64922879630e5b9245c06":{
      "scriptId":"u1"}}});