$axure.loadCurrentPage({
  "url":"销售汇总表（按客户）.html",
  "generationDate":new Date(1446432611256.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"24d7af2557d64668b51112548d9507ee",
    "type":"Axure:Page",
    "name":"销售汇总表（按客户）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a6a478ec44c41138846525bb8d711e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa448dd5158a410bbae469fe4e51fa2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"54a2ff3cd8cd4a76874e19b6ce12baa3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6331dee89bc24c419c6b77541ca94dd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ad6e54d23004031b519f76996808ffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45d1153bd8a4b8ea1a79678a183c31b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"bafefb8354c24b72abd0c6bea2c60fe6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"d6c462d22e88468fa02000db5c4ccbdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"220b5cef8f064e80a4f1ee29a9f4b58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f574939e2644e8285e17c35c69a19c8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"c7f2e5ed40064ba29254b9e434a0728e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673a31f62768495da6108640c5d88885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"038ef710fe3d45d89fecbcabb8ecf507",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"d6faf9361e934196bb74f1002664bc49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"856474082f7c440197aafc8280c6d0b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8022120b8fe04f519d3c83c4cc529c07",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"58e6070f64f64d59941b7530975d8dd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be079bacd3f34c08bc795caa723270a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abf680066fcc4164a67fa246bb4b3c33",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"91a040bc7c704a499bda949e079ced2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2894458d394f02b38dd92f2eed4d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"8117709c47e849e3af1090b498263d62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dee0917fd664d41a44d866a7e8630ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f33fd56410e44daca5fe49356ce5aad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da025eeb1a14aa39f782032100a2d0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"8f90e6d197cc4e4dbeb5373f1b98ee10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fadfe877f69d44e1ae027a9d143b4e08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4e32b8e1ae6416591157ebf0643626d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa47f17d6552443cb28c20a65469e0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f42a4c7150a24defab33229e945cffc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5801e00bdb384010922e9e3e30fafe0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"fded758f669d42d892506daffb25aa0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21ac2c2b48144025bb04f64b969be55b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0503c3b4331d4370a6235309527def36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"567ad8f0a20241dfbcef4cb940959579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"aa8d35dabc2b473e8ebda8fbece012e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8142ef219754dcf9bf9dbbfb8f5ed3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"6470420a8a614c42b1bbca6a9fe18dd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9fc4c9f2e3e4ed0ab5692bcfb3dd12a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"9bb1cbfb696c40949ead2e32e6ad35bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fa7f471dd9741fb86234e28f6abeada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"445812473f134306b1b380c36692799f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d10ba1a77a646e7bfdd2d89f0f092ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"d8b652ccf8684731ba9ea9663bb319c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c9fab3349bd49f5944d69fe82234724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"2d27d0f2b78e4a7c94652127ea6392ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e419f30c81401bbc7dc06436c92a70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"405eb4e3c29541e092f88a9f9a675286",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e68381572ddb44018cdc0c91ac7ff083",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de4e0941fc7547ee8a4869429a1b6339",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fdeffb5f2d24ed69b6944a1d0ffb577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77caa00ff5bf45da9ebfd7cd1c963880",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0089a44e507940ee8b26d9299a0f5511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30183ae58f104462af66bd875cb61076",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ba241d847674795bc89d9b19e64e277",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e736fa28ff394e6a84dba13b77f202ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5942a8965fb426f97b17f5020e1315a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bee1e5a66624ffc85ae8ceb865d076f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab8da85e2024e2cb5a72ce423dc537f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb675bcfc53b4ca5a73f7f4b4fedde57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fa312a1b72c4dbc9df6a5f39f581014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"d4320b27d4be4407b5a2b1fd5d6051b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6d503e465ab4bc6bedfee1df0132f2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"ec2dfff1a41344939bfd240a10e04860",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4be70d8242474fb03d326ec66e057a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"6d34cc1f861a47328f75eb20ffd08765",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e137fe11f426434c94ab82f169d3e070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"de9d79be54da4761bc17ef5ef8068162",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":345,
              "y":134},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b325033e40d469fb0c33da0a0316954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":345,
                  "y":134},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0fd905877454df2b4cb4e38c455762c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":258},
            "size":{
              "width":1766,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e83e0c953b4b486688fa6dc54713537c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":258},
                "size":{
                  "width":1766,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u69.png"}},
{
          "id":"0165504b270848c8b07e807a6093e2ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cfb9867a5284e67b94dd57d979acbbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00d653bd8c254818a5b79efeb25544cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":252,
              "y":195},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"254306159211417d8b8bb6471e91ef38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":252,
                  "y":195},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5abba47af01c47ce9036e69063e950c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":195},
            "size":{
              "width":200,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aacecedc4c646cd97ffb5e720559662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":195},
                "size":{
                  "width":200,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u77.png"}},
{
          "id":"fd317541e87848edbaee37a5ace431f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":194},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b464a02b003445d99218c31cae45ed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":194},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u81.png"}},
{
          "id":"ebf1cee5f6ea41bab5a5836f4edcb5e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":199},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fe43694fda44ee9a386059db4020788",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":199},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u83.png"}},
{
          "id":"231de99c61ec4d5fbf192888cc483ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1082,
              "y":273},
            "size":{
              "width":221,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdfa6d34d4d944718a0cac31e8b39489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1082,
                  "y":273},
                "size":{
                  "width":221,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5eb51210b694e0ba64da1d6aaf4bf3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":354},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40bec51c56b74853ac5a073f52dde66b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":354},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"0b236de7eccf4833b5d573b8b561446f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":399},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386799e1d1614009a70cd33544b822b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":399},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"4baef90c3cfc49bdba31ef89a5a02d65",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"660dc81795e24ac1a79e451f9944a64b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":309,
              "y":365},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"719ac4939a1d4561bc6e4cab4566e80b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":309,
                  "y":365},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e44c8bffec94d7a99a7806397e1117d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"29ad671600bb4515bb68ec7019f26549",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":905,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"0c4057403f334fd0b037ed21ec2ffbb7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":985,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"51106b78174a411c9f167c154816272d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"62d53773f2504943b7749a35a9dd1192",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"43aec88159684e81a1683aa524f1c4f5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"79dce3c5ba7b4db98686fa7dad3bc02b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":579,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e087225f67e046499ed7289775f2a614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":579,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7d9d143e570475da81e9c4df3651458",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":750,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"062ad16056eb48f58717fb6f405ee8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":750,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a4f94b2542d4afaba1bc6838ed5bfd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":928,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25d394965b4e4491adbf0191ebfcac24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":928,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1d66f200b0f4898b3271ecaad6ebac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64905ce8233d43859c4b9abe3da69389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c0e817dc2874c33a834668db00ae6eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1116,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15db0945822646f9965649b09e925d3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1116,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"839bc627eeed45958d050b1b513534bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1225,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4514b7d2cbcc4a0eb5ad4e36e171cc35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1225,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94e8d947abec4761b617f0304e26f519",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"969cca5bff5a412a85d9107d2dc38502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"301dd040790e4ffba3bb2d94a92794e2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"72008dc83e9a4893a2ccc7662e9a39f2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"91478a7dfbe242a1ab014ed7fa80f131",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"2f1780665ed947ccb154e0ba949ec843",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1003,
              "y":410},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cbbb9af4bcc4fc4b02a02c7e1746be0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1003,
                  "y":410},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e157a03052464d2dbb5e977dadd6358f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":289,
              "y":325},
            "size":{
              "width":209,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa3e6f2d4e04fb8a6eed368ecbcfbe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":289,
                  "y":325},
                "size":{
                  "width":209,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6ef4c53ef374ac6aad83e767116b2fa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520.30773925781,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"45f8b927afcb486b96d82346e4c055ee",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"d4efc767218a40c981d8cb084cc58144",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":650},
            "size":{
              "width":1810,
              "height":650}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330aea7c28254ba6830cea7a9dea796c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":650},
                "size":{
                  "width":1810,
                  "height":650}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/销售汇总表（按客户）/u119.png"}},
{
          "id":"1b15d4854f10405eb40ce706a7572d58",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":362.307647705078,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"909e426084fd46b0b30057e198fed179",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":417,
              "y":365},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b01e6598a44170bbd6a03eb1b69222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":417,
                  "y":365},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76a68123544244e4b15880a4241033eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF449513},
            "location":{
              "x":1806,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a478816dbd84c3880e755bc19bd3d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF449513},
                "location":{
                  "x":1806,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u129.png"}},
{
          "id":"5e37f0469b3045f39eb2390b68747683",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1920,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b0422720ba44b0ab3a6fc00b67aba4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1920,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u131.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8a6a478ec44c41138846525bb8d711e9":{
      "scriptId":"u0"},
    "aa448dd5158a410bbae469fe4e51fa2d":{
      "scriptId":"u1"},
    "54a2ff3cd8cd4a76874e19b6ce12baa3":{
      "scriptId":"u2"},
    "6331dee89bc24c419c6b77541ca94dd2":{
      "scriptId":"u3"},
    "5ad6e54d23004031b519f76996808ffd":{
      "scriptId":"u4"},
    "b45d1153bd8a4b8ea1a79678a183c31b":{
      "scriptId":"u5"},
    "bafefb8354c24b72abd0c6bea2c60fe6":{
      "scriptId":"u6"},
    "d6c462d22e88468fa02000db5c4ccbdc":{
      "scriptId":"u7"},
    "220b5cef8f064e80a4f1ee29a9f4b58d":{
      "scriptId":"u8"},
    "3f574939e2644e8285e17c35c69a19c8":{
      "scriptId":"u9"},
    "c7f2e5ed40064ba29254b9e434a0728e":{
      "scriptId":"u10"},
    "673a31f62768495da6108640c5d88885":{
      "scriptId":"u11"},
    "038ef710fe3d45d89fecbcabb8ecf507":{
      "scriptId":"u12"},
    "d6faf9361e934196bb74f1002664bc49":{
      "scriptId":"u13"},
    "856474082f7c440197aafc8280c6d0b1":{
      "scriptId":"u14"},
    "8022120b8fe04f519d3c83c4cc529c07":{
      "scriptId":"u15"},
    "58e6070f64f64d59941b7530975d8dd3":{
      "scriptId":"u16"},
    "be079bacd3f34c08bc795caa723270a1":{
      "scriptId":"u17"},
    "abf680066fcc4164a67fa246bb4b3c33":{
      "scriptId":"u18"},
    "91a040bc7c704a499bda949e079ced2a":{
      "scriptId":"u19"},
    "4e2894458d394f02b38dd92f2eed4d1d":{
      "scriptId":"u20"},
    "8117709c47e849e3af1090b498263d62":{
      "scriptId":"u21"},
    "5dee0917fd664d41a44d866a7e8630ea":{
      "scriptId":"u22"},
    "f33fd56410e44daca5fe49356ce5aad0":{
      "scriptId":"u23"},
    "3da025eeb1a14aa39f782032100a2d0a":{
      "scriptId":"u24"},
    "8f90e6d197cc4e4dbeb5373f1b98ee10":{
      "scriptId":"u25"},
    "fadfe877f69d44e1ae027a9d143b4e08":{
      "scriptId":"u26"},
    "c4e32b8e1ae6416591157ebf0643626d":{
      "scriptId":"u27"},
    "aa47f17d6552443cb28c20a65469e0cd":{
      "scriptId":"u28"},
    "f42a4c7150a24defab33229e945cffc0":{
      "scriptId":"u29"},
    "5801e00bdb384010922e9e3e30fafe0a":{
      "scriptId":"u30"},
    "fded758f669d42d892506daffb25aa0a":{
      "scriptId":"u31"},
    "21ac2c2b48144025bb04f64b969be55b":{
      "scriptId":"u32"},
    "0503c3b4331d4370a6235309527def36":{
      "scriptId":"u33"},
    "567ad8f0a20241dfbcef4cb940959579":{
      "scriptId":"u34"},
    "aa8d35dabc2b473e8ebda8fbece012e3":{
      "scriptId":"u35"},
    "a8142ef219754dcf9bf9dbbfb8f5ed3c":{
      "scriptId":"u36"},
    "6470420a8a614c42b1bbca6a9fe18dd9":{
      "scriptId":"u37"},
    "a9fc4c9f2e3e4ed0ab5692bcfb3dd12a":{
      "scriptId":"u38"},
    "9bb1cbfb696c40949ead2e32e6ad35bd":{
      "scriptId":"u39"},
    "6fa7f471dd9741fb86234e28f6abeada":{
      "scriptId":"u40"},
    "445812473f134306b1b380c36692799f":{
      "scriptId":"u41"},
    "9d10ba1a77a646e7bfdd2d89f0f092ec":{
      "scriptId":"u42"},
    "d8b652ccf8684731ba9ea9663bb319c5":{
      "scriptId":"u43"},
    "6c9fab3349bd49f5944d69fe82234724":{
      "scriptId":"u44"},
    "2d27d0f2b78e4a7c94652127ea6392ce":{
      "scriptId":"u45"},
    "a9e419f30c81401bbc7dc06436c92a70":{
      "scriptId":"u46"},
    "405eb4e3c29541e092f88a9f9a675286":{
      "scriptId":"u47"},
    "e68381572ddb44018cdc0c91ac7ff083":{
      "scriptId":"u48"},
    "de4e0941fc7547ee8a4869429a1b6339":{
      "scriptId":"u49"},
    "1fdeffb5f2d24ed69b6944a1d0ffb577":{
      "scriptId":"u50"},
    "77caa00ff5bf45da9ebfd7cd1c963880":{
      "scriptId":"u51"},
    "0089a44e507940ee8b26d9299a0f5511":{
      "scriptId":"u52"},
    "30183ae58f104462af66bd875cb61076":{
      "scriptId":"u53"},
    "0ba241d847674795bc89d9b19e64e277":{
      "scriptId":"u54"},
    "e736fa28ff394e6a84dba13b77f202ec":{
      "scriptId":"u55"},
    "d5942a8965fb426f97b17f5020e1315a":{
      "scriptId":"u56"},
    "8bee1e5a66624ffc85ae8ceb865d076f":{
      "scriptId":"u57"},
    "eab8da85e2024e2cb5a72ce423dc537f":{
      "scriptId":"u58"},
    "bb675bcfc53b4ca5a73f7f4b4fedde57":{
      "scriptId":"u59"},
    "3fa312a1b72c4dbc9df6a5f39f581014":{
      "scriptId":"u60"},
    "d4320b27d4be4407b5a2b1fd5d6051b2":{
      "scriptId":"u61"},
    "c6d503e465ab4bc6bedfee1df0132f2f":{
      "scriptId":"u62"},
    "ec2dfff1a41344939bfd240a10e04860":{
      "scriptId":"u63"},
    "8d4be70d8242474fb03d326ec66e057a":{
      "scriptId":"u64"},
    "6d34cc1f861a47328f75eb20ffd08765":{
      "scriptId":"u65"},
    "e137fe11f426434c94ab82f169d3e070":{
      "scriptId":"u66"},
    "de9d79be54da4761bc17ef5ef8068162":{
      "scriptId":"u67"},
    "2b325033e40d469fb0c33da0a0316954":{
      "scriptId":"u68"},
    "b0fd905877454df2b4cb4e38c455762c":{
      "scriptId":"u69"},
    "e83e0c953b4b486688fa6dc54713537c":{
      "scriptId":"u70"},
    "0165504b270848c8b07e807a6093e2ef":{
      "scriptId":"u71"},
    "4cfb9867a5284e67b94dd57d979acbbc":{
      "scriptId":"u72"},
    "00d653bd8c254818a5b79efeb25544cd":{
      "scriptId":"u73"},
    "254306159211417d8b8bb6471e91ef38":{
      "scriptId":"u74"},
    "5abba47af01c47ce9036e69063e950c5":{
      "scriptId":"u75"},
    "9aacecedc4c646cd97ffb5e720559662":{
      "scriptId":"u76"},
    "fd317541e87848edbaee37a5ace431f6":{
      "scriptId":"u77"},
    "1b464a02b003445d99218c31cae45ed8":{
      "scriptId":"u78"},
    "ebf1cee5f6ea41bab5a5836f4edcb5e1":{
      "scriptId":"u79"},
    "1fe43694fda44ee9a386059db4020788":{
      "scriptId":"u80"},
    "231de99c61ec4d5fbf192888cc483ab9":{
      "scriptId":"u81"},
    "cdfa6d34d4d944718a0cac31e8b39489":{
      "scriptId":"u82"},
    "a5eb51210b694e0ba64da1d6aaf4bf3d":{
      "scriptId":"u83"},
    "40bec51c56b74853ac5a073f52dde66b":{
      "scriptId":"u84"},
    "0b236de7eccf4833b5d573b8b561446f":{
      "scriptId":"u85"},
    "386799e1d1614009a70cd33544b822b9":{
      "scriptId":"u86"},
    "4baef90c3cfc49bdba31ef89a5a02d65":{
      "scriptId":"u87"},
    "660dc81795e24ac1a79e451f9944a64b":{
      "scriptId":"u88"},
    "719ac4939a1d4561bc6e4cab4566e80b":{
      "scriptId":"u89"},
    "8e44c8bffec94d7a99a7806397e1117d":{
      "scriptId":"u90"},
    "29ad671600bb4515bb68ec7019f26549":{
      "scriptId":"u91"},
    "0c4057403f334fd0b037ed21ec2ffbb7":{
      "scriptId":"u92"},
    "51106b78174a411c9f167c154816272d":{
      "scriptId":"u93"},
    "62d53773f2504943b7749a35a9dd1192":{
      "scriptId":"u94"},
    "43aec88159684e81a1683aa524f1c4f5":{
      "scriptId":"u95"},
    "79dce3c5ba7b4db98686fa7dad3bc02b":{
      "scriptId":"u96"},
    "e087225f67e046499ed7289775f2a614":{
      "scriptId":"u97"},
    "b7d9d143e570475da81e9c4df3651458":{
      "scriptId":"u98"},
    "062ad16056eb48f58717fb6f405ee8c4":{
      "scriptId":"u99"},
    "4a4f94b2542d4afaba1bc6838ed5bfd0":{
      "scriptId":"u100"},
    "25d394965b4e4491adbf0191ebfcac24":{
      "scriptId":"u101"},
    "c1d66f200b0f4898b3271ecaad6ebac3":{
      "scriptId":"u102"},
    "64905ce8233d43859c4b9abe3da69389":{
      "scriptId":"u103"},
    "1c0e817dc2874c33a834668db00ae6eb":{
      "scriptId":"u104"},
    "15db0945822646f9965649b09e925d3a":{
      "scriptId":"u105"},
    "839bc627eeed45958d050b1b513534bc":{
      "scriptId":"u106"},
    "4514b7d2cbcc4a0eb5ad4e36e171cc35":{
      "scriptId":"u107"},
    "94e8d947abec4761b617f0304e26f519":{
      "scriptId":"u108"},
    "969cca5bff5a412a85d9107d2dc38502":{
      "scriptId":"u109"},
    "301dd040790e4ffba3bb2d94a92794e2":{
      "scriptId":"u110"},
    "72008dc83e9a4893a2ccc7662e9a39f2":{
      "scriptId":"u111"},
    "91478a7dfbe242a1ab014ed7fa80f131":{
      "scriptId":"u112"},
    "2f1780665ed947ccb154e0ba949ec843":{
      "scriptId":"u113"},
    "5cbbb9af4bcc4fc4b02a02c7e1746be0":{
      "scriptId":"u114"},
    "e157a03052464d2dbb5e977dadd6358f":{
      "scriptId":"u115"},
    "0aa3e6f2d4e04fb8a6eed368ecbcfbe6":{
      "scriptId":"u116"},
    "b6ef4c53ef374ac6aad83e767116b2fa":{
      "scriptId":"u117"},
    "45f8b927afcb486b96d82346e4c055ee":{
      "scriptId":"u118"},
    "d4efc767218a40c981d8cb084cc58144":{
      "scriptId":"u119"},
    "330aea7c28254ba6830cea7a9dea796c":{
      "scriptId":"u120"},
    "1b15d4854f10405eb40ce706a7572d58":{
      "scriptId":"u121"},
    "909e426084fd46b0b30057e198fed179":{
      "scriptId":"u122"},
    "e9b01e6598a44170bbd6a03eb1b69222":{
      "scriptId":"u123"},
    "76a68123544244e4b15880a4241033eb":{
      "scriptId":"u124"},
    "9a478816dbd84c3880e755bc19bd3d88":{
      "scriptId":"u125"},
    "5e37f0469b3045f39eb2390b68747683":{
      "scriptId":"u126"},
    "2b0422720ba44b0ab3a6fc00b67aba4d":{
      "scriptId":"u127"}}});