$axure.loadCurrentPage({
  "url":"新增结算方式.html",
  "generationDate":new Date(1446432607575.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"601dcca308764ccdb44935cf2060c407",
    "type":"Axure:Page",
    "name":"新增结算方式",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f28e2ddfb00f492e85b239f7bb1f17f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":252}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ddba53703b417d9df2e7f9fc13e5db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":252}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u0.png"}},
{
          "id":"55271e2778ed4065a62d27ba520d6cde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f98a6d57d44b41bda049ca49460506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u2.png"}},
{
          "id":"2684f42f5c834bc8b7d04a1b75fcde1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":385,
              "y":56},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a839930f2b8d4f35bca38dea2502ed7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":385,
                  "y":56},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60f420b1907f449fb08c7a6621d317e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":728,
              "y":53},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5332e03d2a50454294cccd1b95803582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":728,
                  "y":53},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca31208e055f4a4aba7d4ef131db5fc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":270},
            "size":{
              "width":360,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bad2193f31240f5aacb8c61835fb83c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":270},
                "size":{
                  "width":360,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u8.png"}},
{
          "id":"96f0277a14f74f759fb27221cf4de082",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":630,
              "y":274},
            "size":{
              "width":52,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f277ba62feba4f31a332ac7083c4c050",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":630,
                  "y":274},
                "size":{
                  "width":52,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u10.png"}},
{
          "id":"a9202c2cb5904cdb9aad51a8107305f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":692,
              "y":274},
            "size":{
              "width":38,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbce8aa469fb49e690c76aedfbd0bf90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":692,
                  "y":274},
                "size":{
                  "width":38,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u12.png"}},
{
          "id":"09ff1ece7fc043cbb5385ff702fcb0d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":170},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994780ec41374599819b228f1fae0035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":170},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a594c2ede74600a3a0f6ad116eb772",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":165},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d9c1b578e794d2794bb897de60c6c5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":165},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f28e2ddfb00f492e85b239f7bb1f17f5":{
      "scriptId":"u0"},
    "89ddba53703b417d9df2e7f9fc13e5db":{
      "scriptId":"u1"},
    "55271e2778ed4065a62d27ba520d6cde":{
      "scriptId":"u2"},
    "16f98a6d57d44b41bda049ca49460506":{
      "scriptId":"u3"},
    "2684f42f5c834bc8b7d04a1b75fcde1e":{
      "scriptId":"u4"},
    "a839930f2b8d4f35bca38dea2502ed7a":{
      "scriptId":"u5"},
    "60f420b1907f449fb08c7a6621d317e2":{
      "scriptId":"u6"},
    "5332e03d2a50454294cccd1b95803582":{
      "scriptId":"u7"},
    "ca31208e055f4a4aba7d4ef131db5fc8":{
      "scriptId":"u8"},
    "5bad2193f31240f5aacb8c61835fb83c":{
      "scriptId":"u9"},
    "96f0277a14f74f759fb27221cf4de082":{
      "scriptId":"u10"},
    "f277ba62feba4f31a332ac7083c4c050":{
      "scriptId":"u11"},
    "a9202c2cb5904cdb9aad51a8107305f3":{
      "scriptId":"u12"},
    "bbce8aa469fb49e690c76aedfbd0bf90":{
      "scriptId":"u13"},
    "09ff1ece7fc043cbb5385ff702fcb0d4":{
      "scriptId":"u14"},
    "994780ec41374599819b228f1fae0035":{
      "scriptId":"u15"},
    "25a594c2ede74600a3a0f6ad116eb772":{
      "scriptId":"u16"},
    "2d9c1b578e794d2794bb897de60c6c5d":{
      "scriptId":"u17"}}});