$axure.loadCurrentPage({
  "url":"基础参数.html",
  "generationDate":new Date(1446432611743.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8513b620bd7b46bab61f6be5803e8a2e",
    "type":"Axure:Page",
    "name":"基础参数",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38e737e58df044a8bbd068b1faa62445",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bab66445cfc4b4fbbb5a411eb9cd0e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"c7b8048042874754a3171788a9be3ff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":250,
              "y":76},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"525165e476c84e5fa87051fe25ca22dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":250,
                  "y":76},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85e07056c1604bbb87b0935e0088bb7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1310,
              "y":78},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed57b69c57a745a3ba2b982b7b5271a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1310,
                  "y":78},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"919f7c4f122944828e5a114a9eabc3e4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1373,
              "y":78},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"74da5ef6948d4e2095c575af0832b462",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1396,
              "y":76},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e623c28175a4082a95e2276085fa869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1396,
                  "y":76},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76fa1cb9d8ad4bd489c3c718a05b6868",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1570,
              "y":78},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"fa8f47bab6d042ad83fb92b2d5ef2615",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1590,
              "y":76},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a000777aa4426f918fb3b1f0ca925e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1590,
                  "y":76},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc9d9295f652403ca65308eb7f23b6c7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1780,
              "y":76},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"fe6d920cf85e47659ce4fc641c1b173a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1801,
              "y":76},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb99a8c9a6147b9af2ecb1c13907a19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1801,
                  "y":76},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d02206f151a1440a885725815b4341bf",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1884,
              "y":76},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"5196a25e54c14f6aba28f729e2e7e894",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1908,
              "y":76},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"771e4f08233d4e06b68ac9f326e8be9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1908,
                  "y":76},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01573e908a044dc9876b4df93f157f32",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1954,
              "y":76},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"96b5009d6307468ab84bb71325017012",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1978,
              "y":76},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235a4431a1ca47d691c8ea6c41c7bd9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1978,
                  "y":76},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"da3161479f7f49e591bba63ea6fad9e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":253,
              "y":173},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fef7b7073bd4b74ade290280bc46005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":253,
                  "y":173},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79ea7e53481f4a2196cdffd71548419f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":137},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99866762ce8d48c48c11ff2a8d162b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":137},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"3e038aa0afef4daf9da1c5b31708612b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":278,
              "y":142},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ef155e4409645c4b93a26cf89dc417f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":278,
                  "y":142},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf6118216bb44d9aa979bd6073d15e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":441,
              "y":171},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79ce284f95047b8975e2799f3d6542b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":441,
                  "y":171},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0f8cc8b81dd4197904eacad8bf7039e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":172},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"359fd550b9754387ba93e86349742a96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":172},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"2211b74f0eb540a2a00afc0b57f2857a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1733,
              "y":174},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fd086e20fca4c828f54cdcbb060b16d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1733,
                  "y":174},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77d609c123864826ad4994e5827abacb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1816,
              "y":171},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acf2769e1c5944e88f89c9e5e3210c31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1816,
                  "y":171},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"95118f8ae57b4968b4061bd4e84d4b95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1995,
              "y":176},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"127f22c2208f4a619cb2f0f432bc259e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1995,
                  "y":176},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"f95a969d1427430b92bca026a6b64cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1765,
              "y":778},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ba9a10e410e4debb1d9d60510548137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1765,
                  "y":778},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"698f54fc40b142c0ab30962e17659d10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1810,
              "y":837},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce61acdc64f84745bd1008eccb4f36db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1810,
                  "y":837},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76917501a098418a8ee0a20d94872aa2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1772,
              "y":804},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0657ccf53d242e7b5b8838203ce8d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1772,
                  "y":804},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"33eb8b3efc4c425eae878963a18cf1d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cef9aea4f8c4362ba76b33c1f452301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"85bde3588c394f6890ae50fa30f0a990",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":146},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2342ab3023074785b1f6ccf92d716497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":146},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d776ad68ef9645188600c37b9b76565d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":268},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f3906819caa48fc860b57ebd60f54fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":268},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"561170bf53654b0db516a535658ee622",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":396},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26292b76bd294725b6d697f5285fd663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":396},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"580d80a068de41c4a444eb3defaff34c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":524},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38209683814b4cafb955c7e7ed408501",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":524},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8772c91e6635425e96b3e033912b40d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":650},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad726e31c57a4fc19ea38be91ec4ca4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":650},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cd5f7f94794472080310f9b23454954",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":767},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff3625d4273463db9c118881b5b9caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":767},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d1c7dc6e14e40b5bd776a00c14a2c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":147,
              "y":874},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aea1928179b4feda002ce4050168bb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":874},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0afd9f60df244fb4953c4ee2d7f8b6a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":229,
              "y":171},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8978e95ffa4a1494ead77129bf42d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":229,
                  "y":171},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"a9e9258e1c7e4bdbbdb6b9c2cbec9790",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":339,
              "y":127},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d5bd3adba6d4266afc0172ce811995c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":339,
                  "y":127},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"35752fc219f74e6baa63793bb680b8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":137},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f378dfabb61547918ee1a8487af3fd53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":137},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"6f692febd9b84133b18b6c24112b87db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":149},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32e2db820abe4b9cb217e2e8db16eea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":149},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"e8996836de904bf1928aca6fe8f722b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":357,
              "y":143},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd866d122ba64283aee60c8750f8d30d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":357,
                  "y":143},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7515223d57484c05880c0c0086026e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":439,
              "y":121},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f444e40a0c440fe937d7dd37a027bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":439,
                  "y":121},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"905c886bc48049efa70e90045c14b2f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":196},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa719d4d92504b52af865fe9f2fb87f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":196},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a76552bd709434897641a98b52fdc36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1795,
              "y":184},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3afc831ceb4b4e0e99642b19755e64a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1795,
                  "y":184},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"53aac1859003448d8e74e6df1f9a640f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1920,
              "y":184},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"036ef09cc5c346bcbeefeafb9b12dbef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1920,
                  "y":184},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"115ed04ec4564148bd099f4a989dfb2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":268},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"588fbe7d5e8c425faaa0353e58491005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":268},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7489cbdccb845039c93f7334e5abd1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":480,
              "y":268},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1c99ee21f3340bd819a45825ecba470",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":480,
                  "y":268},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"6f88e7cb7a754420b9e7c123ae6b76c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":333},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a4b55d96064598b66a5cdb95682907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":333},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d9a91a719cd43279f7ea8b4fe01be0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":480,
              "y":333},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"064fa3f6ec3c42b79a35d2890f1bbb13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":480,
                  "y":333},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"9c7e4bd0baa843c2be9e6927577d7bfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":408},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f13f8abe474d40beaefcd52fe19bf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":408},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c14630c9b124d00b3f8fbebedbdd912",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":480,
              "y":408},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f510a497bf14a5d82f9b31c413db7d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":480,
                  "y":408},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"4007d59e1136479885210e612aefdc05",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":479},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d63c939ff3a04e21ad180bcd9027a036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":479},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"401316f847394ac58c2aa1ed67fce292",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":480,
              "y":479},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e655d6dd32cc410d8201cd4d614f1e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":480,
                  "y":479},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"aaca4812242c488586e70d316dc01a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":553},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c31a6f4d579413aa861558d6e13d090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":553},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e09423f01344755a06c1b873805c7af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":480,
              "y":553},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01c4894962d14d01b00dc547a0851980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":480,
                  "y":553},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"ad098d91e2ae46a7b5e5c86a2a1f6149",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":634},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76bd66b292a34b18b8caed49ccb0d823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":634},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"424d80bec561466ba9ec52522c1e6950",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":480,
              "y":634},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae512e9937d24b5089c2d6c239a48338",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":480,
                  "y":634},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u99.png"}},
{
          "id":"8763b69ccbd24338b507d012a63c960d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":253,
              "y":704},
            "size":{
              "width":115,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1910839740c94de4adee48cc0b93fbe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":253,
                  "y":704},
                "size":{
                  "width":115,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea1c846da79e47cca1bcdb8e83acf1e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":480,
              "y":704},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4915517dc2a544e5b447fcd39ed4c29e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":480,
                  "y":704},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u99.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "38e737e58df044a8bbd068b1faa62445":{
      "scriptId":"u0"},
    "4bab66445cfc4b4fbbb5a411eb9cd0e8":{
      "scriptId":"u1"},
    "c7b8048042874754a3171788a9be3ff3":{
      "scriptId":"u2"},
    "525165e476c84e5fa87051fe25ca22dc":{
      "scriptId":"u3"},
    "85e07056c1604bbb87b0935e0088bb7f":{
      "scriptId":"u4"},
    "ed57b69c57a745a3ba2b982b7b5271a2":{
      "scriptId":"u5"},
    "919f7c4f122944828e5a114a9eabc3e4":{
      "scriptId":"u6"},
    "74da5ef6948d4e2095c575af0832b462":{
      "scriptId":"u7"},
    "0e623c28175a4082a95e2276085fa869":{
      "scriptId":"u8"},
    "76fa1cb9d8ad4bd489c3c718a05b6868":{
      "scriptId":"u9"},
    "fa8f47bab6d042ad83fb92b2d5ef2615":{
      "scriptId":"u10"},
    "f4a000777aa4426f918fb3b1f0ca925e":{
      "scriptId":"u11"},
    "fc9d9295f652403ca65308eb7f23b6c7":{
      "scriptId":"u12"},
    "fe6d920cf85e47659ce4fc641c1b173a":{
      "scriptId":"u13"},
    "6fb99a8c9a6147b9af2ecb1c13907a19":{
      "scriptId":"u14"},
    "d02206f151a1440a885725815b4341bf":{
      "scriptId":"u15"},
    "5196a25e54c14f6aba28f729e2e7e894":{
      "scriptId":"u16"},
    "771e4f08233d4e06b68ac9f326e8be9b":{
      "scriptId":"u17"},
    "01573e908a044dc9876b4df93f157f32":{
      "scriptId":"u18"},
    "96b5009d6307468ab84bb71325017012":{
      "scriptId":"u19"},
    "235a4431a1ca47d691c8ea6c41c7bd9a":{
      "scriptId":"u20"},
    "da3161479f7f49e591bba63ea6fad9e0":{
      "scriptId":"u21"},
    "6fef7b7073bd4b74ade290280bc46005":{
      "scriptId":"u22"},
    "79ea7e53481f4a2196cdffd71548419f":{
      "scriptId":"u23"},
    "99866762ce8d48c48c11ff2a8d162b64":{
      "scriptId":"u24"},
    "3e038aa0afef4daf9da1c5b31708612b":{
      "scriptId":"u25"},
    "5ef155e4409645c4b93a26cf89dc417f":{
      "scriptId":"u26"},
    "bf6118216bb44d9aa979bd6073d15e43":{
      "scriptId":"u27"},
    "e79ce284f95047b8975e2799f3d6542b":{
      "scriptId":"u28"},
    "e0f8cc8b81dd4197904eacad8bf7039e":{
      "scriptId":"u29"},
    "359fd550b9754387ba93e86349742a96":{
      "scriptId":"u30"},
    "2211b74f0eb540a2a00afc0b57f2857a":{
      "scriptId":"u31"},
    "7fd086e20fca4c828f54cdcbb060b16d":{
      "scriptId":"u32"},
    "77d609c123864826ad4994e5827abacb":{
      "scriptId":"u33"},
    "acf2769e1c5944e88f89c9e5e3210c31":{
      "scriptId":"u34"},
    "95118f8ae57b4968b4061bd4e84d4b95":{
      "scriptId":"u35"},
    "127f22c2208f4a619cb2f0f432bc259e":{
      "scriptId":"u36"},
    "f95a969d1427430b92bca026a6b64cdd":{
      "scriptId":"u37"},
    "4ba9a10e410e4debb1d9d60510548137":{
      "scriptId":"u38"},
    "698f54fc40b142c0ab30962e17659d10":{
      "scriptId":"u39"},
    "ce61acdc64f84745bd1008eccb4f36db":{
      "scriptId":"u40"},
    "76917501a098418a8ee0a20d94872aa2":{
      "scriptId":"u41"},
    "b0657ccf53d242e7b5b8838203ce8d39":{
      "scriptId":"u42"},
    "33eb8b3efc4c425eae878963a18cf1d9":{
      "scriptId":"u43"},
    "5cef9aea4f8c4362ba76b33c1f452301":{
      "scriptId":"u44"},
    "85bde3588c394f6890ae50fa30f0a990":{
      "scriptId":"u45"},
    "2342ab3023074785b1f6ccf92d716497":{
      "scriptId":"u46"},
    "d776ad68ef9645188600c37b9b76565d":{
      "scriptId":"u47"},
    "8f3906819caa48fc860b57ebd60f54fa":{
      "scriptId":"u48"},
    "561170bf53654b0db516a535658ee622":{
      "scriptId":"u49"},
    "26292b76bd294725b6d697f5285fd663":{
      "scriptId":"u50"},
    "580d80a068de41c4a444eb3defaff34c":{
      "scriptId":"u51"},
    "38209683814b4cafb955c7e7ed408501":{
      "scriptId":"u52"},
    "8772c91e6635425e96b3e033912b40d6":{
      "scriptId":"u53"},
    "ad726e31c57a4fc19ea38be91ec4ca4d":{
      "scriptId":"u54"},
    "2cd5f7f94794472080310f9b23454954":{
      "scriptId":"u55"},
    "6ff3625d4273463db9c118881b5b9caa":{
      "scriptId":"u56"},
    "5d1c7dc6e14e40b5bd776a00c14a2c94":{
      "scriptId":"u57"},
    "9aea1928179b4feda002ce4050168bb4":{
      "scriptId":"u58"},
    "0afd9f60df244fb4953c4ee2d7f8b6a2":{
      "scriptId":"u59"},
    "da8978e95ffa4a1494ead77129bf42d3":{
      "scriptId":"u60"},
    "a9e9258e1c7e4bdbbdb6b9c2cbec9790":{
      "scriptId":"u61"},
    "4d5bd3adba6d4266afc0172ce811995c":{
      "scriptId":"u62"},
    "35752fc219f74e6baa63793bb680b8d9":{
      "scriptId":"u63"},
    "f378dfabb61547918ee1a8487af3fd53":{
      "scriptId":"u64"},
    "6f692febd9b84133b18b6c24112b87db":{
      "scriptId":"u65"},
    "32e2db820abe4b9cb217e2e8db16eea0":{
      "scriptId":"u66"},
    "e8996836de904bf1928aca6fe8f722b0":{
      "scriptId":"u67"},
    "fd866d122ba64283aee60c8750f8d30d":{
      "scriptId":"u68"},
    "7515223d57484c05880c0c0086026e1a":{
      "scriptId":"u69"},
    "3f444e40a0c440fe937d7dd37a027bce":{
      "scriptId":"u70"},
    "905c886bc48049efa70e90045c14b2f2":{
      "scriptId":"u71"},
    "aa719d4d92504b52af865fe9f2fb87f1":{
      "scriptId":"u72"},
    "2a76552bd709434897641a98b52fdc36":{
      "scriptId":"u73"},
    "3afc831ceb4b4e0e99642b19755e64a5":{
      "scriptId":"u74"},
    "53aac1859003448d8e74e6df1f9a640f":{
      "scriptId":"u75"},
    "036ef09cc5c346bcbeefeafb9b12dbef":{
      "scriptId":"u76"},
    "115ed04ec4564148bd099f4a989dfb2c":{
      "scriptId":"u77"},
    "588fbe7d5e8c425faaa0353e58491005":{
      "scriptId":"u78"},
    "e7489cbdccb845039c93f7334e5abd1a":{
      "scriptId":"u79"},
    "a1c99ee21f3340bd819a45825ecba470":{
      "scriptId":"u80"},
    "6f88e7cb7a754420b9e7c123ae6b76c9":{
      "scriptId":"u81"},
    "76a4b55d96064598b66a5cdb95682907":{
      "scriptId":"u82"},
    "8d9a91a719cd43279f7ea8b4fe01be0d":{
      "scriptId":"u83"},
    "064fa3f6ec3c42b79a35d2890f1bbb13":{
      "scriptId":"u84"},
    "9c7e4bd0baa843c2be9e6927577d7bfb":{
      "scriptId":"u85"},
    "a1f13f8abe474d40beaefcd52fe19bf8":{
      "scriptId":"u86"},
    "0c14630c9b124d00b3f8fbebedbdd912":{
      "scriptId":"u87"},
    "6f510a497bf14a5d82f9b31c413db7d9":{
      "scriptId":"u88"},
    "4007d59e1136479885210e612aefdc05":{
      "scriptId":"u89"},
    "d63c939ff3a04e21ad180bcd9027a036":{
      "scriptId":"u90"},
    "401316f847394ac58c2aa1ed67fce292":{
      "scriptId":"u91"},
    "e655d6dd32cc410d8201cd4d614f1e91":{
      "scriptId":"u92"},
    "aaca4812242c488586e70d316dc01a27":{
      "scriptId":"u93"},
    "9c31a6f4d579413aa861558d6e13d090":{
      "scriptId":"u94"},
    "7e09423f01344755a06c1b873805c7af":{
      "scriptId":"u95"},
    "01c4894962d14d01b00dc547a0851980":{
      "scriptId":"u96"},
    "ad098d91e2ae46a7b5e5c86a2a1f6149":{
      "scriptId":"u97"},
    "76bd66b292a34b18b8caed49ccb0d823":{
      "scriptId":"u98"},
    "424d80bec561466ba9ec52522c1e6950":{
      "scriptId":"u99"},
    "ae512e9937d24b5089c2d6c239a48338":{
      "scriptId":"u100"},
    "8763b69ccbd24338b507d012a63c960d":{
      "scriptId":"u101"},
    "1910839740c94de4adee48cc0b93fbe2":{
      "scriptId":"u102"},
    "ea1c846da79e47cca1bcdb8e83acf1e0":{
      "scriptId":"u103"},
    "4915517dc2a544e5b447fcd39ed4c29e":{
      "scriptId":"u104"}}});