$axure.loadCurrentPage({
  "url":"供应商类别.html",
  "generationDate":new Date(1446432606149.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ca685a060f2b4e2c99f9265b5c25919f",
    "type":"Axure:Page",
    "name":"供应商类别",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"54298bc67232430a9683899c3f455953",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f248b5663f465787415737e0f86799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"6b4daed58a9c42a7b42d33fd00b9282e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1b7ca0b1b744e2aba07a2702569c15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0cf165a5b7a401d807748e5c3eeddaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22246c1f0948473b83105cd2b3f95892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"beb249b3e88b4d27a9ac3afd91cac77d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"29cc4b0f131f41f8ae637bb556b58ad9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72a28731d12f477eb673e54401c8a280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1039a874ff5a4033a9882d604b27b258",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"dc7c82ca685148618b2c4556fdb71e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dae03c1a00b4c03b23362c57ad7ab5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"422cd52c4ebb4ae6bdb892aa97a3ec4f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"b0e7097d2ae64c2a948a465c89ef07a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30f88c85339a4acbbcd594b2f74e9327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9750c829bdb644e7b0d7ddc9704e2715",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"97c71b6dac5246fb867679bb9c79d250",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e90d5b2ba24d4a5ab744fb29d084f383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"818c2e5e7dbb4cae80bec159b6365fd5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"33e25556e2f24c27ac046a380974201a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2c73b1736ce42e195b071d0fb542569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"dcf8ee49d08841e3bc73d504463b6905",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a02d04ccf2140c0b9073d2a2d086f93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb91656d37b74ecea17e16672217862f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"409d37fab8f04ad9a3302d235d3c78d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"16fb7ce08588468a8831cf08e8012b41",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b405beffd24ff08ae03fb338761799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d2abacd22bd4b00b168e404c50d871a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fc42fa54b0949e68e2d88bb43179296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03f0d7398be349959efc31e9cf8efe6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8653293cd9b44589c617e908dc8b16d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"0fa1976368254e809441f9b1cd9291fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14cef7a992e64c2fb5d9aae0f78e8157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbefd1d8d9aa4959acf6a4af0b72e38b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e2c21ea75d94a9b908ef0f642c8e483",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"4f0309d7459046978ccd3899f97d9a76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3c2a2af9a3e43b0a0ebc5637a369854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"9fbdaa16974243dc9e3a0cddbcc832f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd78bf541d844fa9f3b4488c3e3e53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"6b672bc09c464390be3e2e15252f7056",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb493b21cc94e9d85bc9e34da54273c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"124d073ac2204cf491cbb3edabc0b95a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"789efab2cc954158be24fb5ebe1a6af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"a3978b35c6374d23b824644ad7197951",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63e5286bb8d8458e86f8b0c8de20fe6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"a0601722deb247e4b4a936425ca46b8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d64f505551c64a9fa2345c4e8d4a521c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba16ee1f913c4ab48299f966d6b0a3d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce841863d6e24aa2a7b443e74a4814bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef08d6dced144285b1cb6934a098a1b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84eb8513948e47e5b1557615564c79c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"316d7dc6bfb24035bc7c7dbbe5f64e03",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5496805993074303a0d43f447fdc5702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1849c2c5ca1a43129d6c5601f416e6f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96413e0a155d42bf87f7689c5f2a248b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f72f25ddeac247e68b96cc4485f6e5c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c73d51e2624c63a8aad08232880ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dcd2295246f441493edec040e5dabfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f7b92405bb4a688afc7d11c150b6b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5641b6e8ae44d00a54b30890ad14f81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"176c1167762b4468b434ade338183ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"1f920f874d444af4b41f83f50c29ecd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a911ac3d68e483194220f5c10ad2b95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"102a8ac840a849a1baf22f201846ea49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e855b19a284480991c3d739cdb625cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"a1807aafe7e9412eb2b250b5a9579f7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea15992bd6744b4b6a6c0a6395b3d49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"441ae8e41a7e42908e607398bad2244d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":347,
              "y":133},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49c9523a5bfe4476ba9cf5f1f18279e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":347,
                  "y":133},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32dedc3fd7994506a32ba86c0642013c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":230},
            "size":{
              "width":1766,
              "height":688}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ac5cb2f27764a2796cafadd741b13b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":230},
                "size":{
                  "width":1766,
                  "height":688}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u69.png"}},
{
          "id":"176a30cb18d64d83a3bf1aacced6c5d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c89cde2d67514c00bac1d2ecd9222336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0052bb1f9b504a50b6b6c129cf905f5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":186},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3404b5f75709405b9d1dc84b3c5d966e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":186},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a266ce110ca1452695ae4d66c9861767",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":240,
              "y":230},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b7232c9c164b1fb2182017783aa208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":240,
                  "y":230},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u75.png"}},
{
          "id":"a30c89c691694008921afae5444420e7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":230},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"87f2310c6e384a0795daa31e8b1a509b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":230},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"5016f325dce24994a983564992b71dfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":416,
              "y":237},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3ff0acb754442e5b0e545d50d0c2b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":416,
                  "y":237},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dcc1fe6639f4375a000a445f14eb183",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":630,
              "y":237},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85879278cff5491abdbb4828de6ac1ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":630,
                  "y":237},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0336245f0f3c45898b26b6e6a82d6b68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":269},
            "size":{
              "width":470,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c81f397efd64fd68e2ff0201671fde3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":269},
                "size":{
                  "width":470,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u83.png"}},
{
          "id":"96116bd273b443d2b486cc1b0b7ed469",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":269},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"fd44c41256e14db98dd3ab87c479331d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":269},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"c5fc9cf1e290486499f7b528bf0f7a09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":276},
            "size":{
              "width":19,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af24b1f691fd4b4884d86b58a9f54315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":276},
                "size":{
                  "width":19,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"7fb8f17585a74ccd93248d7631519b4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":280},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4111abe5cc34cdea0a9c15108c66e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":623,
                  "y":280},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u96.png"}},
{
          "id":"61bde65379324a37a78a51ab1cb98bfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":416,
              "y":277},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac1c0d40bd5d4d21a944d498e2c49c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":416,
                  "y":277},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff76f3808eff477787588ed20c4f0d0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1785,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"773dbcd4d1e1413ca373c9e80acd7cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1785,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"2ec26ce06e434061b8480595314eeec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1910,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f83337da6e6e40e1a1bb6817f027a7e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1910,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"ce38cb69351b4b94afaeb0d90b49c933",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":319,
              "y":185},
            "size":{
              "width":81,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d02505af3520490faca50ef8f0b97dcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":319,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u97.png"}},
{
          "id":"63d082461b844d1c8eb7dcc1542913cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":398,
              "y":185},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f29916886244e41838477934f012442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":398,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u99.png"}},
{
          "id":"492d31a379d94312ab8af8c1f8b9bf1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":473,
              "y":185},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12140aece3f64e49871977dc731eea81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":473,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u99.png"}},
{
          "id":"53dfc2d0afa1410e80eedbf82d4798cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":553,
              "y":185},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc80a7cdeca147d585e7ca41478e8322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":553,
                  "y":185},
                "size":{
                  "width":81,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u99.png"}},
{
          "id":"59a0649489e2430297483d3ba7284da6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":814,
              "y":185},
            "size":{
              "width":286,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"259a87607c914469b93b71b9929e2602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":814,
                  "y":185},
                "size":{
                  "width":286,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u105.png"}},
{
          "id":"0fbc352272e844ed9a5fb692c05095b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1112,
              "y":185},
            "size":{
              "width":67,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da793f630f3e4302b378646a6be3323f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1112,
                  "y":185},
                "size":{
                  "width":67,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u107.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "54298bc67232430a9683899c3f455953":{
      "scriptId":"u0"},
    "18f248b5663f465787415737e0f86799":{
      "scriptId":"u1"},
    "6b4daed58a9c42a7b42d33fd00b9282e":{
      "scriptId":"u2"},
    "7f1b7ca0b1b744e2aba07a2702569c15":{
      "scriptId":"u3"},
    "e0cf165a5b7a401d807748e5c3eeddaf":{
      "scriptId":"u4"},
    "22246c1f0948473b83105cd2b3f95892":{
      "scriptId":"u5"},
    "beb249b3e88b4d27a9ac3afd91cac77d":{
      "scriptId":"u6"},
    "29cc4b0f131f41f8ae637bb556b58ad9":{
      "scriptId":"u7"},
    "72a28731d12f477eb673e54401c8a280":{
      "scriptId":"u8"},
    "1039a874ff5a4033a9882d604b27b258":{
      "scriptId":"u9"},
    "dc7c82ca685148618b2c4556fdb71e59":{
      "scriptId":"u10"},
    "4dae03c1a00b4c03b23362c57ad7ab5b":{
      "scriptId":"u11"},
    "422cd52c4ebb4ae6bdb892aa97a3ec4f":{
      "scriptId":"u12"},
    "b0e7097d2ae64c2a948a465c89ef07a3":{
      "scriptId":"u13"},
    "30f88c85339a4acbbcd594b2f74e9327":{
      "scriptId":"u14"},
    "9750c829bdb644e7b0d7ddc9704e2715":{
      "scriptId":"u15"},
    "97c71b6dac5246fb867679bb9c79d250":{
      "scriptId":"u16"},
    "e90d5b2ba24d4a5ab744fb29d084f383":{
      "scriptId":"u17"},
    "818c2e5e7dbb4cae80bec159b6365fd5":{
      "scriptId":"u18"},
    "33e25556e2f24c27ac046a380974201a":{
      "scriptId":"u19"},
    "f2c73b1736ce42e195b071d0fb542569":{
      "scriptId":"u20"},
    "dcf8ee49d08841e3bc73d504463b6905":{
      "scriptId":"u21"},
    "2a02d04ccf2140c0b9073d2a2d086f93":{
      "scriptId":"u22"},
    "eb91656d37b74ecea17e16672217862f":{
      "scriptId":"u23"},
    "409d37fab8f04ad9a3302d235d3c78d0":{
      "scriptId":"u24"},
    "16fb7ce08588468a8831cf08e8012b41":{
      "scriptId":"u25"},
    "89b405beffd24ff08ae03fb338761799":{
      "scriptId":"u26"},
    "6d2abacd22bd4b00b168e404c50d871a":{
      "scriptId":"u27"},
    "9fc42fa54b0949e68e2d88bb43179296":{
      "scriptId":"u28"},
    "03f0d7398be349959efc31e9cf8efe6d":{
      "scriptId":"u29"},
    "c8653293cd9b44589c617e908dc8b16d":{
      "scriptId":"u30"},
    "0fa1976368254e809441f9b1cd9291fe":{
      "scriptId":"u31"},
    "14cef7a992e64c2fb5d9aae0f78e8157":{
      "scriptId":"u32"},
    "bbefd1d8d9aa4959acf6a4af0b72e38b":{
      "scriptId":"u33"},
    "0e2c21ea75d94a9b908ef0f642c8e483":{
      "scriptId":"u34"},
    "4f0309d7459046978ccd3899f97d9a76":{
      "scriptId":"u35"},
    "e3c2a2af9a3e43b0a0ebc5637a369854":{
      "scriptId":"u36"},
    "9fbdaa16974243dc9e3a0cddbcc832f9":{
      "scriptId":"u37"},
    "bbd78bf541d844fa9f3b4488c3e3e53b":{
      "scriptId":"u38"},
    "6b672bc09c464390be3e2e15252f7056":{
      "scriptId":"u39"},
    "bbb493b21cc94e9d85bc9e34da54273c":{
      "scriptId":"u40"},
    "124d073ac2204cf491cbb3edabc0b95a":{
      "scriptId":"u41"},
    "789efab2cc954158be24fb5ebe1a6af0":{
      "scriptId":"u42"},
    "a3978b35c6374d23b824644ad7197951":{
      "scriptId":"u43"},
    "63e5286bb8d8458e86f8b0c8de20fe6e":{
      "scriptId":"u44"},
    "a0601722deb247e4b4a936425ca46b8c":{
      "scriptId":"u45"},
    "d64f505551c64a9fa2345c4e8d4a521c":{
      "scriptId":"u46"},
    "ba16ee1f913c4ab48299f966d6b0a3d6":{
      "scriptId":"u47"},
    "ce841863d6e24aa2a7b443e74a4814bc":{
      "scriptId":"u48"},
    "ef08d6dced144285b1cb6934a098a1b1":{
      "scriptId":"u49"},
    "84eb8513948e47e5b1557615564c79c7":{
      "scriptId":"u50"},
    "316d7dc6bfb24035bc7c7dbbe5f64e03":{
      "scriptId":"u51"},
    "5496805993074303a0d43f447fdc5702":{
      "scriptId":"u52"},
    "1849c2c5ca1a43129d6c5601f416e6f5":{
      "scriptId":"u53"},
    "96413e0a155d42bf87f7689c5f2a248b":{
      "scriptId":"u54"},
    "f72f25ddeac247e68b96cc4485f6e5c3":{
      "scriptId":"u55"},
    "b7c73d51e2624c63a8aad08232880ad6":{
      "scriptId":"u56"},
    "4dcd2295246f441493edec040e5dabfd":{
      "scriptId":"u57"},
    "d6f7b92405bb4a688afc7d11c150b6b2":{
      "scriptId":"u58"},
    "c5641b6e8ae44d00a54b30890ad14f81":{
      "scriptId":"u59"},
    "176c1167762b4468b434ade338183ec3":{
      "scriptId":"u60"},
    "1f920f874d444af4b41f83f50c29ecd8":{
      "scriptId":"u61"},
    "9a911ac3d68e483194220f5c10ad2b95":{
      "scriptId":"u62"},
    "102a8ac840a849a1baf22f201846ea49":{
      "scriptId":"u63"},
    "7e855b19a284480991c3d739cdb625cf":{
      "scriptId":"u64"},
    "a1807aafe7e9412eb2b250b5a9579f7a":{
      "scriptId":"u65"},
    "5ea15992bd6744b4b6a6c0a6395b3d49":{
      "scriptId":"u66"},
    "441ae8e41a7e42908e607398bad2244d":{
      "scriptId":"u67"},
    "49c9523a5bfe4476ba9cf5f1f18279e9":{
      "scriptId":"u68"},
    "32dedc3fd7994506a32ba86c0642013c":{
      "scriptId":"u69"},
    "7ac5cb2f27764a2796cafadd741b13b7":{
      "scriptId":"u70"},
    "176a30cb18d64d83a3bf1aacced6c5d4":{
      "scriptId":"u71"},
    "c89cde2d67514c00bac1d2ecd9222336":{
      "scriptId":"u72"},
    "0052bb1f9b504a50b6b6c129cf905f5c":{
      "scriptId":"u73"},
    "3404b5f75709405b9d1dc84b3c5d966e":{
      "scriptId":"u74"},
    "a266ce110ca1452695ae4d66c9861767":{
      "scriptId":"u75"},
    "f3b7232c9c164b1fb2182017783aa208":{
      "scriptId":"u76"},
    "a30c89c691694008921afae5444420e7":{
      "scriptId":"u77"},
    "87f2310c6e384a0795daa31e8b1a509b":{
      "scriptId":"u78"},
    "5016f325dce24994a983564992b71dfc":{
      "scriptId":"u79"},
    "b3ff0acb754442e5b0e545d50d0c2b90":{
      "scriptId":"u80"},
    "8dcc1fe6639f4375a000a445f14eb183":{
      "scriptId":"u81"},
    "85879278cff5491abdbb4828de6ac1ad":{
      "scriptId":"u82"},
    "0336245f0f3c45898b26b6e6a82d6b68":{
      "scriptId":"u83"},
    "1c81f397efd64fd68e2ff0201671fde3":{
      "scriptId":"u84"},
    "96116bd273b443d2b486cc1b0b7ed469":{
      "scriptId":"u85"},
    "fd44c41256e14db98dd3ab87c479331d":{
      "scriptId":"u86"},
    "c5fc9cf1e290486499f7b528bf0f7a09":{
      "scriptId":"u87"},
    "af24b1f691fd4b4884d86b58a9f54315":{
      "scriptId":"u88"},
    "7fb8f17585a74ccd93248d7631519b4e":{
      "scriptId":"u89"},
    "b4111abe5cc34cdea0a9c15108c66e2c":{
      "scriptId":"u90"},
    "61bde65379324a37a78a51ab1cb98bfc":{
      "scriptId":"u91"},
    "ac1c0d40bd5d4d21a944d498e2c49c56":{
      "scriptId":"u92"},
    "ff76f3808eff477787588ed20c4f0d0a":{
      "scriptId":"u93"},
    "773dbcd4d1e1413ca373c9e80acd7cd4":{
      "scriptId":"u94"},
    "2ec26ce06e434061b8480595314eeec8":{
      "scriptId":"u95"},
    "f83337da6e6e40e1a1bb6817f027a7e7":{
      "scriptId":"u96"},
    "ce38cb69351b4b94afaeb0d90b49c933":{
      "scriptId":"u97"},
    "d02505af3520490faca50ef8f0b97dcd":{
      "scriptId":"u98"},
    "63d082461b844d1c8eb7dcc1542913cd":{
      "scriptId":"u99"},
    "6f29916886244e41838477934f012442":{
      "scriptId":"u100"},
    "492d31a379d94312ab8af8c1f8b9bf1c":{
      "scriptId":"u101"},
    "12140aece3f64e49871977dc731eea81":{
      "scriptId":"u102"},
    "53dfc2d0afa1410e80eedbf82d4798cc":{
      "scriptId":"u103"},
    "cc80a7cdeca147d585e7ca41478e8322":{
      "scriptId":"u104"},
    "59a0649489e2430297483d3ba7284da6":{
      "scriptId":"u105"},
    "259a87607c914469b93b71b9929e2602":{
      "scriptId":"u106"},
    "0fbc352272e844ed9a5fb692c05095b0":{
      "scriptId":"u107"},
    "da793f630f3e4302b378646a6be3323f":{
      "scriptId":"u108"}}});