$axure.loadCurrentPage({
  "url":"供应商对账单.html",
  "generationDate":new Date(1446432611500.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5794c9c8333548e18c66baf75b95fb21",
    "type":"Axure:Page",
    "name":"供应商对账单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ddf1b146e0f64fbc9f52b400c1c37022",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-211,
              "y":63},
            "size":{
              "width":1800,
              "height":753}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba097de86ea544dca4011bd6393dec78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-211,
                  "y":63},
                "size":{
                  "width":1800,
                  "height":753}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商对账单/u0.png"}},
{
          "id":"5806688aa1a147b095d5fb6be755ca88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":257},
            "size":{
              "width":126,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a054439fb24a1c91f11d691bf4d428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":257},
                "size":{
                  "width":126,
                  "height":156}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商对账单/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ddf1b146e0f64fbc9f52b400c1c37022":{
      "scriptId":"u0"},
    "ba097de86ea544dca4011bd6393dec78":{
      "scriptId":"u1"},
    "5806688aa1a147b095d5fb6be755ca88":{
      "scriptId":"u2"},
    "59a054439fb24a1c91f11d691bf4d428":{
      "scriptId":"u3"}}});