$axure.loadCurrentPage({
  "url":"客户管理.html",
  "generationDate":new Date(1446432604860.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f7afef9c278b46039ec325d14e143376",
    "type":"Axure:Page",
    "name":"客户管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5a64b4ca744c45349302c7528e030f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2985c76b291404bb3bd035bf80f94c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"8a442fdd6b644bd99b193076102d4191",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc4116c1b9bd42679941a0c306655eb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8db598083c27425e9e6b651521d0c636",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d719f695977947f595f65b31e7555339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"458bc824a1554dc3ac8995ac12621bde",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"566e894755bf41d1846ba5b7b8073ebf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87963bdb95d24eaabe043031b62e7020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d96c54fbde2e43bdaa40612d01c4efc9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"d41a23508bbb47c1afe0d0cba56e6014",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e71396c673df46c99d32f3c8e4c09191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e824b89eac540b0ab239334ce6ef0de",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"bbaac0e943254f9f86330ef87565d5ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c80f44bd994db3955afab8f3330d0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18fe2b21906f4534afdc78c89d2355a0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"4d9bf5a7e0ae4ffeadda547f68e5479d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cf996c3a0c3438489fb421a7f36238a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74d2bcba643d4139b11dab5ac701b456",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"dce6566bf5d24280aed70211c288b2ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a16cdf086f77403eb48ac4dc937abc1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"65eabb499b6545fd991151ad444a8b21",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67706677e6aa420980cf92d0a8a9c618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c87cc1dbbc694d1fa5d89de294ef1494",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1decec5c18841fdbf23f0af50f4d82c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"7dc8352f2c24451781703e33004541e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3651f3a9671146d8965f9ff34695a9fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaa469651a5d4598b517b37bb9dfcc14",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674960ab5a154d94bec02ab815813275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36ec0e7a688a4b87bce194ef90d1d364",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3cddb53efdd45ab9c8437d1354b7971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"3f54ea6a61bb4f2088ff7056baa85e12",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47aa9d4a661246bd8cefc010116e20c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab6fc6dbfe74494ba6d5ac9b992b2dd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6e5ea1b5152418298de88b675e9b42b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"20335d1d1138411d8ef3520f91d088d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8c85167bb7c498bbc63ba1fea61d6d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"758c26c26f394dffb180a117c236c235",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06fb8d0e7cc84e18a13e2782ecfd915d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"a69f39dde15e42bbb3de478183d4812f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"420eddce56534e3c812cae976ca7a958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0689a8b21f204e2894f9220d8ace4876",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"081a3cde2f154670abf16e7a0f0c1380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"70362474435d420d9890a5b311e3fa63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb5a92e8341418abd8710f8c997fef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"f8d8e826ba1e47d49fb4e70c95e071dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf634d08708494ca8f248e71c929d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc9457859f0547008d4740da46372cc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca927260a89d4c419480073382a7a088",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d08eaaafcc3640e8925aa1087f5a3c77",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e708e689f9534ac5add07981f3666f25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0d29b1cb0694e188d7700cb9c71ce3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5945dc5444543078d597cb359c2a7f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5455feb671c3436fbef48906553da95a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d7d4cef94e41468eda4fe0acb4d41f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf66f01b39c24258a4c1299196ae0fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8ec75a0934e4b97bb1275f3a66ed423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dba03c5bd05d48ef8b1026048af024ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"433168a2d26d4a7094e9c1af3abd96be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"245010a569a542c6a834a56393b2667f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58cdff2597b842d78e1c1e60fe6ad67e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"2b560b46b0ff43f5a687db0e73a2125e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaf840f0e0244d718188440bbab8e9f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"2a865852ba3b4babb487c1aa5bb8acc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c178dcb5059646e7a9ee3fedd0bed9b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"3142c433b8b742bd9652eae91cd3c832",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"301edc04e53045a7bfb7ddeee274ca0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"cc3fb4a0a19d4eb9ac5853d2278f2210",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":344,
              "y":133},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e99758d67bb4389b712890e1538da42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":344,
                  "y":133},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a52ec2c9bc142afbe639076fb1009dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":263},
            "size":{
              "width":1766,
              "height":688}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a93f4eac3d9048b29e04b585ff086b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":263},
                "size":{
                  "width":1766,
                  "height":688}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u69.png"}},
{
          "id":"4422692476a0442f8225bc17fa07c797",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e9a9f4282f24a5288772b95b58fa68f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f1b6eb977004b7f862b35bd35c00b18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":240,
              "y":225},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59fc8dd827b54378afe23d4c70a8e17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":240,
                  "y":225},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u75.png"}},
{
          "id":"10589a38a8904d579d53e9a038ff2d53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":247,
              "y":232},
            "size":{
              "width":88,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf343d1d2564fc895ac24fd952bdf77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":247,
                  "y":232},
                "size":{
                  "width":88,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e1f6fe80d4a41d49a165566b0192f29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":240,
              "y":263},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcdcb784485a420e89040971f6d35ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":240,
                  "y":263},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品管理/u77.png"}},
{
          "id":"1cedc9cf21ce47d1a97d8794f8faf09c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"ddf5a7afa7b645e08e6b973f3e49d820",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":536,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"18a2ba9087b6426faf9bd0a14f838134",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":284,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fed83c3f01164331925d9ee09035e8a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":284,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d67cd69015764f7ba5e98df55bd7d26a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1323,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d56ed43758ff40faaa6aeb74a973d548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1323,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"4dd6895eaef6439481edc077b1678d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1439,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bda1665c09ff45dbbf18e92dac93f80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1439,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"5de7f092070144e2bdf88f5367241f25",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":265},
            "size":{
              "width":10,
              "height":685}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u87_line.png"}},
{
          "id":"1e380b90e35a48528eaeff4a5d493a5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":422,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517ffa52ced24897a5e7a3d381079114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":422,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46ee6b747b3c41139319b471094df0e2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"432c1396f00f467c9a5ffcd258388dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":604,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4d09ee1b124d90977647ef6b90df4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":604,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a877d7d0331e4108882c8b75898f61d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":783,
              "y":270},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac56806ad0a4eb4b217d3de73fec85b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":783,
                  "y":270},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f454e57b2094ee2839ec3bc249871cb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":899,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"7ea31ed638114c0aa72f859d04a719dd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1444,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"0b71acba74554aa6982576100c12d9c7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"9918a13540a044ecaa90051518c24eaf",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1892,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"f629a88bb40d47a0975ec45d31fb8a3d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":330},
            "size":{
              "width":1760,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u125_line.png"}},
{
          "id":"b5fd2b7d76e04ecd8f30b5d987e636e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC00},
            "location":{
              "x":1794,
              "y":306},
            "size":{
              "width":72,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16cea214f034d9f93c9912f2ee49882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "location":{
                  "x":1794,
                  "y":306},
                "size":{
                  "width":72,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u98.png"}},
{
          "id":"78d186374a0243368c069b1751bccac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1556,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7699488b0b047029acd38a2a1412ff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1556,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"a405fa0fd2224604b1e2f643a36d80d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1670,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d6bbb7c31864a3a9fa112e6cc35517d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1670,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"b4ee7b4f6ba749e9995467051bf1ed4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1788,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67cda7757a61496da8921428ecf28860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1788,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"99be2cfdb5134ba5bfe5aa26c24c26e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1910,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107e8988ae444fbfabec756d38dfafad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1910,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"2cea193a6dce43acb96cc10a7eb13c3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "horizontalAlignment":"left",
            "location":{
              "x":243,
              "y":173},
            "size":{
              "width":200,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c37a67d9830b4c30bb00214b1d290a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "horizontalAlignment":"left",
                "location":{
                  "x":243,
                  "y":173},
                "size":{
                  "width":200,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商管理/u110.png"}},
{
          "id":"f07856d71f764c88b0ed77d4b9529e9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":191},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"953c9d8875c4451cb15cb65d58713d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":191},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"3f86a204349a4ffaafa583663f7ce6a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":173},
            "size":{
              "width":440,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b67c128109141ac81bfe1c57fa46f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":173},
                "size":{
                  "width":440,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商管理/u114.png"}},
{
          "id":"cbad1932f92046c3abbb094082936de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":480,
              "y":181},
            "size":{
              "width":361,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582bfc690596461d8c79fbad04d31f1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":181},
                "size":{
                  "width":361,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24185ea605a24b009469eabf7406f750",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":943,
              "y":173},
            "size":{
              "width":67,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c94bc859e63f408a97fb28c4b0efe486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":943,
                  "y":173},
                "size":{
                  "width":67,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商管理/u118.png"}},
{
          "id":"b66916e7db4a489daf33211e6567acde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":275},
            "size":{
              "width":13,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37deb430947c40e29d689993c74aa5f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":275},
                "size":{
                  "width":13,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品管理/u140.png"}},
{
          "id":"c92c7a11b06f4e3ea40aac2fd8dea3b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":310},
            "size":{
              "width":13,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c2e80fabe84d18a845de8abcbe0910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":310},
                "size":{
                  "width":13,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品管理/u140.png"}},
{
          "id":"18f33054fc2a4a888c63a7d9bc1c6825",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":975,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1d00df48316497e88a0adcd1855eb28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":975,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4e3e8ca62044cfc94f162d6a0659b71",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1098,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"30e6c0d7184040a0b949ec828573fdc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1175,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"595e38a41457472182d025b4a572ffd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1175,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bac58954635d4d8eb2b105c20fa78327",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1293,
              "y":263},
            "size":{
              "width":10,
              "height":77}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品管理/u79_line.png"}},
{
          "id":"f9c3dfc1d3204062a20d02846a65bea7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1308,
              "y":270},
            "size":{
              "width":133,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9180375d844845818aaa9c310b90042d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1308,
                  "y":270},
                "size":{
                  "width":133,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a67f20638a4d48f8a8796beb4f68b4b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1801,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb538b9089d447c08c8b906253233545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1801,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b11eb52bf8b46b4a961e7340d19f4ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1931,
              "y":270},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"717171597e624ebbb97fa1ffaf931928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1931,
                  "y":270},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99d79ad925b0487b93e134a8fe5d02e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1967,
              "y":306},
            "size":{
              "width":19,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67419dd73044de6818e698fc4b40ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1967,
                  "y":306},
                "size":{
                  "width":19,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"8f2ae9ecdd7b4915a97a99900eca6789",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1921,
              "y":310},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"641a45e8670243298f45713d3df3d7c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1921,
                  "y":310},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u96.png"}},
{
          "id":"4a7b1326142f400a912237dca6e88e27",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1547,
              "y":270},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d35760128245efbf47d906702ece36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1547,
                  "y":270},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5a64b4ca744c45349302c7528e030f52":{
      "scriptId":"u0"},
    "d2985c76b291404bb3bd035bf80f94c2":{
      "scriptId":"u1"},
    "8a442fdd6b644bd99b193076102d4191":{
      "scriptId":"u2"},
    "dc4116c1b9bd42679941a0c306655eb0":{
      "scriptId":"u3"},
    "8db598083c27425e9e6b651521d0c636":{
      "scriptId":"u4"},
    "d719f695977947f595f65b31e7555339":{
      "scriptId":"u5"},
    "458bc824a1554dc3ac8995ac12621bde":{
      "scriptId":"u6"},
    "566e894755bf41d1846ba5b7b8073ebf":{
      "scriptId":"u7"},
    "87963bdb95d24eaabe043031b62e7020":{
      "scriptId":"u8"},
    "d96c54fbde2e43bdaa40612d01c4efc9":{
      "scriptId":"u9"},
    "d41a23508bbb47c1afe0d0cba56e6014":{
      "scriptId":"u10"},
    "e71396c673df46c99d32f3c8e4c09191":{
      "scriptId":"u11"},
    "6e824b89eac540b0ab239334ce6ef0de":{
      "scriptId":"u12"},
    "bbaac0e943254f9f86330ef87565d5ed":{
      "scriptId":"u13"},
    "f0c80f44bd994db3955afab8f3330d0e":{
      "scriptId":"u14"},
    "18fe2b21906f4534afdc78c89d2355a0":{
      "scriptId":"u15"},
    "4d9bf5a7e0ae4ffeadda547f68e5479d":{
      "scriptId":"u16"},
    "5cf996c3a0c3438489fb421a7f36238a":{
      "scriptId":"u17"},
    "74d2bcba643d4139b11dab5ac701b456":{
      "scriptId":"u18"},
    "dce6566bf5d24280aed70211c288b2ec":{
      "scriptId":"u19"},
    "a16cdf086f77403eb48ac4dc937abc1d":{
      "scriptId":"u20"},
    "65eabb499b6545fd991151ad444a8b21":{
      "scriptId":"u21"},
    "67706677e6aa420980cf92d0a8a9c618":{
      "scriptId":"u22"},
    "c87cc1dbbc694d1fa5d89de294ef1494":{
      "scriptId":"u23"},
    "b1decec5c18841fdbf23f0af50f4d82c":{
      "scriptId":"u24"},
    "7dc8352f2c24451781703e33004541e1":{
      "scriptId":"u25"},
    "3651f3a9671146d8965f9ff34695a9fa":{
      "scriptId":"u26"},
    "aaa469651a5d4598b517b37bb9dfcc14":{
      "scriptId":"u27"},
    "674960ab5a154d94bec02ab815813275":{
      "scriptId":"u28"},
    "36ec0e7a688a4b87bce194ef90d1d364":{
      "scriptId":"u29"},
    "b3cddb53efdd45ab9c8437d1354b7971":{
      "scriptId":"u30"},
    "3f54ea6a61bb4f2088ff7056baa85e12":{
      "scriptId":"u31"},
    "47aa9d4a661246bd8cefc010116e20c0":{
      "scriptId":"u32"},
    "ab6fc6dbfe74494ba6d5ac9b992b2dd3":{
      "scriptId":"u33"},
    "c6e5ea1b5152418298de88b675e9b42b":{
      "scriptId":"u34"},
    "20335d1d1138411d8ef3520f91d088d5":{
      "scriptId":"u35"},
    "c8c85167bb7c498bbc63ba1fea61d6d1":{
      "scriptId":"u36"},
    "758c26c26f394dffb180a117c236c235":{
      "scriptId":"u37"},
    "06fb8d0e7cc84e18a13e2782ecfd915d":{
      "scriptId":"u38"},
    "a69f39dde15e42bbb3de478183d4812f":{
      "scriptId":"u39"},
    "420eddce56534e3c812cae976ca7a958":{
      "scriptId":"u40"},
    "0689a8b21f204e2894f9220d8ace4876":{
      "scriptId":"u41"},
    "081a3cde2f154670abf16e7a0f0c1380":{
      "scriptId":"u42"},
    "70362474435d420d9890a5b311e3fa63":{
      "scriptId":"u43"},
    "cfb5a92e8341418abd8710f8c997fef8":{
      "scriptId":"u44"},
    "f8d8e826ba1e47d49fb4e70c95e071dd":{
      "scriptId":"u45"},
    "baf634d08708494ca8f248e71c929d36":{
      "scriptId":"u46"},
    "fc9457859f0547008d4740da46372cc9":{
      "scriptId":"u47"},
    "ca927260a89d4c419480073382a7a088":{
      "scriptId":"u48"},
    "d08eaaafcc3640e8925aa1087f5a3c77":{
      "scriptId":"u49"},
    "e708e689f9534ac5add07981f3666f25":{
      "scriptId":"u50"},
    "a0d29b1cb0694e188d7700cb9c71ce3e":{
      "scriptId":"u51"},
    "f5945dc5444543078d597cb359c2a7f2":{
      "scriptId":"u52"},
    "5455feb671c3436fbef48906553da95a":{
      "scriptId":"u53"},
    "47d7d4cef94e41468eda4fe0acb4d41f":{
      "scriptId":"u54"},
    "cf66f01b39c24258a4c1299196ae0fd1":{
      "scriptId":"u55"},
    "e8ec75a0934e4b97bb1275f3a66ed423":{
      "scriptId":"u56"},
    "dba03c5bd05d48ef8b1026048af024ca":{
      "scriptId":"u57"},
    "433168a2d26d4a7094e9c1af3abd96be":{
      "scriptId":"u58"},
    "245010a569a542c6a834a56393b2667f":{
      "scriptId":"u59"},
    "58cdff2597b842d78e1c1e60fe6ad67e":{
      "scriptId":"u60"},
    "2b560b46b0ff43f5a687db0e73a2125e":{
      "scriptId":"u61"},
    "aaf840f0e0244d718188440bbab8e9f7":{
      "scriptId":"u62"},
    "2a865852ba3b4babb487c1aa5bb8acc4":{
      "scriptId":"u63"},
    "c178dcb5059646e7a9ee3fedd0bed9b4":{
      "scriptId":"u64"},
    "3142c433b8b742bd9652eae91cd3c832":{
      "scriptId":"u65"},
    "301edc04e53045a7bfb7ddeee274ca0e":{
      "scriptId":"u66"},
    "cc3fb4a0a19d4eb9ac5853d2278f2210":{
      "scriptId":"u67"},
    "1e99758d67bb4389b712890e1538da42":{
      "scriptId":"u68"},
    "2a52ec2c9bc142afbe639076fb1009dc":{
      "scriptId":"u69"},
    "a93f4eac3d9048b29e04b585ff086b96":{
      "scriptId":"u70"},
    "4422692476a0442f8225bc17fa07c797":{
      "scriptId":"u71"},
    "4e9a9f4282f24a5288772b95b58fa68f":{
      "scriptId":"u72"},
    "6f1b6eb977004b7f862b35bd35c00b18":{
      "scriptId":"u73"},
    "59fc8dd827b54378afe23d4c70a8e17b":{
      "scriptId":"u74"},
    "10589a38a8904d579d53e9a038ff2d53":{
      "scriptId":"u75"},
    "7bf343d1d2564fc895ac24fd952bdf77":{
      "scriptId":"u76"},
    "9e1f6fe80d4a41d49a165566b0192f29":{
      "scriptId":"u77"},
    "dcdcb784485a420e89040971f6d35ff6":{
      "scriptId":"u78"},
    "1cedc9cf21ce47d1a97d8794f8faf09c":{
      "scriptId":"u79"},
    "ddf5a7afa7b645e08e6b973f3e49d820":{
      "scriptId":"u80"},
    "18a2ba9087b6426faf9bd0a14f838134":{
      "scriptId":"u81"},
    "fed83c3f01164331925d9ee09035e8a8":{
      "scriptId":"u82"},
    "d67cd69015764f7ba5e98df55bd7d26a":{
      "scriptId":"u83"},
    "d56ed43758ff40faaa6aeb74a973d548":{
      "scriptId":"u84"},
    "4dd6895eaef6439481edc077b1678d07":{
      "scriptId":"u85"},
    "bda1665c09ff45dbbf18e92dac93f80a":{
      "scriptId":"u86"},
    "5de7f092070144e2bdf88f5367241f25":{
      "scriptId":"u87"},
    "1e380b90e35a48528eaeff4a5d493a5d":{
      "scriptId":"u88"},
    "517ffa52ced24897a5e7a3d381079114":{
      "scriptId":"u89"},
    "46ee6b747b3c41139319b471094df0e2":{
      "scriptId":"u90"},
    "432c1396f00f467c9a5ffcd258388dc0":{
      "scriptId":"u91"},
    "6b4d09ee1b124d90977647ef6b90df4d":{
      "scriptId":"u92"},
    "a877d7d0331e4108882c8b75898f61d4":{
      "scriptId":"u93"},
    "9ac56806ad0a4eb4b217d3de73fec85b":{
      "scriptId":"u94"},
    "9f454e57b2094ee2839ec3bc249871cb":{
      "scriptId":"u95"},
    "7ea31ed638114c0aa72f859d04a719dd":{
      "scriptId":"u96"},
    "0b71acba74554aa6982576100c12d9c7":{
      "scriptId":"u97"},
    "9918a13540a044ecaa90051518c24eaf":{
      "scriptId":"u98"},
    "f629a88bb40d47a0975ec45d31fb8a3d":{
      "scriptId":"u99"},
    "b5fd2b7d76e04ecd8f30b5d987e636e1":{
      "scriptId":"u100"},
    "d16cea214f034d9f93c9912f2ee49882":{
      "scriptId":"u101"},
    "78d186374a0243368c069b1751bccac7":{
      "scriptId":"u102"},
    "b7699488b0b047029acd38a2a1412ff0":{
      "scriptId":"u103"},
    "a405fa0fd2224604b1e2f643a36d80d7":{
      "scriptId":"u104"},
    "6d6bbb7c31864a3a9fa112e6cc35517d":{
      "scriptId":"u105"},
    "b4ee7b4f6ba749e9995467051bf1ed4f":{
      "scriptId":"u106"},
    "67cda7757a61496da8921428ecf28860":{
      "scriptId":"u107"},
    "99be2cfdb5134ba5bfe5aa26c24c26e7":{
      "scriptId":"u108"},
    "107e8988ae444fbfabec756d38dfafad":{
      "scriptId":"u109"},
    "2cea193a6dce43acb96cc10a7eb13c3d":{
      "scriptId":"u110"},
    "c37a67d9830b4c30bb00214b1d290a16":{
      "scriptId":"u111"},
    "f07856d71f764c88b0ed77d4b9529e9b":{
      "scriptId":"u112"},
    "953c9d8875c4451cb15cb65d58713d93":{
      "scriptId":"u113"},
    "3f86a204349a4ffaafa583663f7ce6a1":{
      "scriptId":"u114"},
    "2b67c128109141ac81bfe1c57fa46f00":{
      "scriptId":"u115"},
    "cbad1932f92046c3abbb094082936de6":{
      "scriptId":"u116"},
    "582bfc690596461d8c79fbad04d31f1f":{
      "scriptId":"u117"},
    "24185ea605a24b009469eabf7406f750":{
      "scriptId":"u118"},
    "c94bc859e63f408a97fb28c4b0efe486":{
      "scriptId":"u119"},
    "b66916e7db4a489daf33211e6567acde":{
      "scriptId":"u120"},
    "37deb430947c40e29d689993c74aa5f2":{
      "scriptId":"u121"},
    "c92c7a11b06f4e3ea40aac2fd8dea3b1":{
      "scriptId":"u122"},
    "57c2e80fabe84d18a845de8abcbe0910":{
      "scriptId":"u123"},
    "18f33054fc2a4a888c63a7d9bc1c6825":{
      "scriptId":"u124"},
    "d1d00df48316497e88a0adcd1855eb28":{
      "scriptId":"u125"},
    "f4e3e8ca62044cfc94f162d6a0659b71":{
      "scriptId":"u126"},
    "30e6c0d7184040a0b949ec828573fdc9":{
      "scriptId":"u127"},
    "595e38a41457472182d025b4a572ffd9":{
      "scriptId":"u128"},
    "bac58954635d4d8eb2b105c20fa78327":{
      "scriptId":"u129"},
    "f9c3dfc1d3204062a20d02846a65bea7":{
      "scriptId":"u130"},
    "9180375d844845818aaa9c310b90042d":{
      "scriptId":"u131"},
    "a67f20638a4d48f8a8796beb4f68b4b4":{
      "scriptId":"u132"},
    "eb538b9089d447c08c8b906253233545":{
      "scriptId":"u133"},
    "5b11eb52bf8b46b4a961e7340d19f4ea":{
      "scriptId":"u134"},
    "717171597e624ebbb97fa1ffaf931928":{
      "scriptId":"u135"},
    "99d79ad925b0487b93e134a8fe5d02e2":{
      "scriptId":"u136"},
    "e67419dd73044de6818e698fc4b40ade":{
      "scriptId":"u137"},
    "8f2ae9ecdd7b4915a97a99900eca6789":{
      "scriptId":"u138"},
    "641a45e8670243298f45713d3df3d7c4":{
      "scriptId":"u139"},
    "4a7b1326142f400a912237dca6e88e27":{
      "scriptId":"u140"},
    "75d35760128245efbf47d906702ece36":{
      "scriptId":"u141"}}});