$axure.loadCurrentPage({
  "url":"采购汇总表（按商品）.html",
  "generationDate":new Date(1446432609960.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5ea99d282f0f4c349c2813f36ba51525",
    "type":"Axure:Page",
    "name":"采购汇总表（按商品）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6f9a83462e344065b34d3f22da93df33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfaa59d40c37409ea9f783c17f5a91a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"6f322668fc654482904276a935a403f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5359b1fe5a384f5f8d3c910f2b385456",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d25c3e4a6464f45aaea636837c4f633",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3574a6aa74654d4e9a4e3dc94951c8d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"a70a8dfbde4f4c96bdacee11890084e5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"47bbbfa4a01340d5ba206f105056ad8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ec2a0f60e64d93a1281612264a2251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"542e4eff3e084788bdaa49f63015795e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"dfa50058a6f74b31a7b7bd0f3fc8cbb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a406b3ccac42688f05b0a11ea56f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99d3c24ad7d24557952c25ce1d9bef4c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"d1e606fdaf9048cc8c6fa4e8ba8972bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8036e705f054017bcbfea076d07d82b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd07ada36fa34b0a96b5d0642ebe750f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"24938a73ee994834adafaa85199dd6d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e19e4dbb32d240be91cd2738ec7647a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"668652f48d7145d2bab7b4c78f823a8c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"535646c17ccf4057810e5c8c67a0d120",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61536fcb4b1044119e118a845d1d4753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"a4d072034395438bb3756c52558eb718",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b83e69b96b4a4d06bbd96d5f1cd9585c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ab6aa07403446deabfc94a80e8cabb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40e0e595e9b5472c8169038df7fc8f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"ed1cb7445b364d53ad2dde7e44c17dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302748800c054cc4ae4225d403992671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94bcf2eaea94490494d5e9a4043fe49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8856a33b3a214c6bb182c4744e4b58bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30e970bd880247d187efe6474cc434c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5d09c9074d14852b1b8ba3dad14a371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"2b44100031bd4b07a4a9eca0441a43d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d603b64366d44d88ac83aac7e9f55965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb62ceb5680347f598005f38f6032b4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b86936120c345c2a3bfa23f00dceb21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"65873abf994047f58bd1a75aa98b3f48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18c5b9a6d34149bc85174951cefdb3a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"6ee1f9afac114d2481232c24ee2a5f20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9975bf8f7f74f2982945df01eb9fee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"a9673dbd8dc8400381ded868f461e9dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f17a4f43b0b14b32aed8fa1e7d0d8dd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af758a33a003474daaa83a47ff394356",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d33bbf6a3e34437da8657ce36836d6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"a17652ab9e0f4a799c661edc0877e371",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa3d0ddd404e4140b78ad67b7ad2b200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"672cb2356c544626b892cdcbb7a06998",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51aeb699126d44068b0fc47c096ea8b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0783f3fc3dd0403392809c5d3f5c3f61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08831ff16064f99a7f6c27f54bffa80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24ed09012d654433bb29ccb43a2540ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb54beeada3f4d519a87a3cb9ac41678",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04810277c4b642d790823fa02f54539b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1eeec0c7da2415182bc73dd6b78e70c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"deaef38bf34d4c149c0976f109af80f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d62c4ac8514fbab01a3fd81e55ac75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47375c26c8374e3bb544c43089dac3ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f95d8923754287bd18c472c5ac0c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75bf40fddcac4cbfb4a3b020928fbb78",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07c3fb3e748f448aad9d1d973be37218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"943fdab9051f43c19ea8160eb2064970",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3eae0986e414333807d49c9db1d8b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"ed118a6404224f44b7eea17d3b586b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74f84df7f73a48d797a8ad03bf6ff6f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"5f0f0d18a7134bbbbfa0c944f0729f9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d323cb60434f019c8638951b9cfd2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"c171208163ca42759b2fcf2526b45bcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61fac7dbb5b24f93bc7e0dceb7a4cb4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"f44cc2b1c7c442e197780e4c023e03fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":345,
              "y":134},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f41829444194a1abcaf7814fddba163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":345,
                  "y":134},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f74f0803a2149dcaa9f1d6571837354",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":258},
            "size":{
              "width":1766,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94908a24b2f64955929967d202f833f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":258},
                "size":{
                  "width":1766,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u69.png"}},
{
          "id":"08b1ac0acf394da3a66ced282d6e88df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"227f247c3b5047ec8808967c16edb65b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b678f1b6060f4d1f8a66c1065187b655",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":252,
              "y":195},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29af197a4d964ba687c824b5d9691017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":252,
                  "y":195},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca6bbf1878f4ce681e5c33be7c0ef1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":195},
            "size":{
              "width":200,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b15de8840cd84040abb0976646c68149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":195},
                "size":{
                  "width":200,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u77.png"}},
{
          "id":"a2826b4b37304805b2db651efaed8f7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":194},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724ba4e27ff2451584e1d9331d33ddf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":194},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u81.png"}},
{
          "id":"bf31a375dedf47bd9a26dd5e2285e13b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":199},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee7490864c841928e15d5a8416e0ccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":199},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u83.png"}},
{
          "id":"1f8b9b35a82c4695a3dfb7de2cd3bf40",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1082,
              "y":273},
            "size":{
              "width":221,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab82e09a3943434796a1329a9489f928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1082,
                  "y":273},
                "size":{
                  "width":221,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"779ca827a61949e8b994322650972e53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":354},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b6a654928b744579ca8e1512546216e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":354},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"99c07290ad3247cd9f29cd1fc7c7b090",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":399},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e692ff9e2b43ca91a495d5fe142334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":399},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"a2291351a7244ba59dea796dc3cd446d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"3af14d19d2704d59a461d849592b45f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":309,
              "y":365},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac4ae04a6084332b60cd29506d2490f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":309,
                  "y":365},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b2e720996f44029b403d321859cd1fa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"c22527975d5f4720b10fcee2c89e24d1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":905,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"06595e568d79427da46ff47a594ef871",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":985,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"1c14bf85fae64598ac935917b373026a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"f567ed8d73284911b90d881687088118",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"a5701d710e1e4f088943012c2616c3ad",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"2e87b038d51b42108a597a9ce0775d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":495,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f172d71a79b94a96bd92c24fbb61676a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":495,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82e4c21d89eb43d29f85e28064412664",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":750,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4695a141481a447981ba839fbf47db3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":750,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05c965ad4cec469fb1f0cb2d924ac556",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":928,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff7287c50e746cba66544cf7f28dddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":928,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"742025adbb894b11b472c17c1eedc7df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"728e667b334c4f90b0e0cc25715dfdb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"266f3955f8cd4e6cb87075c6a0b59e7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1116,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cdacbe3d388475d8b3d25ba853dcd0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1116,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f862cb376b5c41b6a01654e8170401c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1225,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"881755a5fd654aa987d0e7ca3eb113f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1225,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3201c1d080464cedb7900756026b7d31",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98adf67fd05847848fb35d0cfdd36fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a68e5610be9a46d1be83a64707bf453f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"89289e10e9c8456cb72f38312d435f55",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"b575a890561c4a7fa5292e37baaa20d6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"90d44974c9f74e79b7a8de337a56f8b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1003,
              "y":410},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cd1595ce4344e19b6802f81bd17b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1003,
                  "y":410},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d38bcf6c06b4fcd88f84223e35c76c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":289,
              "y":325},
            "size":{
              "width":209,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e80bb42793994e43adf332653bb2fb74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":289,
                  "y":325},
                "size":{
                  "width":209,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56cb161787a847adaf201dd687683cf8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520.30773925781,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"5fd08c3e4884441594f6fb7082fc4516",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"563ce151323c489785a5216814ef9d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF449513},
            "location":{
              "x":1806,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b19eaa848fd14252b8200e5def996caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF449513},
                "location":{
                  "x":1806,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u129.png"}},
{
          "id":"f550cf55482e49fab6741fbd08321c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1920,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e959eb9a42e3495282928ddebd6fb258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1920,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u131.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6f9a83462e344065b34d3f22da93df33":{
      "scriptId":"u0"},
    "cfaa59d40c37409ea9f783c17f5a91a7":{
      "scriptId":"u1"},
    "6f322668fc654482904276a935a403f9":{
      "scriptId":"u2"},
    "5359b1fe5a384f5f8d3c910f2b385456":{
      "scriptId":"u3"},
    "8d25c3e4a6464f45aaea636837c4f633":{
      "scriptId":"u4"},
    "3574a6aa74654d4e9a4e3dc94951c8d1":{
      "scriptId":"u5"},
    "a70a8dfbde4f4c96bdacee11890084e5":{
      "scriptId":"u6"},
    "47bbbfa4a01340d5ba206f105056ad8b":{
      "scriptId":"u7"},
    "23ec2a0f60e64d93a1281612264a2251":{
      "scriptId":"u8"},
    "542e4eff3e084788bdaa49f63015795e":{
      "scriptId":"u9"},
    "dfa50058a6f74b31a7b7bd0f3fc8cbb9":{
      "scriptId":"u10"},
    "33a406b3ccac42688f05b0a11ea56f38":{
      "scriptId":"u11"},
    "99d3c24ad7d24557952c25ce1d9bef4c":{
      "scriptId":"u12"},
    "d1e606fdaf9048cc8c6fa4e8ba8972bf":{
      "scriptId":"u13"},
    "e8036e705f054017bcbfea076d07d82b":{
      "scriptId":"u14"},
    "fd07ada36fa34b0a96b5d0642ebe750f":{
      "scriptId":"u15"},
    "24938a73ee994834adafaa85199dd6d9":{
      "scriptId":"u16"},
    "e19e4dbb32d240be91cd2738ec7647a7":{
      "scriptId":"u17"},
    "668652f48d7145d2bab7b4c78f823a8c":{
      "scriptId":"u18"},
    "535646c17ccf4057810e5c8c67a0d120":{
      "scriptId":"u19"},
    "61536fcb4b1044119e118a845d1d4753":{
      "scriptId":"u20"},
    "a4d072034395438bb3756c52558eb718":{
      "scriptId":"u21"},
    "b83e69b96b4a4d06bbd96d5f1cd9585c":{
      "scriptId":"u22"},
    "8ab6aa07403446deabfc94a80e8cabb0":{
      "scriptId":"u23"},
    "40e0e595e9b5472c8169038df7fc8f24":{
      "scriptId":"u24"},
    "ed1cb7445b364d53ad2dde7e44c17dc8":{
      "scriptId":"u25"},
    "302748800c054cc4ae4225d403992671":{
      "scriptId":"u26"},
    "94bcf2eaea94490494d5e9a4043fe49d":{
      "scriptId":"u27"},
    "8856a33b3a214c6bb182c4744e4b58bb":{
      "scriptId":"u28"},
    "30e970bd880247d187efe6474cc434c0":{
      "scriptId":"u29"},
    "c5d09c9074d14852b1b8ba3dad14a371":{
      "scriptId":"u30"},
    "2b44100031bd4b07a4a9eca0441a43d1":{
      "scriptId":"u31"},
    "d603b64366d44d88ac83aac7e9f55965":{
      "scriptId":"u32"},
    "eb62ceb5680347f598005f38f6032b4f":{
      "scriptId":"u33"},
    "5b86936120c345c2a3bfa23f00dceb21":{
      "scriptId":"u34"},
    "65873abf994047f58bd1a75aa98b3f48":{
      "scriptId":"u35"},
    "18c5b9a6d34149bc85174951cefdb3a3":{
      "scriptId":"u36"},
    "6ee1f9afac114d2481232c24ee2a5f20":{
      "scriptId":"u37"},
    "d9975bf8f7f74f2982945df01eb9fee9":{
      "scriptId":"u38"},
    "a9673dbd8dc8400381ded868f461e9dd":{
      "scriptId":"u39"},
    "f17a4f43b0b14b32aed8fa1e7d0d8dd7":{
      "scriptId":"u40"},
    "af758a33a003474daaa83a47ff394356":{
      "scriptId":"u41"},
    "d33bbf6a3e34437da8657ce36836d6c9":{
      "scriptId":"u42"},
    "a17652ab9e0f4a799c661edc0877e371":{
      "scriptId":"u43"},
    "aa3d0ddd404e4140b78ad67b7ad2b200":{
      "scriptId":"u44"},
    "672cb2356c544626b892cdcbb7a06998":{
      "scriptId":"u45"},
    "51aeb699126d44068b0fc47c096ea8b9":{
      "scriptId":"u46"},
    "0783f3fc3dd0403392809c5d3f5c3f61":{
      "scriptId":"u47"},
    "b08831ff16064f99a7f6c27f54bffa80":{
      "scriptId":"u48"},
    "24ed09012d654433bb29ccb43a2540ee":{
      "scriptId":"u49"},
    "bb54beeada3f4d519a87a3cb9ac41678":{
      "scriptId":"u50"},
    "04810277c4b642d790823fa02f54539b":{
      "scriptId":"u51"},
    "a1eeec0c7da2415182bc73dd6b78e70c":{
      "scriptId":"u52"},
    "deaef38bf34d4c149c0976f109af80f1":{
      "scriptId":"u53"},
    "96d62c4ac8514fbab01a3fd81e55ac75":{
      "scriptId":"u54"},
    "47375c26c8374e3bb544c43089dac3ae":{
      "scriptId":"u55"},
    "c5f95d8923754287bd18c472c5ac0c8c":{
      "scriptId":"u56"},
    "75bf40fddcac4cbfb4a3b020928fbb78":{
      "scriptId":"u57"},
    "07c3fb3e748f448aad9d1d973be37218":{
      "scriptId":"u58"},
    "943fdab9051f43c19ea8160eb2064970":{
      "scriptId":"u59"},
    "f3eae0986e414333807d49c9db1d8b64":{
      "scriptId":"u60"},
    "ed118a6404224f44b7eea17d3b586b2d":{
      "scriptId":"u61"},
    "74f84df7f73a48d797a8ad03bf6ff6f4":{
      "scriptId":"u62"},
    "5f0f0d18a7134bbbbfa0c944f0729f9e":{
      "scriptId":"u63"},
    "31d323cb60434f019c8638951b9cfd2b":{
      "scriptId":"u64"},
    "c171208163ca42759b2fcf2526b45bcf":{
      "scriptId":"u65"},
    "61fac7dbb5b24f93bc7e0dceb7a4cb4c":{
      "scriptId":"u66"},
    "f44cc2b1c7c442e197780e4c023e03fb":{
      "scriptId":"u67"},
    "8f41829444194a1abcaf7814fddba163":{
      "scriptId":"u68"},
    "7f74f0803a2149dcaa9f1d6571837354":{
      "scriptId":"u69"},
    "94908a24b2f64955929967d202f833f8":{
      "scriptId":"u70"},
    "08b1ac0acf394da3a66ced282d6e88df":{
      "scriptId":"u71"},
    "227f247c3b5047ec8808967c16edb65b":{
      "scriptId":"u72"},
    "b678f1b6060f4d1f8a66c1065187b655":{
      "scriptId":"u73"},
    "29af197a4d964ba687c824b5d9691017":{
      "scriptId":"u74"},
    "0ca6bbf1878f4ce681e5c33be7c0ef1e":{
      "scriptId":"u75"},
    "b15de8840cd84040abb0976646c68149":{
      "scriptId":"u76"},
    "a2826b4b37304805b2db651efaed8f7e":{
      "scriptId":"u77"},
    "724ba4e27ff2451584e1d9331d33ddf8":{
      "scriptId":"u78"},
    "bf31a375dedf47bd9a26dd5e2285e13b":{
      "scriptId":"u79"},
    "4ee7490864c841928e15d5a8416e0ccd":{
      "scriptId":"u80"},
    "1f8b9b35a82c4695a3dfb7de2cd3bf40":{
      "scriptId":"u81"},
    "ab82e09a3943434796a1329a9489f928":{
      "scriptId":"u82"},
    "779ca827a61949e8b994322650972e53":{
      "scriptId":"u83"},
    "4b6a654928b744579ca8e1512546216e":{
      "scriptId":"u84"},
    "99c07290ad3247cd9f29cd1fc7c7b090":{
      "scriptId":"u85"},
    "e5e692ff9e2b43ca91a495d5fe142334":{
      "scriptId":"u86"},
    "a2291351a7244ba59dea796dc3cd446d":{
      "scriptId":"u87"},
    "3af14d19d2704d59a461d849592b45f1":{
      "scriptId":"u88"},
    "5ac4ae04a6084332b60cd29506d2490f":{
      "scriptId":"u89"},
    "8b2e720996f44029b403d321859cd1fa":{
      "scriptId":"u90"},
    "c22527975d5f4720b10fcee2c89e24d1":{
      "scriptId":"u91"},
    "06595e568d79427da46ff47a594ef871":{
      "scriptId":"u92"},
    "1c14bf85fae64598ac935917b373026a":{
      "scriptId":"u93"},
    "f567ed8d73284911b90d881687088118":{
      "scriptId":"u94"},
    "a5701d710e1e4f088943012c2616c3ad":{
      "scriptId":"u95"},
    "2e87b038d51b42108a597a9ce0775d26":{
      "scriptId":"u96"},
    "f172d71a79b94a96bd92c24fbb61676a":{
      "scriptId":"u97"},
    "82e4c21d89eb43d29f85e28064412664":{
      "scriptId":"u98"},
    "4695a141481a447981ba839fbf47db3a":{
      "scriptId":"u99"},
    "05c965ad4cec469fb1f0cb2d924ac556":{
      "scriptId":"u100"},
    "2ff7287c50e746cba66544cf7f28dddc":{
      "scriptId":"u101"},
    "742025adbb894b11b472c17c1eedc7df":{
      "scriptId":"u102"},
    "728e667b334c4f90b0e0cc25715dfdb8":{
      "scriptId":"u103"},
    "266f3955f8cd4e6cb87075c6a0b59e7d":{
      "scriptId":"u104"},
    "4cdacbe3d388475d8b3d25ba853dcd0f":{
      "scriptId":"u105"},
    "f862cb376b5c41b6a01654e8170401c2":{
      "scriptId":"u106"},
    "881755a5fd654aa987d0e7ca3eb113f7":{
      "scriptId":"u107"},
    "3201c1d080464cedb7900756026b7d31":{
      "scriptId":"u108"},
    "98adf67fd05847848fb35d0cfdd36fd3":{
      "scriptId":"u109"},
    "a68e5610be9a46d1be83a64707bf453f":{
      "scriptId":"u110"},
    "89289e10e9c8456cb72f38312d435f55":{
      "scriptId":"u111"},
    "b575a890561c4a7fa5292e37baaa20d6":{
      "scriptId":"u112"},
    "90d44974c9f74e79b7a8de337a56f8b4":{
      "scriptId":"u113"},
    "77cd1595ce4344e19b6802f81bd17b9d":{
      "scriptId":"u114"},
    "6d38bcf6c06b4fcd88f84223e35c76c4":{
      "scriptId":"u115"},
    "e80bb42793994e43adf332653bb2fb74":{
      "scriptId":"u116"},
    "56cb161787a847adaf201dd687683cf8":{
      "scriptId":"u117"},
    "5fd08c3e4884441594f6fb7082fc4516":{
      "scriptId":"u118"},
    "563ce151323c489785a5216814ef9d01":{
      "scriptId":"u119"},
    "b19eaa848fd14252b8200e5def996caa":{
      "scriptId":"u120"},
    "f550cf55482e49fab6741fbd08321c66":{
      "scriptId":"u121"},
    "e959eb9a42e3495282928ddebd6fb258":{
      "scriptId":"u122"}}});