$axure.loadCurrentPage({
  "url":"销售明细表.html",
  "generationDate":new Date(1446432610481.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7ee694fbefd348a2adb8b2640db2f985",
    "type":"Axure:Page",
    "name":"销售明细表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38619d9992f9435d9cccf9d9b004d2c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29425db8043c4ad29f160c877ddc41e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"61e750c1850a46eb83f244d02beac04d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c4858d3d8be4f3593af61d4f1dc4a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4db7def9bc7543eaa356820606df1b75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dd91b5a026f4634801a40ff884987f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"7fd776ad7863494f93251aa606217d0c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"6568d337a0be499e89ce84dbb36f802e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b590c52ce945a1860deae723e84173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ed9629f3da841d3ade21f01252e40fc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"dcbb222d0f70486295a3d80ab71d5d96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cf72379ddbf4c00bfed01caf0b94a12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"011dbe47d3a54f0ab87d499a61f166a5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"af8c0474f6ef45bd9de88974370ca2a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ab6922bf31142efa9a40b4ad415b61a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a56a0bafd9cd4f4188db9302281ecd29",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"e381f24ff7824ad88c387006477ae0b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1403e4fbc252400c86c8767873c41350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4f170ebd2b34031859533d2647c2412",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"d41d975c937b4c978463764c80da2230",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9a7fb9b93d4c969a8835b1032b2172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"6c11f7522a234bb7958b2e1808319869",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04bc425e649d48d3ad8adc13811e947b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"938e53e26a0f446cb1a8c3e159ad309e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aadb41a67a24d64aef8ffadc528a43d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"8b55f04cadf84d7f9729fb621783c00c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0827ece04924dc2820c78100ab5fd05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"215325d6b2e646b184260d5f67440712",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20cee2f434bc4ce9a0d36048c6de357f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb58fbc9e2b743ea8a5fefa888727554",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b79784fb304426b1306bd1f143179b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"f5aa06fe8fec4c888b2e606b88efea88",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"103f46200b544332928437b7b0dcdf0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b04b7bc9e76e4c2b83cfef3f5e92ce25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73dde57de64f4f13a8ff241f4c78df97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"9282f1ff597a451b9817906640b49063",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b4e8a6e7f524da48c71b3c5f91790a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"6ff0c3ab8ace439c80694db9a1fc5e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f4cddfa3fee4806a881da4468243568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"701ddb3df9644ff893ab81b89d8c3513",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b89bf7051704b898224a03c1d5702dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"650b74b1409a4051bea8171fb990202a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26edd07713204a33ac509fd9c9380aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"01e7b07d05ae45a2bdd40e99d9965f90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b4e3ddf13d4754bdf93f6e3f630f76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"be98aa40f66b4ade8f252d9ba13111cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f4516c07d0c4d7aad03bb2c66d15b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88bf27e48f0f4b209c4740e58b7f6166",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34045be6e39946fc9369b823282fd616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"857beb884de04d0582f1bc10dd6dddc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4138f4e626442bcb697ffbdda390b09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0be1aac23744768a2c237eb30906d68",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cc0400540b14889b4fd14da6b6e7ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d7f9ce41d7444848e5616e35bce68bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0204b4c5f7495385d9952e2f1b37fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c8940e42a184120ab2e97fef07c53a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59de76c2309c4d008d2d66de9491122e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca6117379e045b680e2afd434a0ea9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5453e1c748974ee99df2192d81cff93a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3cffec5cc7943acaa46be0c6c950fed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d04e465f4b24f748faa2a49d252d2a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"77e1bb8fe3ce498c890b235c4b6e53c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"551eb71f69e940598be3fcbc01e75cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"711ef0729e534b04918d8bea6e87bb5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaaac986491246fca466b3afdd4ac2e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"b258a4cd6aea494f80ac3cd19d601304",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62ac5ae54d014299b7bb5a8e2deae90d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"b456c97ff7c740d6a6975c73278fe68d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":345,
              "y":134},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ca0fc8fec8d4db480105d78c909fdd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":345,
                  "y":134},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b9c5f5d7be347b7858efdf1b4c04124",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":258},
            "size":{
              "width":1766,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eee1b092b9144ec8c1e87f100063bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":258},
                "size":{
                  "width":1766,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u69.png"}},
{
          "id":"cbd742dcf2b540a6bb983d729eed02b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"961e9dfc5dd44709b35f1a2d58adfaae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4fe88dd066546ecb667a00dd7b6da2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":252,
              "y":195},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c6a63c824149ffaffc9fb110bf8946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":252,
                  "y":195},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d8cb6e33fe84ef090de4d968c329b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":226},
            "size":{
              "width":326,
              "height":325}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52ebb4b2c49f411895f8a7bab9116378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":226},
                "size":{
                  "width":326,
                  "height":325}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u75.png"}},
{
          "id":"ec3f372eeb944d7a95157f7d888280d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":195},
            "size":{
              "width":200,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"361af888e0c2479581fa5f5980f274b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":195},
                "size":{
                  "width":200,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u77.png"}},
{
          "id":"c54da82c503a4d2690d5785cc01b02c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":209},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb166d921424f798938bea800264932",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":209},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"2c9ef4a7deec483280190abacd278b58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":194},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e22a03babf478dbb74bc791ee29ea7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":194},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u81.png"}},
{
          "id":"6cc8f0b5ef7a4e1983acfad8538e8374",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":199},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3384ffaf20c64d369a38269684b9953d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":199},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u83.png"}},
{
          "id":"03c2af14f61f43989709d48ffe2a1dbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":374,
              "y":237},
            "size":{
              "width":46,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d12172f6274476918689f7a7b1fe06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":374,
                  "y":237},
                "size":{
                  "width":46,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce7e2e6550ad4c609c4129a1ff139bd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":250},
            "size":{
              "width":102,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e50cac3030c42eab7c0d4543e540f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":250},
                "size":{
                  "width":102,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u87.png"}},
{
          "id":"b7647b18b8fb4b8a846ab407f881615e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":255},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c80e7dd4083d4157b2720e31bf7ba09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":255},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}},
{
          "id":"b1e1bbc635804ec08dad5b5caa706162",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":574,
              "y":250},
            "size":{
              "width":102,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"805dc12a565949f88c9dc95de00991af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":574,
                  "y":250},
                "size":{
                  "width":102,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u87.png"}},
{
          "id":"c9a8f51ba9c24320941f77e5fbdfe44b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":255},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ac44259c33b456d8075776fb5ecd03f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":255},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}},
{
          "id":"13a19372472d41119c3ca29fdfcd0e73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":555,
              "y":254},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29739d4edfaa4d9fa47a37fd72bb2755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":555,
                  "y":254},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11a4aa0f84c44056bde8c92895f377ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":298},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ccfb234337a4e4c91e5b3f825d96314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":298},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"75f53ad0a50e4e0c8e67d4adb2ff4002",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":348},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be6340303be04e1d8961bccd6a78c31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":348},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"937d5374fe4c4d5785b54f8a823d25d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":408},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"695f1ee9b86f4816b082331f2fb1159a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":408},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"5dba63ae0a9d49619b91c24602a0a979",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":305},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42fd711cc504489d9dfb4f42dafff84e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":305},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"3246c2dfc9ac41288eb36d11761b6838",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":354},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55310ba015be40c9ac0a57ae0fa01c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":354},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"f2211c319a3f49ccb92006c569910968",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":416},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"714df773fb8745eb9ed5587c1898f40e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":416},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"b4a000c8d0ab484a83590b20a94bb3af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"400",
            "location":{
              "x":448,
              "y":378},
            "size":{
              "width":223,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0451e3fb53db4f78b017b8c98bf69e9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"400",
                "location":{
                  "x":448,
                  "y":378},
                "size":{
                  "width":223,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6c1ffab5f4241709e2bd14397c97dd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"400",
            "location":{
              "x":379,
              "y":514},
            "size":{
              "width":41,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d40841060f834fac8245230ce59e6a5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"400",
                "location":{
                  "x":379,
                  "y":514},
                "size":{
                  "width":41,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0128bf3d61d41f6af32d4b496c36a09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":514},
            "size":{
              "width":6,
              "height":12},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f0fbb1f78e48aaa9f611d0185894c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":514},
                "size":{
                  "width":6,
                  "height":12},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u113.png"}},
{
          "id":"8a42b8f5439d4cad88ffd6e5ffff5b4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":506},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f6d786921e4c54aa14b05ef87aa140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":566,
                  "y":506},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u115.png"}},
{
          "id":"d8fc1bde918d49ef9c520501998c2a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":626,
              "y":506},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49bd462f05fe4df698300807da7628c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":626,
                  "y":506},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u117.png"}},
{
          "id":"687ea08ab6f7492b8975f2d253b871a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1842,
              "y":200},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e07ae28ab8c424c8d34b0ca82df3b79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1842,
                  "y":200},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u115.png"}},
{
          "id":"9473ce9055a1430cbcb609644e9c1956",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":1902,
              "y":200},
            "size":{
              "width":54,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"412b05038a454b718ab33a310636175c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":1902,
                  "y":200},
                "size":{
                  "width":54,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u117.png"}},
{
          "id":"1e3ddf18a39c46e3b693e437b662d855",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":374,
              "y":455},
            "size":{
              "width":76,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41aaacb90c545449b9e61bdd3aa2c8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":374,
                  "y":455},
                "size":{
                  "width":76,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddfe19bb7dd9462fb9ad66fb4d2dc5ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":448,
              "y":452},
            "size":{
              "width":228,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60d9c82872e342f28fbdf128f070520f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":448,
                  "y":452},
                "size":{
                  "width":228,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u97.png"}},
{
          "id":"1c995e2e6812475d9e714ff28c17fc4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":460},
            "size":{
              "width":9,
              "height":8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea0cc6a48a84b3e829c81bafbe2539d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":460},
                "size":{
                  "width":9,
                  "height":8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"e0fc50eace104f30bb1206fe5ef797fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":490},
            "size":{
              "width":13,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46a50bea259a43b99ce5cd1d2ec6c315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":490},
                "size":{
                  "width":13,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/销售明细表/u129.png"}},
{
          "id":"1d0ffff460af415aa5a5a3f522aafd4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":395,
              "y":488},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b09e9c407534128a3cbf8694ac792dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":395,
                  "y":488},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"154a8fed3c03421f971ce78414e5fcab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":195},
            "size":{
              "width":396,
              "height":395}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce540c2e4384f928f904e4f6f3b590e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":195},
                "size":{
                  "width":396,
                  "height":395}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/销售明细表/u133.png"}},
{
          "id":"10ce952c9b9e4d04bfcd746709b483c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1227.5,
              "y":226},
            "size":{
              "width":480,
              "height":353}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82a2e927e3ab4a1e9afa6420a2364a9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1227.5,
                  "y":226},
                "size":{
                  "width":480,
                  "height":353}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/销售明细表/u135.png"}},
{
          "id":"027e1c03c5b24d78af19b3eb8253875a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":590},
            "size":{
              "width":408,
              "height":452}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f4dcc0e41c45aab76e0e3d27fa9767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":395,
                  "y":590},
                "size":{
                  "width":408,
                  "height":452}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/销售明细表/u137.png"}},
{
          "id":"c94650e98c6346fc9d244e3d9324d28a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":918.5,
              "y":479},
            "size":{
              "width":409,
              "height":451}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908aae4275db4e798e0b892c53f2c3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":918.5,
                  "y":479},
                "size":{
                  "width":409,
                  "height":451}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/销售明细表/u139.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "38619d9992f9435d9cccf9d9b004d2c2":{
      "scriptId":"u0"},
    "29425db8043c4ad29f160c877ddc41e0":{
      "scriptId":"u1"},
    "61e750c1850a46eb83f244d02beac04d":{
      "scriptId":"u2"},
    "8c4858d3d8be4f3593af61d4f1dc4a42":{
      "scriptId":"u3"},
    "4db7def9bc7543eaa356820606df1b75":{
      "scriptId":"u4"},
    "1dd91b5a026f4634801a40ff884987f0":{
      "scriptId":"u5"},
    "7fd776ad7863494f93251aa606217d0c":{
      "scriptId":"u6"},
    "6568d337a0be499e89ce84dbb36f802e":{
      "scriptId":"u7"},
    "70b590c52ce945a1860deae723e84173":{
      "scriptId":"u8"},
    "1ed9629f3da841d3ade21f01252e40fc":{
      "scriptId":"u9"},
    "dcbb222d0f70486295a3d80ab71d5d96":{
      "scriptId":"u10"},
    "3cf72379ddbf4c00bfed01caf0b94a12":{
      "scriptId":"u11"},
    "011dbe47d3a54f0ab87d499a61f166a5":{
      "scriptId":"u12"},
    "af8c0474f6ef45bd9de88974370ca2a2":{
      "scriptId":"u13"},
    "3ab6922bf31142efa9a40b4ad415b61a":{
      "scriptId":"u14"},
    "a56a0bafd9cd4f4188db9302281ecd29":{
      "scriptId":"u15"},
    "e381f24ff7824ad88c387006477ae0b2":{
      "scriptId":"u16"},
    "1403e4fbc252400c86c8767873c41350":{
      "scriptId":"u17"},
    "c4f170ebd2b34031859533d2647c2412":{
      "scriptId":"u18"},
    "d41d975c937b4c978463764c80da2230":{
      "scriptId":"u19"},
    "0c9a7fb9b93d4c969a8835b1032b2172":{
      "scriptId":"u20"},
    "6c11f7522a234bb7958b2e1808319869":{
      "scriptId":"u21"},
    "04bc425e649d48d3ad8adc13811e947b":{
      "scriptId":"u22"},
    "938e53e26a0f446cb1a8c3e159ad309e":{
      "scriptId":"u23"},
    "0aadb41a67a24d64aef8ffadc528a43d":{
      "scriptId":"u24"},
    "8b55f04cadf84d7f9729fb621783c00c":{
      "scriptId":"u25"},
    "d0827ece04924dc2820c78100ab5fd05":{
      "scriptId":"u26"},
    "215325d6b2e646b184260d5f67440712":{
      "scriptId":"u27"},
    "20cee2f434bc4ce9a0d36048c6de357f":{
      "scriptId":"u28"},
    "fb58fbc9e2b743ea8a5fefa888727554":{
      "scriptId":"u29"},
    "a7b79784fb304426b1306bd1f143179b":{
      "scriptId":"u30"},
    "f5aa06fe8fec4c888b2e606b88efea88":{
      "scriptId":"u31"},
    "103f46200b544332928437b7b0dcdf0d":{
      "scriptId":"u32"},
    "b04b7bc9e76e4c2b83cfef3f5e92ce25":{
      "scriptId":"u33"},
    "73dde57de64f4f13a8ff241f4c78df97":{
      "scriptId":"u34"},
    "9282f1ff597a451b9817906640b49063":{
      "scriptId":"u35"},
    "0b4e8a6e7f524da48c71b3c5f91790a0":{
      "scriptId":"u36"},
    "6ff0c3ab8ace439c80694db9a1fc5e69":{
      "scriptId":"u37"},
    "9f4cddfa3fee4806a881da4468243568":{
      "scriptId":"u38"},
    "701ddb3df9644ff893ab81b89d8c3513":{
      "scriptId":"u39"},
    "4b89bf7051704b898224a03c1d5702dd":{
      "scriptId":"u40"},
    "650b74b1409a4051bea8171fb990202a":{
      "scriptId":"u41"},
    "26edd07713204a33ac509fd9c9380aa3":{
      "scriptId":"u42"},
    "01e7b07d05ae45a2bdd40e99d9965f90":{
      "scriptId":"u43"},
    "09b4e3ddf13d4754bdf93f6e3f630f76":{
      "scriptId":"u44"},
    "be98aa40f66b4ade8f252d9ba13111cf":{
      "scriptId":"u45"},
    "5f4516c07d0c4d7aad03bb2c66d15b5f":{
      "scriptId":"u46"},
    "88bf27e48f0f4b209c4740e58b7f6166":{
      "scriptId":"u47"},
    "34045be6e39946fc9369b823282fd616":{
      "scriptId":"u48"},
    "857beb884de04d0582f1bc10dd6dddc5":{
      "scriptId":"u49"},
    "e4138f4e626442bcb697ffbdda390b09":{
      "scriptId":"u50"},
    "c0be1aac23744768a2c237eb30906d68":{
      "scriptId":"u51"},
    "1cc0400540b14889b4fd14da6b6e7ccc":{
      "scriptId":"u52"},
    "4d7f9ce41d7444848e5616e35bce68bb":{
      "scriptId":"u53"},
    "9e0204b4c5f7495385d9952e2f1b37fe":{
      "scriptId":"u54"},
    "3c8940e42a184120ab2e97fef07c53a4":{
      "scriptId":"u55"},
    "59de76c2309c4d008d2d66de9491122e":{
      "scriptId":"u56"},
    "0ca6117379e045b680e2afd434a0ea9e":{
      "scriptId":"u57"},
    "5453e1c748974ee99df2192d81cff93a":{
      "scriptId":"u58"},
    "a3cffec5cc7943acaa46be0c6c950fed":{
      "scriptId":"u59"},
    "3d04e465f4b24f748faa2a49d252d2a4":{
      "scriptId":"u60"},
    "77e1bb8fe3ce498c890b235c4b6e53c5":{
      "scriptId":"u61"},
    "551eb71f69e940598be3fcbc01e75cd4":{
      "scriptId":"u62"},
    "711ef0729e534b04918d8bea6e87bb5f":{
      "scriptId":"u63"},
    "aaaac986491246fca466b3afdd4ac2e1":{
      "scriptId":"u64"},
    "b258a4cd6aea494f80ac3cd19d601304":{
      "scriptId":"u65"},
    "62ac5ae54d014299b7bb5a8e2deae90d":{
      "scriptId":"u66"},
    "b456c97ff7c740d6a6975c73278fe68d":{
      "scriptId":"u67"},
    "7ca0fc8fec8d4db480105d78c909fdd1":{
      "scriptId":"u68"},
    "8b9c5f5d7be347b7858efdf1b4c04124":{
      "scriptId":"u69"},
    "5eee1b092b9144ec8c1e87f100063bae":{
      "scriptId":"u70"},
    "cbd742dcf2b540a6bb983d729eed02b0":{
      "scriptId":"u71"},
    "961e9dfc5dd44709b35f1a2d58adfaae":{
      "scriptId":"u72"},
    "f4fe88dd066546ecb667a00dd7b6da2e":{
      "scriptId":"u73"},
    "d8c6a63c824149ffaffc9fb110bf8946":{
      "scriptId":"u74"},
    "8d8cb6e33fe84ef090de4d968c329b32":{
      "scriptId":"u75"},
    "52ebb4b2c49f411895f8a7bab9116378":{
      "scriptId":"u76"},
    "ec3f372eeb944d7a95157f7d888280d4":{
      "scriptId":"u77"},
    "361af888e0c2479581fa5f5980f274b9":{
      "scriptId":"u78"},
    "c54da82c503a4d2690d5785cc01b02c0":{
      "scriptId":"u79"},
    "cdb166d921424f798938bea800264932":{
      "scriptId":"u80"},
    "2c9ef4a7deec483280190abacd278b58":{
      "scriptId":"u81"},
    "15e22a03babf478dbb74bc791ee29ea7":{
      "scriptId":"u82"},
    "6cc8f0b5ef7a4e1983acfad8538e8374":{
      "scriptId":"u83"},
    "3384ffaf20c64d369a38269684b9953d":{
      "scriptId":"u84"},
    "03c2af14f61f43989709d48ffe2a1dbf":{
      "scriptId":"u85"},
    "a6d12172f6274476918689f7a7b1fe06":{
      "scriptId":"u86"},
    "ce7e2e6550ad4c609c4129a1ff139bd3":{
      "scriptId":"u87"},
    "6e50cac3030c42eab7c0d4543e540f0c":{
      "scriptId":"u88"},
    "b7647b18b8fb4b8a846ab407f881615e":{
      "scriptId":"u89"},
    "c80e7dd4083d4157b2720e31bf7ba09a":{
      "scriptId":"u90"},
    "b1e1bbc635804ec08dad5b5caa706162":{
      "scriptId":"u91"},
    "805dc12a565949f88c9dc95de00991af":{
      "scriptId":"u92"},
    "c9a8f51ba9c24320941f77e5fbdfe44b":{
      "scriptId":"u93"},
    "6ac44259c33b456d8075776fb5ecd03f":{
      "scriptId":"u94"},
    "13a19372472d41119c3ca29fdfcd0e73":{
      "scriptId":"u95"},
    "29739d4edfaa4d9fa47a37fd72bb2755":{
      "scriptId":"u96"},
    "11a4aa0f84c44056bde8c92895f377ee":{
      "scriptId":"u97"},
    "5ccfb234337a4e4c91e5b3f825d96314":{
      "scriptId":"u98"},
    "75f53ad0a50e4e0c8e67d4adb2ff4002":{
      "scriptId":"u99"},
    "be6340303be04e1d8961bccd6a78c31a":{
      "scriptId":"u100"},
    "937d5374fe4c4d5785b54f8a823d25d8":{
      "scriptId":"u101"},
    "695f1ee9b86f4816b082331f2fb1159a":{
      "scriptId":"u102"},
    "5dba63ae0a9d49619b91c24602a0a979":{
      "scriptId":"u103"},
    "42fd711cc504489d9dfb4f42dafff84e":{
      "scriptId":"u104"},
    "3246c2dfc9ac41288eb36d11761b6838":{
      "scriptId":"u105"},
    "55310ba015be40c9ac0a57ae0fa01c51":{
      "scriptId":"u106"},
    "f2211c319a3f49ccb92006c569910968":{
      "scriptId":"u107"},
    "714df773fb8745eb9ed5587c1898f40e":{
      "scriptId":"u108"},
    "b4a000c8d0ab484a83590b20a94bb3af":{
      "scriptId":"u109"},
    "0451e3fb53db4f78b017b8c98bf69e9c":{
      "scriptId":"u110"},
    "a6c1ffab5f4241709e2bd14397c97dd5":{
      "scriptId":"u111"},
    "d40841060f834fac8245230ce59e6a5c":{
      "scriptId":"u112"},
    "f0128bf3d61d41f6af32d4b496c36a09":{
      "scriptId":"u113"},
    "d5f0fbb1f78e48aaa9f611d0185894c8":{
      "scriptId":"u114"},
    "8a42b8f5439d4cad88ffd6e5ffff5b4e":{
      "scriptId":"u115"},
    "54f6d786921e4c54aa14b05ef87aa140":{
      "scriptId":"u116"},
    "d8fc1bde918d49ef9c520501998c2a1b":{
      "scriptId":"u117"},
    "49bd462f05fe4df698300807da7628c2":{
      "scriptId":"u118"},
    "687ea08ab6f7492b8975f2d253b871a6":{
      "scriptId":"u119"},
    "2e07ae28ab8c424c8d34b0ca82df3b79":{
      "scriptId":"u120"},
    "9473ce9055a1430cbcb609644e9c1956":{
      "scriptId":"u121"},
    "412b05038a454b718ab33a310636175c":{
      "scriptId":"u122"},
    "1e3ddf18a39c46e3b693e437b662d855":{
      "scriptId":"u123"},
    "c41aaacb90c545449b9e61bdd3aa2c8e":{
      "scriptId":"u124"},
    "ddfe19bb7dd9462fb9ad66fb4d2dc5ff":{
      "scriptId":"u125"},
    "60d9c82872e342f28fbdf128f070520f":{
      "scriptId":"u126"},
    "1c995e2e6812475d9e714ff28c17fc4b":{
      "scriptId":"u127"},
    "dea0cc6a48a84b3e829c81bafbe2539d":{
      "scriptId":"u128"},
    "e0fc50eace104f30bb1206fe5ef797fc":{
      "scriptId":"u129"},
    "46a50bea259a43b99ce5cd1d2ec6c315":{
      "scriptId":"u130"},
    "1d0ffff460af415aa5a5a3f522aafd4f":{
      "scriptId":"u131"},
    "0b09e9c407534128a3cbf8694ac792dc":{
      "scriptId":"u132"},
    "154a8fed3c03421f971ce78414e5fcab":{
      "scriptId":"u133"},
    "fce540c2e4384f928f904e4f6f3b590e":{
      "scriptId":"u134"},
    "10ce952c9b9e4d04bfcd746709b483c4":{
      "scriptId":"u135"},
    "82a2e927e3ab4a1e9afa6420a2364a9e":{
      "scriptId":"u136"},
    "027e1c03c5b24d78af19b3eb8253875a":{
      "scriptId":"u137"},
    "f7f4dcc0e41c45aab76e0e3d27fa9767":{
      "scriptId":"u138"},
    "c94650e98c6346fc9d244e3d9324d28a":{
      "scriptId":"u139"},
    "908aae4275db4e798e0b892c53f2c3f8":{
      "scriptId":"u140"}}});