$axure.loadCurrentPage({
  "url":"新增账户.html",
  "generationDate":new Date(1446432605902.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"06b28b1e7ea045debe469fc0a6e8bab1",
    "type":"Axure:Page",
    "name":"新增账户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"218eadbd09db44de9bd731942e0a1eb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":629,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f540c7b465074b358a220dc3b91078f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":629,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u0.png"}},
{
          "id":"4b2951a67c1d48d98e943c3231e27b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":629,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bfb2d384fc6449b89d22941a9a5c590",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":629,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u2.png"}},
{
          "id":"492ce264ad8b4b1ba178a5ad8960d463",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":389,
              "y":60},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a13e0b4a5cf499f81d20a5b2664a146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":389,
                  "y":60},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28525e7c53e141e8a734cdc936f357a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":980,
              "y":55},
            "size":{
              "width":18,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682a2b79caa2452e8334c17e2350bb02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":980,
                  "y":55},
                "size":{
                  "width":18,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80bac9f0a4cb40cb91a20b7855906351",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":434},
            "size":{
              "width":629,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bda542b132f34f7e8b40cf68e55ec282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":434},
                "size":{
                  "width":629,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u8.png"}},
{
          "id":"6a5cd1f19a984d0d858c0932dc1da237",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":820,
              "y":441},
            "size":{
              "width":88,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e21d7242be1457aab641b6041dbab18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":820,
                  "y":441},
                "size":{
                  "width":88,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u10.png"}},
{
          "id":"ec121de935d5469f9a37e122356be5dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":930,
              "y":441},
            "size":{
              "width":61,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62486c7b656c48e4af82b9985f55a960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":930,
                  "y":441},
                "size":{
                  "width":61,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u12.png"}},
{
          "id":"a07e839757ab4f7da475ec423e47b104",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":408,
              "y":126},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b01e5472cf6b4966abfab55fb21efe8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":408,
                  "y":126},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"646081194f894dd3a775bea82f10d295",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":120},
            "size":{
              "width":188,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e6bb7cb6274edda4cf6eb35dd1784b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":502,
                  "y":120},
                "size":{
                  "width":188,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u16.png"}},
{
          "id":"f573e8c10e67463e98d745ef68a1cb8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":713,
              "y":126},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7e4a6935f047f99777b386fc36c342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":713,
                  "y":126},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c95a167ea3c48a9b8010025a2f19029",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":807,
              "y":120},
            "size":{
              "width":191,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e333d91c56341b9bb398f4de4201f5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":807,
                  "y":120},
                "size":{
                  "width":191,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u20.png"}},
{
          "id":"4f191c1a96224894b213e0c017c04bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":408,
              "y":177},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1f692f01fbb4c01b553a693696b4c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":408,
                  "y":177},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a24fc2e00c64f0a89913650900ae71c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":502,
              "y":171},
            "size":{
              "width":188,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8020d16db36c427f962b19613f70570e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":502,
                  "y":171},
                "size":{
                  "width":188,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u16.png"}},
{
          "id":"76760bbf91834eea9fbeca66937e10e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":713,
              "y":176},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32ae8c1fe95d4f0286b99df1c1c79689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":713,
                  "y":176},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d382cc1f656e4141b98b87a752a70d2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":807,
              "y":170},
            "size":{
              "width":191,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b62cb0e72c54f3ab46b4e7e28378b00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":807,
                  "y":170},
                "size":{
                  "width":191,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u20.png"}},
{
          "id":"e7f452da6ffe470f9cabb4e83ccea72a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":408,
              "y":238},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b1a56c33bd8417c94fa22b5394fc8d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":408,
                  "y":238},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea64c312b3654690b3cd74c8e97b0a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":232},
            "size":{
              "width":188,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f973bd502fe645e2a8bc86cfd11cb7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":502,
                  "y":232},
                "size":{
                  "width":188,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增账户/u16.png"}},
{
          "id":"b2f770162734407489dcaa402b7d4d7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":242},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c23421f17d0b425782a73c3ff7c33e12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":666,
                  "y":242},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"5947585d023348e096907dd83a57e665",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":179.5},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aad16ba8d7b4e28a66295e46f6692c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":666,
                  "y":179.5},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u83.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "218eadbd09db44de9bd731942e0a1eb5":{
      "scriptId":"u0"},
    "f540c7b465074b358a220dc3b91078f8":{
      "scriptId":"u1"},
    "4b2951a67c1d48d98e943c3231e27b6c":{
      "scriptId":"u2"},
    "6bfb2d384fc6449b89d22941a9a5c590":{
      "scriptId":"u3"},
    "492ce264ad8b4b1ba178a5ad8960d463":{
      "scriptId":"u4"},
    "0a13e0b4a5cf499f81d20a5b2664a146":{
      "scriptId":"u5"},
    "28525e7c53e141e8a734cdc936f357a8":{
      "scriptId":"u6"},
    "682a2b79caa2452e8334c17e2350bb02":{
      "scriptId":"u7"},
    "80bac9f0a4cb40cb91a20b7855906351":{
      "scriptId":"u8"},
    "bda542b132f34f7e8b40cf68e55ec282":{
      "scriptId":"u9"},
    "6a5cd1f19a984d0d858c0932dc1da237":{
      "scriptId":"u10"},
    "1e21d7242be1457aab641b6041dbab18":{
      "scriptId":"u11"},
    "ec121de935d5469f9a37e122356be5dd":{
      "scriptId":"u12"},
    "62486c7b656c48e4af82b9985f55a960":{
      "scriptId":"u13"},
    "a07e839757ab4f7da475ec423e47b104":{
      "scriptId":"u14"},
    "b01e5472cf6b4966abfab55fb21efe8d":{
      "scriptId":"u15"},
    "646081194f894dd3a775bea82f10d295":{
      "scriptId":"u16"},
    "c7e6bb7cb6274edda4cf6eb35dd1784b":{
      "scriptId":"u17"},
    "f573e8c10e67463e98d745ef68a1cb8b":{
      "scriptId":"u18"},
    "0d7e4a6935f047f99777b386fc36c342":{
      "scriptId":"u19"},
    "4c95a167ea3c48a9b8010025a2f19029":{
      "scriptId":"u20"},
    "9e333d91c56341b9bb398f4de4201f5a":{
      "scriptId":"u21"},
    "4f191c1a96224894b213e0c017c04bb5":{
      "scriptId":"u22"},
    "d1f692f01fbb4c01b553a693696b4c29":{
      "scriptId":"u23"},
    "0a24fc2e00c64f0a89913650900ae71c":{
      "scriptId":"u24"},
    "8020d16db36c427f962b19613f70570e":{
      "scriptId":"u25"},
    "76760bbf91834eea9fbeca66937e10e2":{
      "scriptId":"u26"},
    "32ae8c1fe95d4f0286b99df1c1c79689":{
      "scriptId":"u27"},
    "d382cc1f656e4141b98b87a752a70d2f":{
      "scriptId":"u28"},
    "2b62cb0e72c54f3ab46b4e7e28378b00":{
      "scriptId":"u29"},
    "e7f452da6ffe470f9cabb4e83ccea72a":{
      "scriptId":"u30"},
    "6b1a56c33bd8417c94fa22b5394fc8d0":{
      "scriptId":"u31"},
    "ea64c312b3654690b3cd74c8e97b0a57":{
      "scriptId":"u32"},
    "f973bd502fe645e2a8bc86cfd11cb7bd":{
      "scriptId":"u33"},
    "b2f770162734407489dcaa402b7d4d7d":{
      "scriptId":"u34"},
    "c23421f17d0b425782a73c3ff7c33e12":{
      "scriptId":"u35"},
    "5947585d023348e096907dd83a57e665":{
      "scriptId":"u36"},
    "7aad16ba8d7b4e28a66295e46f6692c4":{
      "scriptId":"u37"}}});