$axure.loadCurrentPage({
  "url":"新增客户类别.html",
  "generationDate":new Date(1446432606472.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"42d71e96c2944dd9979b5e88b05113ad",
    "type":"Axure:Page",
    "name":"新增客户类别",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a47e8166e324446aa94b7aea2021ac12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":252}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3fb8027cfdb4e9ea058cbecd0e8cea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":252}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u0.png"}},
{
          "id":"7106fad668044cdda56652c49fbc448c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c2c3158ccc54b72a7df640d7530cbc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u2.png"}},
{
          "id":"43727ede4d2e45e1916221b0fb9cd1c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":385,
              "y":56},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21849f22d9c46319a700cedc49d35b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":385,
                  "y":56},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5871f7fd2044013a9d862f72c65e976",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":728,
              "y":53},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f889fe90be2243eaafe8cc84681e733d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":728,
                  "y":53},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc823573e09a4a01acb196b6bf03ba68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":270},
            "size":{
              "width":360,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72fc5d46c9cf4bcbbfb8357bee8233ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":270},
                "size":{
                  "width":360,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u8.png"}},
{
          "id":"a53eb1f769724dabb926c6da23a03df1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":630,
              "y":274},
            "size":{
              "width":52,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85354b21b9614eaeb569b6d278bcc3ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":630,
                  "y":274},
                "size":{
                  "width":52,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u10.png"}},
{
          "id":"9700c72b0a6e4fd9944a48085408626d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":692,
              "y":274},
            "size":{
              "width":38,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d471c7d732d54136bf7c1f62307a48e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":692,
                  "y":274},
                "size":{
                  "width":38,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u12.png"}},
{
          "id":"e713b4a0923340f8afcdc44d8563af30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":170},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e8e9b8d6734f18ac01dd7ac4a055be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":170},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbb8281178294fc6a0e888d453c0adef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":165},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caab53d6995d45c0934aed0c26835072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":165},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a47e8166e324446aa94b7aea2021ac12":{
      "scriptId":"u0"},
    "a3fb8027cfdb4e9ea058cbecd0e8cea9":{
      "scriptId":"u1"},
    "7106fad668044cdda56652c49fbc448c":{
      "scriptId":"u2"},
    "0c2c3158ccc54b72a7df640d7530cbc2":{
      "scriptId":"u3"},
    "43727ede4d2e45e1916221b0fb9cd1c0":{
      "scriptId":"u4"},
    "e21849f22d9c46319a700cedc49d35b4":{
      "scriptId":"u5"},
    "c5871f7fd2044013a9d862f72c65e976":{
      "scriptId":"u6"},
    "f889fe90be2243eaafe8cc84681e733d":{
      "scriptId":"u7"},
    "fc823573e09a4a01acb196b6bf03ba68":{
      "scriptId":"u8"},
    "72fc5d46c9cf4bcbbfb8357bee8233ab":{
      "scriptId":"u9"},
    "a53eb1f769724dabb926c6da23a03df1":{
      "scriptId":"u10"},
    "85354b21b9614eaeb569b6d278bcc3ac":{
      "scriptId":"u11"},
    "9700c72b0a6e4fd9944a48085408626d":{
      "scriptId":"u12"},
    "d471c7d732d54136bf7c1f62307a48e9":{
      "scriptId":"u13"},
    "e713b4a0923340f8afcdc44d8563af30":{
      "scriptId":"u14"},
    "21e8e9b8d6734f18ac01dd7ac4a055be":{
      "scriptId":"u15"},
    "cbb8281178294fc6a0e888d453c0adef":{
      "scriptId":"u16"},
    "caab53d6995d45c0934aed0c26835072":{
      "scriptId":"u17"}}});