$axure.loadCurrentPage({
  "url":"销售汇总表（按商品）.html",
  "generationDate":new Date(1446432610994),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e08466b6d74049c2b1573501242389a5",
    "type":"Axure:Page",
    "name":"销售汇总表（按商品）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7378ecee965a4a76b981232f731c7fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a97ea54d193c42d09076fdf612875ec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"a1adf4c7f41043b280d8769e20dd49a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"814fac2540e04b4bb538feccb4fc85af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c0955091e0e419ebeb07405caf38173",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"281e8e9d32d84f9ea55a0f23e759785a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"336ce5dbe88a41e08e8fbc2e1047e976",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"f677ffe329164a21abad8b818c0f5052",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e3021f366f44b3bea4281e91447063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0abb1ebaef5b4b9d8158a7e7394811ef",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"a3407d38c9e14e3ab8703652c31dd199",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b468345aec1945c1866abb6113e8ffb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bb2e52ab08f4e6e82de1cee30b6b867",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"364a4e1221b849c692df3839df7081ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba11d23a1f5e45269b23f624a0275752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33f96180df6840b0a654d58894f3ca48",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"e838f08510bb4374b46aad322e754204",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009c2ec2e28043fbaaec517708a9b115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20ef617282db429caa20fcfe02db4775",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"6f84a994257b497681609e92a6b64148",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb0df179a854bba8c546642fd499d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"93fe18057acc41218f3f018ec87b5349",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"822113649b3f453fbae74cd9effa7692",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f0e271c38814eaabc7b25047c648b94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6146d854f9254ae8a6a72402ad82821f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"819c9081ab0d49bc99013e6fd5c598da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e8b4702944c4b09a8a60b5748ec788d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed686e742aa4477d94812c7d181f566a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4bc9941b6de43518250e0c0193c9b53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bd8ef45f5e142c795b518450230fd38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a172e4c87044e8e822e0cb35980e6a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"f9823703f1cf4cf38c2995b06d1f1270",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc88bed73524e1bae4960cd10590026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab342eb2a5d640448dd3fbbae070bdaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f19376ab1e9b40aeb548c7b18f916875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"2d90cdc730f14a18bc5ab858d45f54b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ec729a69f54420ad0d9629213b7e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"6b1468ca7b6c48928bc59f66f376b2d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506435d1426742b98caac3994d2ece62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"e8f81af4186d4562a2b9cd194386cbdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfa76a5bbefb4a70a97c972cf738f972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a2bc6c826a9403a933ff2809b009bdf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eca6abb4f8ea4f10a2aa8f518c53d0b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"424a76e0fbcc4b30a203cca5e8c696c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7d5ddfa6ed2464e91f4ce5b0efc3862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"b964baeb7adb4109bdd8c3e4e4ea90f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6e361a80c9b445c875792c0bccc5205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"842eac5462ca4ca9b5c4488593cd8ada",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fdafc938fbb4bfcb286969a661f2365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d66a2d04ede64a729c966179654fdfc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1fec87fe4964e72a03ce4ed051735e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7ea8bc1fb4b4b1d8cbbe5565a0f9cfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec3b6f86cdc4aa7b5f694ab1d0412af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d9701a3110b4c328d8923fd206f67b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b93200ed4b647b19180bc4a52809d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afff306e2a6f40bcb3f85d30cb04c49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c7cea99e1b48ac8c34ae5efe53787c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78911b5abb424883b65a6d703d1ea305",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55aa62d7abc540e89807fa1d2dcc001c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aab21c67f52a43eabcb70e1940954ea3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5090fddda0fa477cbab3130b208b5f20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"d47669a4dd3b4000966ee93b430cdd0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4010466f3ef44ab68f4e83646158b28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"3c3aa11f27424d28b3ace4b3f25de783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"972d7efff4ca4c0e8f2b6d75e6174284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"d472f7b1bc28485cbf479133d36f51de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85cc2175bd1343d6883931b59c35d257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"72cdc6840b9b4610ba5244b32bb2a813",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":345,
              "y":134},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06b97d04faf84231b36ccda76e56ac4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":345,
                  "y":134},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66f4c8d16e5d4f9ba6c1d56dc23313a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":258},
            "size":{
              "width":1766,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c1f8a61aade4bc4a20a51a8b88eb3f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":258},
                "size":{
                  "width":1766,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u69.png"}},
{
          "id":"ddfd342cfda14c138250e06ce6c46d3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e99150db1d49c985502583cd95ea08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d01889aaac3b4011bf485f731ff5fc54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":252,
              "y":195},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98c6864d44e44270a9dabaa6a7084389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":252,
                  "y":195},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35bdfd4a5ff145f58d54e3eaa225c197",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":195},
            "size":{
              "width":200,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2feda222540432b8e916e9292d8a090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":195},
                "size":{
                  "width":200,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u77.png"}},
{
          "id":"04c8094c28c34a249c74c62f7b22ded6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":194},
            "size":{
              "width":36,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7892f97878f24b648cdbb62a42a0255a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":194},
                "size":{
                  "width":36,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u81.png"}},
{
          "id":"068c362017794592a20f59fbcc50c2f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":199},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8270caed924d4c2d8c6ddd09bb6eab30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":199},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表/u83.png"}},
{
          "id":"5965c342ac7b4f588c9e964d38494de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1082,
              "y":273},
            "size":{
              "width":221,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab570b5ed7584f8d9b1486bd5481d184",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1082,
                  "y":273},
                "size":{
                  "width":221,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6864f6edcaf94536a6f3a0ae05bd2e2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":354},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c886eb24fe4964a291bea1946c4b65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":354},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"4e384ee26fb64fd48eb09f864de27d37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":399},
            "size":{
              "width":1691,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7ea6deb481d49d1a370efb260ce2af2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":399},
                "size":{
                  "width":1691,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u83.png"}},
{
          "id":"aad92e93f9764126bb7a6a4f30e089e7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"24b9a5e683cb44f8a7431304cd98394a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":309,
              "y":365},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a32dbf68b1c46b79906ba1965e9f7b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":309,
                  "y":365},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85a55a86a1494584847726a66c8783c2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"e0859ed261824736914a5f7820dde81e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":905,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"3d6aaa8e7e754b12943bff5d2ce096f9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":985,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"b241b27b0ae141a98954cb508432a870",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"934f0f5f083d4fc380387506978d5054",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"df9fba01f4d24f3da7699743b9f74a07",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"3c209d3bb9724ff091975afdfe93f654",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":495,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70fc036a2a2548d498fe455ae494b775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":495,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"567f0e7138644e1cada243709291a9e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":750,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff18de4d1b334fc3b0aa38f7f81f7565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":750,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"705e69a0caaa423d80dbe44b1992c071",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":928,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c198e812512401ba0c9e3897b0322c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":928,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdeffcd3950347b986d54b7cde6ccfc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1014,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e71e04ab1a549e283ee00e2c5f645ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1014,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"674ec50645fd4fd98cdc95d3637d7fb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1116,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e92fa8c9e64ab28f211bded6131b74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1116,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5325a7afb4a64f019d5c4a1dfe286c67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1225,
              "y":364},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1131ce14d9d548ceb646f608554bb585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1225,
                  "y":364},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47110155f1ee46bd89e073af633ac4ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":364},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd0a6a356a941d68e37eadb686b4b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":364},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae2ba5e1541a4373bc7c439c30adbc33",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"725eaaa41dbf47bbb7ae4b0fb8d6b18a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1182,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"34758d442a414c3c9158556fac0ac494",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"d392e74f41244cdbbbbbd38a447bbafb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":1003,
              "y":410},
            "size":{
              "width":67,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386118b287624302b45c9e7f6674bd01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":1003,
                  "y":410},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ad241126ec4abc8e6cab65459966e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":289,
              "y":325},
            "size":{
              "width":209,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db7644add974c65b2252260caf87c1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":289,
                  "y":325},
                "size":{
                  "width":209,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4400ed1b7bdd4d04ade9b296ed9c685d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1520.30773925781,
              "y":399},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"fdbde75708784222b0ee3087f74d1bbc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1328,
              "y":354},
            "size":{
              "width":10,
              "height":46}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购明细表_1/u87_line.png"}},
{
          "id":"84219f19d6c9472c8d386417aa4cd6b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF449513},
            "location":{
              "x":1806,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac8227031a44298a3e0b3c7b3d9cc84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF449513},
                "location":{
                  "x":1806,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u129.png"}},
{
          "id":"b899a10319f044e4a8cfea9352d0d770",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1920,
              "y":194},
            "size":{
              "width":84,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"211e12e4f58f4e93a5c473521fcd5b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1920,
                  "y":194},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购明细表_1/u131.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7378ecee965a4a76b981232f731c7fdc":{
      "scriptId":"u0"},
    "a97ea54d193c42d09076fdf612875ec4":{
      "scriptId":"u1"},
    "a1adf4c7f41043b280d8769e20dd49a7":{
      "scriptId":"u2"},
    "814fac2540e04b4bb538feccb4fc85af":{
      "scriptId":"u3"},
    "4c0955091e0e419ebeb07405caf38173":{
      "scriptId":"u4"},
    "281e8e9d32d84f9ea55a0f23e759785a":{
      "scriptId":"u5"},
    "336ce5dbe88a41e08e8fbc2e1047e976":{
      "scriptId":"u6"},
    "f677ffe329164a21abad8b818c0f5052":{
      "scriptId":"u7"},
    "a4e3021f366f44b3bea4281e91447063":{
      "scriptId":"u8"},
    "0abb1ebaef5b4b9d8158a7e7394811ef":{
      "scriptId":"u9"},
    "a3407d38c9e14e3ab8703652c31dd199":{
      "scriptId":"u10"},
    "b468345aec1945c1866abb6113e8ffb2":{
      "scriptId":"u11"},
    "3bb2e52ab08f4e6e82de1cee30b6b867":{
      "scriptId":"u12"},
    "364a4e1221b849c692df3839df7081ee":{
      "scriptId":"u13"},
    "ba11d23a1f5e45269b23f624a0275752":{
      "scriptId":"u14"},
    "33f96180df6840b0a654d58894f3ca48":{
      "scriptId":"u15"},
    "e838f08510bb4374b46aad322e754204":{
      "scriptId":"u16"},
    "009c2ec2e28043fbaaec517708a9b115":{
      "scriptId":"u17"},
    "20ef617282db429caa20fcfe02db4775":{
      "scriptId":"u18"},
    "6f84a994257b497681609e92a6b64148":{
      "scriptId":"u19"},
    "6cb0df179a854bba8c546642fd499d8a":{
      "scriptId":"u20"},
    "93fe18057acc41218f3f018ec87b5349":{
      "scriptId":"u21"},
    "822113649b3f453fbae74cd9effa7692":{
      "scriptId":"u22"},
    "9f0e271c38814eaabc7b25047c648b94":{
      "scriptId":"u23"},
    "6146d854f9254ae8a6a72402ad82821f":{
      "scriptId":"u24"},
    "819c9081ab0d49bc99013e6fd5c598da":{
      "scriptId":"u25"},
    "8e8b4702944c4b09a8a60b5748ec788d":{
      "scriptId":"u26"},
    "ed686e742aa4477d94812c7d181f566a":{
      "scriptId":"u27"},
    "b4bc9941b6de43518250e0c0193c9b53":{
      "scriptId":"u28"},
    "5bd8ef45f5e142c795b518450230fd38":{
      "scriptId":"u29"},
    "8a172e4c87044e8e822e0cb35980e6a4":{
      "scriptId":"u30"},
    "f9823703f1cf4cf38c2995b06d1f1270":{
      "scriptId":"u31"},
    "3cc88bed73524e1bae4960cd10590026":{
      "scriptId":"u32"},
    "ab342eb2a5d640448dd3fbbae070bdaa":{
      "scriptId":"u33"},
    "f19376ab1e9b40aeb548c7b18f916875":{
      "scriptId":"u34"},
    "2d90cdc730f14a18bc5ab858d45f54b1":{
      "scriptId":"u35"},
    "e7ec729a69f54420ad0d9629213b7e55":{
      "scriptId":"u36"},
    "6b1468ca7b6c48928bc59f66f376b2d0":{
      "scriptId":"u37"},
    "506435d1426742b98caac3994d2ece62":{
      "scriptId":"u38"},
    "e8f81af4186d4562a2b9cd194386cbdd":{
      "scriptId":"u39"},
    "cfa76a5bbefb4a70a97c972cf738f972":{
      "scriptId":"u40"},
    "5a2bc6c826a9403a933ff2809b009bdf":{
      "scriptId":"u41"},
    "eca6abb4f8ea4f10a2aa8f518c53d0b2":{
      "scriptId":"u42"},
    "424a76e0fbcc4b30a203cca5e8c696c9":{
      "scriptId":"u43"},
    "c7d5ddfa6ed2464e91f4ce5b0efc3862":{
      "scriptId":"u44"},
    "b964baeb7adb4109bdd8c3e4e4ea90f2":{
      "scriptId":"u45"},
    "f6e361a80c9b445c875792c0bccc5205":{
      "scriptId":"u46"},
    "842eac5462ca4ca9b5c4488593cd8ada":{
      "scriptId":"u47"},
    "8fdafc938fbb4bfcb286969a661f2365":{
      "scriptId":"u48"},
    "d66a2d04ede64a729c966179654fdfc7":{
      "scriptId":"u49"},
    "b1fec87fe4964e72a03ce4ed051735e5":{
      "scriptId":"u50"},
    "c7ea8bc1fb4b4b1d8cbbe5565a0f9cfe":{
      "scriptId":"u51"},
    "cec3b6f86cdc4aa7b5f694ab1d0412af":{
      "scriptId":"u52"},
    "0d9701a3110b4c328d8923fd206f67b3":{
      "scriptId":"u53"},
    "6b93200ed4b647b19180bc4a52809d88":{
      "scriptId":"u54"},
    "afff306e2a6f40bcb3f85d30cb04c49d":{
      "scriptId":"u55"},
    "e9c7cea99e1b48ac8c34ae5efe53787c":{
      "scriptId":"u56"},
    "78911b5abb424883b65a6d703d1ea305":{
      "scriptId":"u57"},
    "55aa62d7abc540e89807fa1d2dcc001c":{
      "scriptId":"u58"},
    "aab21c67f52a43eabcb70e1940954ea3":{
      "scriptId":"u59"},
    "5090fddda0fa477cbab3130b208b5f20":{
      "scriptId":"u60"},
    "d47669a4dd3b4000966ee93b430cdd0d":{
      "scriptId":"u61"},
    "4010466f3ef44ab68f4e83646158b28b":{
      "scriptId":"u62"},
    "3c3aa11f27424d28b3ace4b3f25de783":{
      "scriptId":"u63"},
    "972d7efff4ca4c0e8f2b6d75e6174284":{
      "scriptId":"u64"},
    "d472f7b1bc28485cbf479133d36f51de":{
      "scriptId":"u65"},
    "85cc2175bd1343d6883931b59c35d257":{
      "scriptId":"u66"},
    "72cdc6840b9b4610ba5244b32bb2a813":{
      "scriptId":"u67"},
    "06b97d04faf84231b36ccda76e56ac4f":{
      "scriptId":"u68"},
    "66f4c8d16e5d4f9ba6c1d56dc23313a1":{
      "scriptId":"u69"},
    "5c1f8a61aade4bc4a20a51a8b88eb3f2":{
      "scriptId":"u70"},
    "ddfd342cfda14c138250e06ce6c46d3a":{
      "scriptId":"u71"},
    "14e99150db1d49c985502583cd95ea08":{
      "scriptId":"u72"},
    "d01889aaac3b4011bf485f731ff5fc54":{
      "scriptId":"u73"},
    "98c6864d44e44270a9dabaa6a7084389":{
      "scriptId":"u74"},
    "35bdfd4a5ff145f58d54e3eaa225c197":{
      "scriptId":"u75"},
    "a2feda222540432b8e916e9292d8a090":{
      "scriptId":"u76"},
    "04c8094c28c34a249c74c62f7b22ded6":{
      "scriptId":"u77"},
    "7892f97878f24b648cdbb62a42a0255a":{
      "scriptId":"u78"},
    "068c362017794592a20f59fbcc50c2f9":{
      "scriptId":"u79"},
    "8270caed924d4c2d8c6ddd09bb6eab30":{
      "scriptId":"u80"},
    "5965c342ac7b4f588c9e964d38494de6":{
      "scriptId":"u81"},
    "ab570b5ed7584f8d9b1486bd5481d184":{
      "scriptId":"u82"},
    "6864f6edcaf94536a6f3a0ae05bd2e2c":{
      "scriptId":"u83"},
    "57c886eb24fe4964a291bea1946c4b65":{
      "scriptId":"u84"},
    "4e384ee26fb64fd48eb09f864de27d37":{
      "scriptId":"u85"},
    "f7ea6deb481d49d1a370efb260ce2af2":{
      "scriptId":"u86"},
    "aad92e93f9764126bb7a6a4f30e089e7":{
      "scriptId":"u87"},
    "24b9a5e683cb44f8a7431304cd98394a":{
      "scriptId":"u88"},
    "2a32dbf68b1c46b79906ba1965e9f7b9":{
      "scriptId":"u89"},
    "85a55a86a1494584847726a66c8783c2":{
      "scriptId":"u90"},
    "e0859ed261824736914a5f7820dde81e":{
      "scriptId":"u91"},
    "3d6aaa8e7e754b12943bff5d2ce096f9":{
      "scriptId":"u92"},
    "b241b27b0ae141a98954cb508432a870":{
      "scriptId":"u93"},
    "934f0f5f083d4fc380387506978d5054":{
      "scriptId":"u94"},
    "df9fba01f4d24f3da7699743b9f74a07":{
      "scriptId":"u95"},
    "3c209d3bb9724ff091975afdfe93f654":{
      "scriptId":"u96"},
    "70fc036a2a2548d498fe455ae494b775":{
      "scriptId":"u97"},
    "567f0e7138644e1cada243709291a9e9":{
      "scriptId":"u98"},
    "ff18de4d1b334fc3b0aa38f7f81f7565":{
      "scriptId":"u99"},
    "705e69a0caaa423d80dbe44b1992c071":{
      "scriptId":"u100"},
    "7c198e812512401ba0c9e3897b0322c2":{
      "scriptId":"u101"},
    "fdeffcd3950347b986d54b7cde6ccfc0":{
      "scriptId":"u102"},
    "8e71e04ab1a549e283ee00e2c5f645ed":{
      "scriptId":"u103"},
    "674ec50645fd4fd98cdc95d3637d7fb0":{
      "scriptId":"u104"},
    "e2e92fa8c9e64ab28f211bded6131b74":{
      "scriptId":"u105"},
    "5325a7afb4a64f019d5c4a1dfe286c67":{
      "scriptId":"u106"},
    "1131ce14d9d548ceb646f608554bb585":{
      "scriptId":"u107"},
    "47110155f1ee46bd89e073af633ac4ae":{
      "scriptId":"u108"},
    "cbd0a6a356a941d68e37eadb686b4b0a":{
      "scriptId":"u109"},
    "ae2ba5e1541a4373bc7c439c30adbc33":{
      "scriptId":"u110"},
    "725eaaa41dbf47bbb7ae4b0fb8d6b18a":{
      "scriptId":"u111"},
    "34758d442a414c3c9158556fac0ac494":{
      "scriptId":"u112"},
    "d392e74f41244cdbbbbbd38a447bbafb":{
      "scriptId":"u113"},
    "386118b287624302b45c9e7f6674bd01":{
      "scriptId":"u114"},
    "f6ad241126ec4abc8e6cab65459966e2":{
      "scriptId":"u115"},
    "8db7644add974c65b2252260caf87c1f":{
      "scriptId":"u116"},
    "4400ed1b7bdd4d04ade9b296ed9c685d":{
      "scriptId":"u117"},
    "fdbde75708784222b0ee3087f74d1bbc":{
      "scriptId":"u118"},
    "84219f19d6c9472c8d386417aa4cd6b9":{
      "scriptId":"u119"},
    "2ac8227031a44298a3e0b3c7b3d9cc84":{
      "scriptId":"u120"},
    "b899a10319f044e4a8cfea9352d0d770":{
      "scriptId":"u121"},
    "211e12e4f58f4e93a5c473521fcd5b1b":{
      "scriptId":"u122"}}});