$axure.loadCurrentPage({
  "url":"商品收发汇总表.html",
  "generationDate":new Date(1446432611374.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7f3a326ed773458698ede21ee037b0c6",
    "type":"Axure:Page",
    "name":"商品收发汇总表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62154cdd9bfd422b89b0f6e8e39576b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-220,
              "y":128},
            "size":{
              "width":1819,
              "height":623}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704f49cf60f04eec91eb72e85778dff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-220,
                  "y":128},
                "size":{
                  "width":1819,
                  "height":623}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品收发汇总表/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "62154cdd9bfd422b89b0f6e8e39576b8":{
      "scriptId":"u0"},
    "704f49cf60f04eec91eb72e85778dff5":{
      "scriptId":"u1"}}});