$axure.loadCurrentPage({
  "url":"新增商品类别.html",
  "generationDate":new Date(1446432606757.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"caa0efe98f7c4be79f70f5c6f5da2df9",
    "type":"Axure:Page",
    "name":"新增商品类别",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b446e6b32c542b0bb519f5f16d0c8f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":252}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"877b5dffa11d4d579dedf0185526fd3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":252}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u0.png"}},
{
          "id":"e57f185c8d964f03a13b9fcbc74498d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa925f0fbae4a07959389917c145f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u2.png"}},
{
          "id":"c8b212ca035644f8834c36d8ae9d1598",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":385,
              "y":56},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ffe7cc0e8b440128904d9a892c63d09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":385,
                  "y":56},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70aba63e3ee24690ad4468b5ee6c6f77",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":728,
              "y":53},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09a55bc66cb04e9ca64c872066e394ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":728,
                  "y":53},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50f77053c7154a54a398d8e0e60cfaac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":270},
            "size":{
              "width":360,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d93972022ff43458bf04c9307148bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":270},
                "size":{
                  "width":360,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u8.png"}},
{
          "id":"18f8878d63664784a4e181272192a333",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3571BC},
            "location":{
              "x":630,
              "y":274},
            "size":{
              "width":52,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7371ead26627450ca87062588db3d3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3571BC},
                "location":{
                  "x":630,
                  "y":274},
                "size":{
                  "width":52,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u10.png"}},
{
          "id":"1c71d27b20ee470c82cf190f6fa94e27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":692,
              "y":274},
            "size":{
              "width":38,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd0e0483b6984416b12629ca7a4244c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":692,
                  "y":274},
                "size":{
                  "width":38,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增仓库/u12.png"}},
{
          "id":"5a938491b44044f082016da325ecf806",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":170},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d46ff993f18a4a0f8553fb5118dec1f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":170},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64802fe18e614d0bafa0eaa403a8eac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":165},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02fd0b5b5b0f49a7a97f07c436b6af08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":165},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3b446e6b32c542b0bb519f5f16d0c8f7":{
      "scriptId":"u0"},
    "877b5dffa11d4d579dedf0185526fd3b":{
      "scriptId":"u1"},
    "e57f185c8d964f03a13b9fcbc74498d9":{
      "scriptId":"u2"},
    "aaa925f0fbae4a07959389917c145f70":{
      "scriptId":"u3"},
    "c8b212ca035644f8834c36d8ae9d1598":{
      "scriptId":"u4"},
    "3ffe7cc0e8b440128904d9a892c63d09":{
      "scriptId":"u5"},
    "70aba63e3ee24690ad4468b5ee6c6f77":{
      "scriptId":"u6"},
    "09a55bc66cb04e9ca64c872066e394ab":{
      "scriptId":"u7"},
    "50f77053c7154a54a398d8e0e60cfaac":{
      "scriptId":"u8"},
    "0d93972022ff43458bf04c9307148bff":{
      "scriptId":"u9"},
    "18f8878d63664784a4e181272192a333":{
      "scriptId":"u10"},
    "7371ead26627450ca87062588db3d3dd":{
      "scriptId":"u11"},
    "1c71d27b20ee470c82cf190f6fa94e27":{
      "scriptId":"u12"},
    "dd0e0483b6984416b12629ca7a4244c2":{
      "scriptId":"u13"},
    "5a938491b44044f082016da325ecf806":{
      "scriptId":"u14"},
    "d46ff993f18a4a0f8553fb5118dec1f8":{
      "scriptId":"u15"},
    "64802fe18e614d0bafa0eaa403a8eac0":{
      "scriptId":"u16"},
    "02fd0b5b5b0f49a7a97f07c436b6af08":{
      "scriptId":"u17"}}});