$axure.loadCurrentPage({
  "url":"现金银行报表.html",
  "generationDate":new Date(1446432611405.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"112f2a09c0c74cef95782aefadac5c02",
    "type":"Axure:Page",
    "name":"现金银行报表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"78498d82fcb14a6a8d2c4b41966b3deb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-219,
              "y":2},
            "size":{
              "width":1816,
              "height":876}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d841f9ba0514cc3905fcd2e9f7443d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-219,
                  "y":2},
                "size":{
                  "width":1816,
                  "height":876}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/现金银行报表/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "78498d82fcb14a6a8d2c4b41966b3deb":{
      "scriptId":"u0"},
    "5d841f9ba0514cc3905fcd2e9f7443d0":{
      "scriptId":"u1"}}});