$axure.loadCurrentPage({
  "url":"计量单位.html",
  "generationDate":new Date(1446432607265.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1588f7caef114b2f9c7ddeead613abc5",
    "type":"Axure:Page",
    "name":"计量单位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c28e9234e793482fb394b9e4ccabfbfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dfc271ba7e64919860030bb4c301d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"414f8bcc61144c1f81be7bd9a24e687f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":240,
              "y":66},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9afcb9491c244bbbde32f23658c74a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":240,
                  "y":66},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"425fa2b228304ad99820786d25098d47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1300,
              "y":68},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6f5c4fbd6b54005b8a8396d8dd1703d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1300,
                  "y":68},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"609097e447c34e188503dd10967970e6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1363,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"74e13b01dc5a4d94bbf800a17935a3c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1386,
              "y":66},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a351037cac441969523d5775cf7af3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1386,
                  "y":66},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6300898572e469998b8ffaab5c85f84",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1560,
              "y":68},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"db4f478bcb6f4a3788fdf2c982a3666a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1580,
              "y":66},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f25d6ae26de240cb803f76b27b439765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1580,
                  "y":66},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"001ed6d6477a482584fe5da32db941f5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1770,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"b477ef68e9c2410b96f8a48f4263ce1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1791,
              "y":66},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcdbc5a071cd47aca4f1fae2528368d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1791,
                  "y":66},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"048997d8278445b884accc487a75a47f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1874,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"c64f139e2066486ebc56af89631e3591",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1898,
              "y":66},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4298c7e608514e1c862f9fbfaea4e8b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1898,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afe23a17c88a406891d9a7e14ecc3567",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1944,
              "y":66},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"9cba223ba9a945858288a793b3459317",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1968,
              "y":66},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48d2b5940af2458fafde96fbadf6f4bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1968,
                  "y":66},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"f20f0131201c4e23bb045591f92782a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":243,
              "y":163},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b265851b0d4a6cae739f8764f0129d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":243,
                  "y":163},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2acf15d6a2f344cfbb72b2554c8e0f11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":127},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbec67f1769c4306a639b76ae1e03b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":127},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"d2536cecd8b94694a79b3dd597d567f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":132},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b298445d469c48ecbe9d7b82e9d3c8fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":132},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bf366af6d584a72b0044ce0f572cb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":161},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf8f29716eb46c99879fca9ee360afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":161},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4af615a2e2d046aeb4ff1562c74a613e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":162},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87f3ce30374943f595907eb3adf22b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":162},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"234f452bb415467596dab43f38c89239",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1723,
              "y":164},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031adadb0f6142d6affb59e095a05c98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1723,
                  "y":164},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70700261a620407797781d647c87779f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1806,
              "y":161},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a477ca966fc046068b549ff9ee393a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1806,
                  "y":161},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"40c1efe8399e4375856ccd6af73c7e0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":1985,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b69237db4a4368a79eeaffa888b02a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1985,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"05b7b8ecf26d4d41aa7ea106310ffad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1755,
              "y":768},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb76c2342d2544a2ada89fafa742fe27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1755,
                  "y":768},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"90bdc728fd1647bb8301be55dc13c982",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1800,
              "y":827},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c78168754b6741dfa7b50147416bd12d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1800,
                  "y":827},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"905d6e15be2c4841ae4f0c8870214b00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1762,
              "y":794},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f454d005d14f1d868484c93fab0b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1762,
                  "y":794},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"ce1520862dbf4d29bb81fa5eb95f9426",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fc00a34d934ce38e41a6d4fb754b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":120,
                  "y":50},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"53f37a6c07cc4670be923e734b0f1a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":136},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0504cf364d0a49eebaea93f52c4fe38e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":136},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7071950570a45b9a5c133504e29fc61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":258},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba043ca83e14de49cb3a6b033cf6383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":258},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c4c5d72573e40daacb8a463fa440940",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":386},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b108193b744947f89dbd6248b1c0c7db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":386},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c391a3299eb64ab5b027782f7908a982",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":514},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27251d85e56a4bf78935cc74aac64ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":514},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9acb50b00994feb8b23ebd4ea1f9795",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":640},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4bc620bfd1432da200ac5e07e2fcf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":640},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d88d581df2c04714a7ae476554061912",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":757},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a0fe64d952e4234be45fc074ef7cb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":757},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de99f6dc81004eee839525c901076d71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":864},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2bf16881a9408192bd0515eb493289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":864},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"071e53330077458894ee4761759be5f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":161},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79db3af9a47241bfb1bd2787475b2388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":161},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"7a30813dc4b74b78991a5d23615a0f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":329,
              "y":117},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9618324fcf54ed9a866aa6e13c04a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":329,
                  "y":117},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"7d2474e7a05f44be93fa7439dc3e2d64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":127},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f521b47d11bb40949230593dae35de29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":127},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"cb79147f8a204de79e62f1fe8d13ccb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":139},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b205e81f35141b2bffd56a59081b6d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":139},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"9631667bd8e44a398b6c6835ec558186",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":347,
              "y":133},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b813d87e396046bdbc9f6149b0816a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":347,
                  "y":133},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1481557b85245caa6d003b9b82304e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":230},
            "size":{
              "width":1766,
              "height":688}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db94eba38ed41eeab730aab677bd819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":230},
                "size":{
                  "width":1766,
                  "height":688}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u69.png"}},
{
          "id":"4770f458008d41f8a66c79697fc07f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":429,
              "y":111},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dd49f8ea78146239dce2164c85c5b83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":429,
                  "y":111},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73e09c7f99de47d1817b9602d9d4114b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":186},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7864147390944fe4bd8ad14f74aafede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":186},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccfa1a3c0fcb416d91098d636ec193a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":240,
              "y":230},
            "size":{
              "width":1766,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5746dd67e1dc4826a896502502758299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":240,
                  "y":230},
                "size":{
                  "width":1766,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u75.png"}},
{
          "id":"ccea7ef6677d4400b03a088d80ddec4f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":230},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"2195889b3a254fb5b677700005349610",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":230},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"3791579e7988465e8b6eb6940fbfdf19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":416,
              "y":237},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc01327fa4764c54b3fc1e39d2fb5a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":416,
                  "y":237},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cba75f0b421d42e7ba599f86c643cb64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":630,
              "y":237},
            "size":{
              "width":45,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9755fc856748099a75d4a498e04823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":630,
                  "y":237},
                "size":{
                  "width":45,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76b09f4cb3a8491f9d762b31bb4fcb0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":269},
            "size":{
              "width":470,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7913a1f11d144088fdf385dce8222f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":269},
                "size":{
                  "width":470,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商类别/u83.png"}},
{
          "id":"847b373cb89c46498c0d9658db311142",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":269},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"498b4cb35e714d2382838f7cb1de4ccc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":704,
              "y":269},
            "size":{
              "width":10,
              "height":40}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/仓库管理/u77_line.png"}},
{
          "id":"e33b289246954245aaba6772fab6145c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":276},
            "size":{
              "width":19,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d6dc8739f2b490eba22e7f2d570506d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":276},
                "size":{
                  "width":19,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u178.png"}},
{
          "id":"8d1fcf51bfaf41eeb574f4ff5c9cb75a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":280},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dadf447b89a446f58e2cec88296bd3a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":623,
                  "y":280},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u96.png"}},
{
          "id":"732d0566735840ec975f3ceaf11d00a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":416,
              "y":277},
            "size":{
              "width":21,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce8cf0211d2484186889931637e1915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":416,
                  "y":277},
                "size":{
                  "width":21,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdd78de4940642bf85af2e889e0754f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1785,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94ca59a54014637ae649b339d9b770b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1785,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"ae62902f95da4e688f2266e0393d1d47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1910,
              "y":174},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4e00854e98245da8953b9dd2da1fe39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1910,
                  "y":174},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c28e9234e793482fb394b9e4ccabfbfd":{
      "scriptId":"u0"},
    "5dfc271ba7e64919860030bb4c301d73":{
      "scriptId":"u1"},
    "414f8bcc61144c1f81be7bd9a24e687f":{
      "scriptId":"u2"},
    "c9afcb9491c244bbbde32f23658c74a8":{
      "scriptId":"u3"},
    "425fa2b228304ad99820786d25098d47":{
      "scriptId":"u4"},
    "c6f5c4fbd6b54005b8a8396d8dd1703d":{
      "scriptId":"u5"},
    "609097e447c34e188503dd10967970e6":{
      "scriptId":"u6"},
    "74e13b01dc5a4d94bbf800a17935a3c0":{
      "scriptId":"u7"},
    "1a351037cac441969523d5775cf7af3e":{
      "scriptId":"u8"},
    "e6300898572e469998b8ffaab5c85f84":{
      "scriptId":"u9"},
    "db4f478bcb6f4a3788fdf2c982a3666a":{
      "scriptId":"u10"},
    "f25d6ae26de240cb803f76b27b439765":{
      "scriptId":"u11"},
    "001ed6d6477a482584fe5da32db941f5":{
      "scriptId":"u12"},
    "b477ef68e9c2410b96f8a48f4263ce1f":{
      "scriptId":"u13"},
    "dcdbc5a071cd47aca4f1fae2528368d5":{
      "scriptId":"u14"},
    "048997d8278445b884accc487a75a47f":{
      "scriptId":"u15"},
    "c64f139e2066486ebc56af89631e3591":{
      "scriptId":"u16"},
    "4298c7e608514e1c862f9fbfaea4e8b0":{
      "scriptId":"u17"},
    "afe23a17c88a406891d9a7e14ecc3567":{
      "scriptId":"u18"},
    "9cba223ba9a945858288a793b3459317":{
      "scriptId":"u19"},
    "48d2b5940af2458fafde96fbadf6f4bf":{
      "scriptId":"u20"},
    "f20f0131201c4e23bb045591f92782a2":{
      "scriptId":"u21"},
    "08b265851b0d4a6cae739f8764f0129d":{
      "scriptId":"u22"},
    "2acf15d6a2f344cfbb72b2554c8e0f11":{
      "scriptId":"u23"},
    "fbec67f1769c4306a639b76ae1e03b78":{
      "scriptId":"u24"},
    "d2536cecd8b94694a79b3dd597d567f9":{
      "scriptId":"u25"},
    "b298445d469c48ecbe9d7b82e9d3c8fa":{
      "scriptId":"u26"},
    "3bf366af6d584a72b0044ce0f572cb0f":{
      "scriptId":"u27"},
    "ebf8f29716eb46c99879fca9ee360afd":{
      "scriptId":"u28"},
    "4af615a2e2d046aeb4ff1562c74a613e":{
      "scriptId":"u29"},
    "87f3ce30374943f595907eb3adf22b86":{
      "scriptId":"u30"},
    "234f452bb415467596dab43f38c89239":{
      "scriptId":"u31"},
    "031adadb0f6142d6affb59e095a05c98":{
      "scriptId":"u32"},
    "70700261a620407797781d647c87779f":{
      "scriptId":"u33"},
    "a477ca966fc046068b549ff9ee393a2f":{
      "scriptId":"u34"},
    "40c1efe8399e4375856ccd6af73c7e0e":{
      "scriptId":"u35"},
    "e9b69237db4a4368a79eeaffa888b02a":{
      "scriptId":"u36"},
    "05b7b8ecf26d4d41aa7ea106310ffad7":{
      "scriptId":"u37"},
    "fb76c2342d2544a2ada89fafa742fe27":{
      "scriptId":"u38"},
    "90bdc728fd1647bb8301be55dc13c982":{
      "scriptId":"u39"},
    "c78168754b6741dfa7b50147416bd12d":{
      "scriptId":"u40"},
    "905d6e15be2c4841ae4f0c8870214b00":{
      "scriptId":"u41"},
    "c8f454d005d14f1d868484c93fab0b14":{
      "scriptId":"u42"},
    "ce1520862dbf4d29bb81fa5eb95f9426":{
      "scriptId":"u43"},
    "e9fc00a34d934ce38e41a6d4fb754b59":{
      "scriptId":"u44"},
    "53f37a6c07cc4670be923e734b0f1a2e":{
      "scriptId":"u45"},
    "0504cf364d0a49eebaea93f52c4fe38e":{
      "scriptId":"u46"},
    "d7071950570a45b9a5c133504e29fc61":{
      "scriptId":"u47"},
    "fba043ca83e14de49cb3a6b033cf6383":{
      "scriptId":"u48"},
    "0c4c5d72573e40daacb8a463fa440940":{
      "scriptId":"u49"},
    "b108193b744947f89dbd6248b1c0c7db":{
      "scriptId":"u50"},
    "c391a3299eb64ab5b027782f7908a982":{
      "scriptId":"u51"},
    "27251d85e56a4bf78935cc74aac64ceb":{
      "scriptId":"u52"},
    "d9acb50b00994feb8b23ebd4ea1f9795":{
      "scriptId":"u53"},
    "0a4bc620bfd1432da200ac5e07e2fcf4":{
      "scriptId":"u54"},
    "d88d581df2c04714a7ae476554061912":{
      "scriptId":"u55"},
    "9a0fe64d952e4234be45fc074ef7cb09":{
      "scriptId":"u56"},
    "de99f6dc81004eee839525c901076d71":{
      "scriptId":"u57"},
    "8a2bf16881a9408192bd0515eb493289":{
      "scriptId":"u58"},
    "071e53330077458894ee4761759be5f7":{
      "scriptId":"u59"},
    "79db3af9a47241bfb1bd2787475b2388":{
      "scriptId":"u60"},
    "7a30813dc4b74b78991a5d23615a0f4f":{
      "scriptId":"u61"},
    "c9618324fcf54ed9a866aa6e13c04a51":{
      "scriptId":"u62"},
    "7d2474e7a05f44be93fa7439dc3e2d64":{
      "scriptId":"u63"},
    "f521b47d11bb40949230593dae35de29":{
      "scriptId":"u64"},
    "cb79147f8a204de79e62f1fe8d13ccb5":{
      "scriptId":"u65"},
    "0b205e81f35141b2bffd56a59081b6d3":{
      "scriptId":"u66"},
    "9631667bd8e44a398b6c6835ec558186":{
      "scriptId":"u67"},
    "b813d87e396046bdbc9f6149b0816a97":{
      "scriptId":"u68"},
    "a1481557b85245caa6d003b9b82304e8":{
      "scriptId":"u69"},
    "2db94eba38ed41eeab730aab677bd819":{
      "scriptId":"u70"},
    "4770f458008d41f8a66c79697fc07f9f":{
      "scriptId":"u71"},
    "5dd49f8ea78146239dce2164c85c5b83":{
      "scriptId":"u72"},
    "73e09c7f99de47d1817b9602d9d4114b":{
      "scriptId":"u73"},
    "7864147390944fe4bd8ad14f74aafede":{
      "scriptId":"u74"},
    "ccfa1a3c0fcb416d91098d636ec193a5":{
      "scriptId":"u75"},
    "5746dd67e1dc4826a896502502758299":{
      "scriptId":"u76"},
    "ccea7ef6677d4400b03a088d80ddec4f":{
      "scriptId":"u77"},
    "2195889b3a254fb5b677700005349610":{
      "scriptId":"u78"},
    "3791579e7988465e8b6eb6940fbfdf19":{
      "scriptId":"u79"},
    "fc01327fa4764c54b3fc1e39d2fb5a50":{
      "scriptId":"u80"},
    "cba75f0b421d42e7ba599f86c643cb64":{
      "scriptId":"u81"},
    "fd9755fc856748099a75d4a498e04823":{
      "scriptId":"u82"},
    "76b09f4cb3a8491f9d762b31bb4fcb0c":{
      "scriptId":"u83"},
    "e7913a1f11d144088fdf385dce8222f4":{
      "scriptId":"u84"},
    "847b373cb89c46498c0d9658db311142":{
      "scriptId":"u85"},
    "498b4cb35e714d2382838f7cb1de4ccc":{
      "scriptId":"u86"},
    "e33b289246954245aaba6772fab6145c":{
      "scriptId":"u87"},
    "5d6dc8739f2b490eba22e7f2d570506d":{
      "scriptId":"u88"},
    "8d1fcf51bfaf41eeb574f4ff5c9cb75a":{
      "scriptId":"u89"},
    "dadf447b89a446f58e2cec88296bd3a4":{
      "scriptId":"u90"},
    "732d0566735840ec975f3ceaf11d00a9":{
      "scriptId":"u91"},
    "fce8cf0211d2484186889931637e1915":{
      "scriptId":"u92"},
    "bdd78de4940642bf85af2e889e0754f1":{
      "scriptId":"u93"},
    "f94ca59a54014637ae649b339d9b770b":{
      "scriptId":"u94"},
    "ae62902f95da4e688f2266e0393d1d47":{
      "scriptId":"u95"},
    "f4e00854e98245da8953b9dd2da1fe39":{
      "scriptId":"u96"}}});