$axure.loadCurrentPage({
  "url":"应收账款明细表.html",
  "generationDate":new Date(1446432611450.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1410cc486231451da708630d2b19e5cc",
    "type":"Axure:Page",
    "name":"应收账款明细表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1ec15b2796424947a82dc65de59902be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-222,
              "y":60},
            "size":{
              "width":1823,
              "height":759}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60851e4e1c53480bbddffb18a6f743fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-222,
                  "y":60},
                "size":{
                  "width":1823,
                  "height":759}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应收账款明细表/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1ec15b2796424947a82dc65de59902be":{
      "scriptId":"u0"},
    "60851e4e1c53480bbddffb18a6f743fb":{
      "scriptId":"u1"}}});