$axure.loadCurrentPage({
  "url":"账户管理_1.html",
  "generationDate":new Date(1446432611948.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0a3d105167e14dad80da1e357a279ea2",
    "type":"Axure:Page",
    "name":"账户管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6bbc1693557444adbe24cfa5380c6762",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"27px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":1920,
              "height":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b84909bbb574a08b95a57373fa63533",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"27px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":1920,
                  "height":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u0.png"}},
{
          "id":"17920c96b9904862a5f0e08d206fd361",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":260,
              "y":86},
            "size":{
              "width":251,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d94d58b021544d49a2d06fda1a680bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":260,
                  "y":86},
                "size":{
                  "width":251,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"435e50a270fc4dd59687906202acf16e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "selected":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1320,
              "y":88},
            "size":{
              "width":47,
              "height":17},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8378961530f240a5ad6841a10cf0b4f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1320,
                  "y":88},
                "size":{
                  "width":47,
                  "height":17},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u6.png"}},
{
          "id":"d711fafe54b44558a0acfb0de6e38710",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1383,
              "y":88},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"52a4b78525944aa390ac9e28dccba365",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1406,
              "y":86},
            "size":{
              "width":163,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c23a869421466bb77f48e1333daaa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1406,
                  "y":86},
                "size":{
                  "width":163,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58789ac89e694a34a315c2611c9d5ffc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":88},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u8_line.png"}},
{
          "id":"6f329ec2e0024e90b4c0357b817f45db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1600,
              "y":86},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a370d7954fc4b1781d7a01bf8e9b670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1600,
                  "y":86},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"661ef618ec704c83a78528cfdf5fda41",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1790,
              "y":86},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"6469f1d22c1341ae8b91a1ec8c4274d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1811,
              "y":86},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a92db93272443378e7719deac9145e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1811,
                  "y":86},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27940464d8844ed19e56eec6461a8a7d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1894,
              "y":86},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"5035bbb636ca497095ba1472e2031577",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1918,
              "y":86},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"569109ddd6e344b4aa04e6b1afbe49fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1918,
                  "y":86},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74c6b9a0964d47899cc3382d33989d1f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1964,
              "y":86},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页_1/u14_line.png"}},
{
          "id":"8732dd98618e4ead99a750fe95e13f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":1988,
              "y":86},
            "size":{
              "width":37,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e6821bc3a8244488feb7d39b5be0b1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":1988,
                  "y":86},
                "size":{
                  "width":37,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u21.png"}},
{
          "id":"a52a57cd35934cc09016e6e0710c7015",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":263,
              "y":183},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afb7371c679944e7ad9dabf64b804d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":263,
                  "y":183},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"240c254cf07d4b04ac663e6c2546c439",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":147},
            "size":{
              "width":87,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2088e714bf6c4f68a240503dd3f7b5e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":147},
                "size":{
                  "width":87,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u23.png"}},
{
          "id":"302b115e63fa4d368d701d7b526880d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":288,
              "y":152},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7f09412119d41088033a8508306c149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":288,
                  "y":152},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63b3866edbbf424bb412e51c097a0306",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":451,
              "y":181},
            "size":{
              "width":309,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b57e1ab0089467b9b7095a0a911f8b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":451,
                  "y":181},
                "size":{
                  "width":309,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7c4739ced934c6cab230f352243d513",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":182},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e88a16ae58740b4b7c5a2207dbc270e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":182},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"96c41d3362554cc7b3e5e28c73f8777f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":1743,
              "y":184},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c97ea3f6764b369b24b911d48a2755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":1743,
                  "y":184},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4555bc52f55e45959ce4b2acf17c77e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1826,
              "y":181},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8056b011a6144613a5f9b5adb7755fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1826,
                  "y":181},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u35.png"}},
{
          "id":"8722e0e987b84711981eb4209586512d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":2005,
              "y":186},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dacd2fa41e244a12be833a0f79c19c59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2005,
                  "y":186},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u37.png"}},
{
          "id":"c9c4e773b421442d9fe44dfac214f237",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1775,
              "y":788},
            "size":{
              "width":285,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a92987028fff4930ab430f257c7947c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1775,
                  "y":788},
                "size":{
                  "width":285,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u130.png"}},
{
          "id":"b931d846874f44bf86edac20d10b93c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":1820,
              "y":847},
            "size":{
              "width":232,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa343e9ba714cc793803f6432404d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":1820,
                  "y":847},
                "size":{
                  "width":232,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65e07f006ded438bb6bc7be4596c7c9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1782,
              "y":814},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29615ab217ec4e67b964cc42c4fd505e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1782,
                  "y":814},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u31.png"}},
{
          "id":"9c16dbf08e314c6a9c64393654ac5441",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF337CA7},
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":100,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac7a3105e6749b38787682113403a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF337CA7},
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":100,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u136.png"}},
{
          "id":"87c02ec17f0c466c894380d35592e90e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":156},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd55a6cfb53b4c488f090c1e85c6755a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":156},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dade46938a7469db797c3df2126954d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":278},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96af417ad44541d2b2ca5a4c22281f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":278},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a1f99d0d0e14fbd8362aadaee4fe9d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":406},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e12fdf377449f59ddf3ffb8b5b352e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":406},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e84eb0af7f2f4a7f8ee0792300895be4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":534},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f4da6e8719c4a4cb4b37d188ee27352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":534},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f446bce02bc84ee5b55fd5f4e9b9f8bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":660},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131c601f874f4406b86035441b5a64ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":660},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b786882e43dc4e41885062a4ea9ac478",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":777},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac7ee5564b14ac8ab9a53e0c935d934",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":777},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f5ee7ddba664b6eabbcdba4154de308",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":884},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"221f19ed59824141af191bc78830cb7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":884},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ffe34b9ab604258a2450e9379574b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":239,
              "y":181},
            "size":{
              "width":1819,
              "height":789}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d73d714f30e2457aa4d43bc809e23562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":239,
                  "y":181},
                "size":{
                  "width":1819,
                  "height":789}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页_1/u2.png"}},
{
          "id":"b20cfee919b64765ba6eb5b109eeb704",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":349,
              "y":137},
            "size":{
              "width":120,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f727b312f6499196279ca3cafe5ca4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":349,
                  "y":137},
                "size":{
                  "width":120,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u61.png"}},
{
          "id":"a3e0c5ab9a8248b2b512f32102f35752",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":147},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26d5cc65ec1543e28b15e7ca13e68ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":147},
                "size":{
                  "width":32,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购货单/u63.png"}},
{
          "id":"3422b9dce5274c34ad246b1487913574",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":159},
            "size":{
              "width":14,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b39b77fc68464927abce90d9c056dda2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":159},
                "size":{
                  "width":14,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册登陆页面/u99.png"}},
{
          "id":"d2b482080dd546e3bd836ec3e7eb30e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":367,
              "y":153},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c167d73bb924883aa917f82c74ea558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":367,
                  "y":153},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce226952c3614d20905269563cbb5796",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":449,
              "y":131},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b4f9e27066c4cfe8da82b870df44f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":449,
                  "y":131},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e6d6cdeda054def8a3b810eab2c8ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":206},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ec09d6ddc44f99b682a79a27a5c3b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":206},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82ba14fc5d3f4f4c9bf2af5c4d2f20c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":1805,
              "y":194},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24b292a7ccbe422ab788d61252f5f1b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":1805,
                  "y":194},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u104.png"}},
{
          "id":"0a8da61f32a5421687dd613e3d059ecb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1930,
              "y":194},
            "size":{
              "width":95,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d882e86e9ca04210826f0af82819ba0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1930,
                  "y":194},
                "size":{
                  "width":95,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u106.png"}},
{
          "id":"2957394c284e4368b9b9fb83d862470a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":263,
              "y":278},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e54ae7024a89404385b2b755cfe832a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":263,
                  "y":278},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbe5e29654ef4dd68c2c83a6142bb3c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":263,
              "y":343},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f78a27699b547f3b32261525dcd0e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":263,
                  "y":343},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5e7d6fede247e7b07daf9df1a576aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":490,
              "y":343},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac98c09c6c6a4302b1eca2ad1648f909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":490,
                  "y":343},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"fbbc96aeb94445c9a28be5becb3e0d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":263,
              "y":418},
            "size":{
              "width":126,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff4cf7d6a00440899b2f1144ea1c7e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":263,
                  "y":418},
                "size":{
                  "width":126,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3909b0ca909d4d53beab25d0250e903e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":490,
              "y":418},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36218dc1a6b146a2aced38ce1503f534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":490,
                  "y":418},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"6065c93a6ec147439af389d1c5baa7eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":263,
              "y":489},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e59a9a59d1434a88d7fc347b96a36e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":263,
                  "y":489},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd78a600ae3142d39c8b0667fdbfb5ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":490,
              "y":489},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39fbfa50662847c5b901604a695b32cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":489},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"1658ce169bbb4bfa98253dbc97885be4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":263,
              "y":563},
            "size":{
              "width":76,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c114c706979c4936a35767fd4b5d8c4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":263,
                  "y":563},
                "size":{
                  "width":76,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f60aafb082ed426b8d3d79b8ba5f7e75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":490,
              "y":563},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27896ea72dc047b3990ef98c3d2921a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":563},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"7190f291af944172a2028e7695638bdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":263,
              "y":644},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a8af8bf662b47dcab9ddd0d47be38ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":263,
                  "y":644},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63a334c0b652498495ecbb94616a01dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":490,
              "y":644},
            "size":{
              "width":370,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dae8650360a14fcb8a4cbcf716db6606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":644},
                "size":{
                  "width":370,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基础参数/u79.png"}},
{
          "id":"38f09db23867460192305b217b67042e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":892,
              "y":489},
            "size":{
              "width":168,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b63bb838b6c486ea911b4451526fb9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":892,
                  "y":489},
                "size":{
                  "width":168,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理_1/u99.png"}},
{
          "id":"77426599104e47d881ddb6ff1d3a81e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":490,
              "y":597},
            "size":{
              "width":356,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bfa044235664f1e943310fc7dde505e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":597},
                "size":{
                  "width":356,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac90444876d747be917608302faee201",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"400",
            "location":{
              "x":488,
              "y":278},
            "size":{
              "width":81,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf277fb8208470999df380080099a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"400",
                "location":{
                  "x":488,
                  "y":278},
                "size":{
                  "width":81,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6bbc1693557444adbe24cfa5380c6762":{
      "scriptId":"u0"},
    "2b84909bbb574a08b95a57373fa63533":{
      "scriptId":"u1"},
    "17920c96b9904862a5f0e08d206fd361":{
      "scriptId":"u2"},
    "d94d58b021544d49a2d06fda1a680bd8":{
      "scriptId":"u3"},
    "435e50a270fc4dd59687906202acf16e":{
      "scriptId":"u4"},
    "8378961530f240a5ad6841a10cf0b4f6":{
      "scriptId":"u5"},
    "d711fafe54b44558a0acfb0de6e38710":{
      "scriptId":"u6"},
    "52a4b78525944aa390ac9e28dccba365":{
      "scriptId":"u7"},
    "a9c23a869421466bb77f48e1333daaa1":{
      "scriptId":"u8"},
    "58789ac89e694a34a315c2611c9d5ffc":{
      "scriptId":"u9"},
    "6f329ec2e0024e90b4c0357b817f45db":{
      "scriptId":"u10"},
    "5a370d7954fc4b1781d7a01bf8e9b670":{
      "scriptId":"u11"},
    "661ef618ec704c83a78528cfdf5fda41":{
      "scriptId":"u12"},
    "6469f1d22c1341ae8b91a1ec8c4274d7":{
      "scriptId":"u13"},
    "9a92db93272443378e7719deac9145e4":{
      "scriptId":"u14"},
    "27940464d8844ed19e56eec6461a8a7d":{
      "scriptId":"u15"},
    "5035bbb636ca497095ba1472e2031577":{
      "scriptId":"u16"},
    "569109ddd6e344b4aa04e6b1afbe49fd":{
      "scriptId":"u17"},
    "74c6b9a0964d47899cc3382d33989d1f":{
      "scriptId":"u18"},
    "8732dd98618e4ead99a750fe95e13f50":{
      "scriptId":"u19"},
    "0e6821bc3a8244488feb7d39b5be0b1d":{
      "scriptId":"u20"},
    "a52a57cd35934cc09016e6e0710c7015":{
      "scriptId":"u21"},
    "afb7371c679944e7ad9dabf64b804d88":{
      "scriptId":"u22"},
    "240c254cf07d4b04ac663e6c2546c439":{
      "scriptId":"u23"},
    "2088e714bf6c4f68a240503dd3f7b5e1":{
      "scriptId":"u24"},
    "302b115e63fa4d368d701d7b526880d5":{
      "scriptId":"u25"},
    "b7f09412119d41088033a8508306c149":{
      "scriptId":"u26"},
    "63b3866edbbf424bb412e51c097a0306":{
      "scriptId":"u27"},
    "7b57e1ab0089467b9b7095a0a911f8b1":{
      "scriptId":"u28"},
    "f7c4739ced934c6cab230f352243d513":{
      "scriptId":"u29"},
    "5e88a16ae58740b4b7c5a2207dbc270e":{
      "scriptId":"u30"},
    "96c41d3362554cc7b3e5e28c73f8777f":{
      "scriptId":"u31"},
    "d8c97ea3f6764b369b24b911d48a2755":{
      "scriptId":"u32"},
    "4555bc52f55e45959ce4b2acf17c77e9":{
      "scriptId":"u33"},
    "8056b011a6144613a5f9b5adb7755fd0":{
      "scriptId":"u34"},
    "8722e0e987b84711981eb4209586512d":{
      "scriptId":"u35"},
    "dacd2fa41e244a12be833a0f79c19c59":{
      "scriptId":"u36"},
    "c9c4e773b421442d9fe44dfac214f237":{
      "scriptId":"u37"},
    "a92987028fff4930ab430f257c7947c5":{
      "scriptId":"u38"},
    "b931d846874f44bf86edac20d10b93c7":{
      "scriptId":"u39"},
    "4fa343e9ba714cc793803f6432404d99":{
      "scriptId":"u40"},
    "65e07f006ded438bb6bc7be4596c7c9a":{
      "scriptId":"u41"},
    "29615ab217ec4e67b964cc42c4fd505e":{
      "scriptId":"u42"},
    "9c16dbf08e314c6a9c64393654ac5441":{
      "scriptId":"u43"},
    "dac7a3105e6749b38787682113403a73":{
      "scriptId":"u44"},
    "87c02ec17f0c466c894380d35592e90e":{
      "scriptId":"u45"},
    "fd55a6cfb53b4c488f090c1e85c6755a":{
      "scriptId":"u46"},
    "4dade46938a7469db797c3df2126954d":{
      "scriptId":"u47"},
    "96af417ad44541d2b2ca5a4c22281f1e":{
      "scriptId":"u48"},
    "8a1f99d0d0e14fbd8362aadaee4fe9d7":{
      "scriptId":"u49"},
    "70e12fdf377449f59ddf3ffb8b5b352e":{
      "scriptId":"u50"},
    "e84eb0af7f2f4a7f8ee0792300895be4":{
      "scriptId":"u51"},
    "0f4da6e8719c4a4cb4b37d188ee27352":{
      "scriptId":"u52"},
    "f446bce02bc84ee5b55fd5f4e9b9f8bb":{
      "scriptId":"u53"},
    "131c601f874f4406b86035441b5a64ce":{
      "scriptId":"u54"},
    "b786882e43dc4e41885062a4ea9ac478":{
      "scriptId":"u55"},
    "5ac7ee5564b14ac8ab9a53e0c935d934":{
      "scriptId":"u56"},
    "7f5ee7ddba664b6eabbcdba4154de308":{
      "scriptId":"u57"},
    "221f19ed59824141af191bc78830cb7f":{
      "scriptId":"u58"},
    "7ffe34b9ab604258a2450e9379574b73":{
      "scriptId":"u59"},
    "d73d714f30e2457aa4d43bc809e23562":{
      "scriptId":"u60"},
    "b20cfee919b64765ba6eb5b109eeb704":{
      "scriptId":"u61"},
    "35f727b312f6499196279ca3cafe5ca4":{
      "scriptId":"u62"},
    "a3e0c5ab9a8248b2b512f32102f35752":{
      "scriptId":"u63"},
    "26d5cc65ec1543e28b15e7ca13e68ed9":{
      "scriptId":"u64"},
    "3422b9dce5274c34ad246b1487913574":{
      "scriptId":"u65"},
    "b39b77fc68464927abce90d9c056dda2":{
      "scriptId":"u66"},
    "d2b482080dd546e3bd836ec3e7eb30e9":{
      "scriptId":"u67"},
    "1c167d73bb924883aa917f82c74ea558":{
      "scriptId":"u68"},
    "ce226952c3614d20905269563cbb5796":{
      "scriptId":"u69"},
    "5b4f9e27066c4cfe8da82b870df44f78":{
      "scriptId":"u70"},
    "8e6d6cdeda054def8a3b810eab2c8ffe":{
      "scriptId":"u71"},
    "c3ec09d6ddc44f99b682a79a27a5c3b4":{
      "scriptId":"u72"},
    "82ba14fc5d3f4f4c9bf2af5c4d2f20c1":{
      "scriptId":"u73"},
    "24b292a7ccbe422ab788d61252f5f1b6":{
      "scriptId":"u74"},
    "0a8da61f32a5421687dd613e3d059ecb":{
      "scriptId":"u75"},
    "d882e86e9ca04210826f0af82819ba0a":{
      "scriptId":"u76"},
    "2957394c284e4368b9b9fb83d862470a":{
      "scriptId":"u77"},
    "e54ae7024a89404385b2b755cfe832a9":{
      "scriptId":"u78"},
    "dbe5e29654ef4dd68c2c83a6142bb3c0":{
      "scriptId":"u79"},
    "0f78a27699b547f3b32261525dcd0e2d":{
      "scriptId":"u80"},
    "1f5e7d6fede247e7b07daf9df1a576aa":{
      "scriptId":"u81"},
    "ac98c09c6c6a4302b1eca2ad1648f909":{
      "scriptId":"u82"},
    "fbbc96aeb94445c9a28be5becb3e0d84":{
      "scriptId":"u83"},
    "aff4cf7d6a00440899b2f1144ea1c7e9":{
      "scriptId":"u84"},
    "3909b0ca909d4d53beab25d0250e903e":{
      "scriptId":"u85"},
    "36218dc1a6b146a2aced38ce1503f534":{
      "scriptId":"u86"},
    "6065c93a6ec147439af389d1c5baa7eb":{
      "scriptId":"u87"},
    "a4e59a9a59d1434a88d7fc347b96a36e":{
      "scriptId":"u88"},
    "fd78a600ae3142d39c8b0667fdbfb5ee":{
      "scriptId":"u89"},
    "39fbfa50662847c5b901604a695b32cc":{
      "scriptId":"u90"},
    "1658ce169bbb4bfa98253dbc97885be4":{
      "scriptId":"u91"},
    "c114c706979c4936a35767fd4b5d8c4e":{
      "scriptId":"u92"},
    "f60aafb082ed426b8d3d79b8ba5f7e75":{
      "scriptId":"u93"},
    "27896ea72dc047b3990ef98c3d2921a1":{
      "scriptId":"u94"},
    "7190f291af944172a2028e7695638bdd":{
      "scriptId":"u95"},
    "2a8af8bf662b47dcab9ddd0d47be38ea":{
      "scriptId":"u96"},
    "63a334c0b652498495ecbb94616a01dc":{
      "scriptId":"u97"},
    "dae8650360a14fcb8a4cbcf716db6606":{
      "scriptId":"u98"},
    "38f09db23867460192305b217b67042e":{
      "scriptId":"u99"},
    "5b63bb838b6c486ea911b4451526fb9d":{
      "scriptId":"u100"},
    "77426599104e47d881ddb6ff1d3a81e8":{
      "scriptId":"u101"},
    "0bfa044235664f1e943310fc7dde505e":{
      "scriptId":"u102"},
    "ac90444876d747be917608302faee201":{
      "scriptId":"u103"},
    "cbf277fb8208470999df380080099a03":{
      "scriptId":"u104"}}});